Repository Azure/azure-quickstart-templates, pull requests merged in 2018-08, with the labels that each got.

#5004 SQL MI template with jumpbox
  201-sqlmi-new-vnet-w-jumpbox/.ci_skip
  201-sqlmi-new-vnet-w-jumpbox/README.md
  201-sqlmi-new-vnet-w-jumpbox/azuredeploy.json
  201-sqlmi-new-vnet-w-jumpbox/azuredeploy.parameters.json
  201-sqlmi-new-vnet-w-jumpbox/installSSMS.ps1
  201-sqlmi-new-vnet-w-jumpbox/metadata.json
Labels: CI PASS

#4956 Updated to use Managed disks
  101-recovery-services-create-vm-and-configure-backup/azuredeploy.json
  101-recovery-services-create-vm-and-configure-backup/azuredeploy.parameters.json
  101-recovery-services-create-vm-and-configure-backup/metadata.json
Labels: awaiting-author-response

#5042 Updated to use Managed disks
  201-vm-sql-full-keyvault/azuredeploy.json
  201-vm-sql-full-keyvault/azuredeploy.parameters.json
  201-vm-sql-full-keyvault/metadata.json
Labels: awaiting-author-response

#5084 updated to use Managed Disks
  bosh-setup/azuredeploy.json
  bosh-setup/azuredeploy.parameters.json
  bosh-setup/metadata.json
Labels: merge-conflict

#5079 updated to use Managed Disks
  mongodb-on-centos/azuredeploy.json
  mongodb-on-centos/azuredeploy.parameters.json
  mongodb-on-centos/metadata.json
Labels: remove unused storage

#5072 updated to use Managed Disks
  thinkbox-deadline/azuredeploy.json
  thinkbox-deadline/metadata.json
Labels: remove unused storage

#5063 Updated to use Managed disks
  eset-vm-extension/azuredeploy.json
  eset-vm-extension/azuredeploy.parameters.json
  eset-vm-extension/metadata.json
Labels: remove unused storage

#5022 updated to use Managed Disks
  spark-on-ubuntu/azuredeploy.json
  spark-on-ubuntu/azuredeploy.parameters.json
  spark-on-ubuntu/jumpbox-resources-disabled.json
  spark-on-ubuntu/jumpbox-resources-enabled.json
  spark-on-ubuntu/metadata.json
  spark-on-ubuntu/shared-resources.json
Labels: awaiting-author-response
