Repository Azure/azure-quickstart-templates, pull requests merged in 2019-04, with the labels that each got.

#5915 deprecated acs-dcos
  101-acs-dcos/README.md
  101-acs-dcos/metadata.json
Labels: awaiting-author-response

#5412 Artifactory enterprise marketplace
  artifactory-enterprise/LICENSE
  artifactory-enterprise/README.md
  artifactory-enterprise/azuredeploy.json
  artifactory-enterprise/azuredeploy.parameters.json
  artifactory-enterprise/createUiDefinition.json
  artifactory-enterprise/images/HA_Diagram.png
  artifactory-enterprise/images/Parameters.png
  artifactory-enterprise/images/add_licenses.png
  artifactory-enterprise/mainTemplate.json
  artifactory-enterprise/metadata.json
  artifactory-enterprise/nested/azureDBDeploy.json
  artifactory-enterprise/scripts/install_artifactory.sh
  test/template-validation-tests/package.json
Labels: CI PASS

#5952 Added instant recovery retention
  101-recovery-services-weekly-backup-policy-create/README.md
  101-recovery-services-weekly-backup-policy-create/azuredeploy.json
Labels: bug

#5950 Azure Backup for SQL Server in Azure Virtual Machines
  101-recovery-services-vm-workload-backup/README.md
  101-recovery-services-vm-workload-backup/azuredeploy.json
  101-recovery-services-vm-workload-backup/azuredeploy.parameters.json
  101-recovery-services-vm-workload-backup/images/WorkloadBackup.png
  101-recovery-services-vm-workload-backup/metadata.json
  101-recovery-services-vm-workload-backup/prereqs/prereq.azuredeploy.json
  101-recovery-services-vm-workload-backup/prereqs/prereq.azuredeploy.parameters.json
Labels: bug

#5768 Time series insights with iothub
  201-timeseriesinsights-environment-payg-with-iothub/README.md
  201-timeseriesinsights-environment-payg-with-iothub/azuredeploy.json
  201-timeseriesinsights-environment-payg-with-iothub/azuredeploy.parameters.json
  201-timeseriesinsights-environment-payg-with-iothub/metadata.json
  201-timeseriesinsights-environment-with-eventhub/README.md
  201-timeseriesinsights-environment-with-eventhub/azuredeploy.json
Labels: CI Update
