Repository Azure/azure-quickstart-templates, pull requests merged in 2020-11, with the labels that each got.

#8490 adjust tab spaces
  managementgroup-deployments/mg-policy/azuredeploy.json
  managementgroup-deployments/mg-policy/metadata.json
Labels: manual validation

#8485 Updates ARM template files - RBAC custom role
  subscription-deployments/create-role-def/README.md
  subscription-deployments/create-role-def/azuredeploy.json
  subscription-deployments/create-role-def/azuredeploy.parameters.json
  subscription-deployments/create-role-def/metadata.json
Labels: manual validation

#8435 created rg deployment
  subscription-deployments/create-rg/README.md
  subscription-deployments/create-rg/azuredeploy.json
  subscription-deployments/create-rg/azuredeploy.parameters.json
  subscription-deployments/create-rg/metadata.json
Labels: CI PASS, manual validation

#8405 First commit of sas9.4-viya quick start for Azure Resource Manager
  sas9.4-viya/README.md
  sas9.4-viya/azuredeploy.json
  sas9.4-viya/azuredeploy.parameters.json
  sas9.4-viya/client_install.zip
  sas9.4-viya/images/configuration.jpg
  sas9.4-viya/images/forward_ports.jpg
  sas9.4-viya/images/pubip_port.jpg
  sas9.4-viya/images/rdp_connection.jpg
  sas9.4-viya/images/sas94-viya-architecture-diagram.svg
  sas9.4-viya/images/source_destination.jpg
  sas9.4-viya/images/vmuser_ppk.jpg
  sas9.4-viya/metadata.json
  sas9.4-viya/nestedtemplates/access_policy.json
  sas9.4-viya/nestedtemplates/role_assignments.json
  sas9.4-viya/nestedtemplates/vm_linux_extension.json
  sas9.4-viya/nestedtemplates/vm_windows_extension.json
  sas9.4-viya/properties/response-properties.tar.gz
  sas9.4-viya/properties/viya-ark.tar.gz
  sas9.4-viya/sas_client_install.ps1
  sas9.4-viya/scripts/ansible_setup.sh
  sas9.4-viya/scripts/ansible_ssl.sh
  sas9.4-viya/scripts/compute_config.sh
  sas9.4-viya/scripts/compute_install.sh
  sas9.4-viya/scripts/meta_config.sh
  sas9.4-viya/scripts/meta_install.sh
  sas9.4-viya/scripts/mid_config.sh
  sas9.4-viya/scripts/mid_install.sh
  sas9.4-viya/scripts/sasapp_prereq.sh
  sas9.4-viya/scripts/viya_ark.sh
  sas9.4-viya/scripts/viya_prereq.sh
  sas9.4-viya/scripts/viyainstall.sh
Labels: needs/author feedback

#8489 Update to 201-vm-monitoring-diagnostics-extension/azuredeploy.json
  201-vm-monitoring-diagnostics-extension/README.md
  201-vm-monitoring-diagnostics-extension/azuredeploy.json
  201-vm-monitoring-diagnostics-extension/metadata.json
Labels: needs/author feedback
