Repository Azure/azure-quickstart-templates, pull requests merged in 2021-06, with the labels that each got.

#10446 Moving to subdir and updates
  quickstarts/microsoft.hdinsight/hdinsight-custom-ambari-db/azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-custom-ambari-db/azuredeploy.parameters.json
  quickstarts/microsoft.hdinsight/hdinsight-custom-ambari-db/metadata.json
  quickstarts/microsoft.hdinsight/hdinsight-custom-ambari-db/prereqs/prereq.azuredeploy.json
Labels: best practices violations

#10673 Updating to use the latest GA version
  101-cosmosdb-sql-rbac/azuredeploy.json
Labels: ROOT

#10630 FIX-TEMPLATE: 301-multi-vmss-windows
  301-multi-vmss-windows/azuredeploy.json
  301-multi-vmss-windows/azuredeploy.parameters.json
Labels: ROOT, best practices violations, readme violations

#10619 minimal update to date and owner
  quickstarts/microsoft.hdinsight/hdinsight-custom-ambari-db/metadata.json
  quickstarts/microsoft.hdinsight/hdinsight-custom-ambari-db/prereqs/prereq.azuredeploy.json
Labels: best practices violations

#10613 COPY: 201-vm-diagnostics-extension-windows to quickstarts\microsoft.compute
  quickstarts/microsoft.compute/vm-diagnostics-extension-windows/README.md
  quickstarts/microsoft.compute/vm-diagnostics-extension-windows/azuredeploy.json
  quickstarts/microsoft.compute/vm-diagnostics-extension-windows/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-diagnostics-extension-windows/metadata.json
Labels: best practices violations

#10610 COPY: 201-aci-linuxcontainer-healthprobe to quickstarts\microsoft.containerinstance
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-healthprobe/README.md
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-healthprobe/azuredeploy.json
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-healthprobe/azuredeploy.parameters.json
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-healthprobe/metadata.json
Labels: best practices violations

#10609 COPY: 101-webappazure-oms-monitoring to quickstarts\microsoft.web
  quickstarts/microsoft.web/webappazure-oms-monitoring/README.md
  quickstarts/microsoft.web/webappazure-oms-monitoring/azuredeploy.json
  quickstarts/microsoft.web/webappazure-oms-monitoring/azuredeploy.parameters.json
  quickstarts/microsoft.web/webappazure-oms-monitoring/images/azure-web-apps-analytics-tile.png
  quickstarts/microsoft.web/webappazure-oms-monitoring/images/web-app-search-example.png
  quickstarts/microsoft.web/webappazure-oms-monitoring/images/web-apps-dash01.png
  quickstarts/microsoft.web/webappazure-oms-monitoring/images/web-apps-dash02.png
  quickstarts/microsoft.web/webappazure-oms-monitoring/metadata.json
Labels: best practices violations

#10597 COPY: kubernetes-on-ubuntu-vmss to demos
  demos/kubernetes-on-ubuntu-vmss/README.md
  demos/kubernetes-on-ubuntu-vmss/azuredeploy.json
  demos/kubernetes-on-ubuntu-vmss/azuredeploy.parameters.json
  demos/kubernetes-on-ubuntu-vmss/metadata.json
  demos/kubernetes-on-ubuntu-vmss/scripts/cloud-init-master.sh
  demos/kubernetes-on-ubuntu-vmss/scripts/cloud-init-vmss.sh
Labels: best practices violations

#10550 Update README.md - Fixing header issues.
  informatica-adf-hdinsight-powerbi/README.md
Labels: ROOT, best practices violations, readme violations

#10551 FIX-TEMPLATE: docker-parse
  docker-parse/azuredeploy.json
  docker-parse/metadata.json
Labels: ROOT, best practices violations

#10552 FIX-TEMPLATE: docker-neo4j
  docker-neo4j/azuredeploy.json
  docker-neo4j/metadata.json
  docker-neo4j/scripts/setup_data_disk.sh
Labels: ROOT, best practices violations

#10553 FIX-TEMPLATE: docker-ckan
  docker-ckan/azuredeploy.json
  docker-ckan/metadata.json
Labels: ROOT, best practices violations

#10572 FIX-TEMPLATE: 201-cdn-with-ruleseengine-cacheoverride
  201-cdn-with-ruleseengine-cacheoverride/metadata.json
Labels: ROOT, best practices violations

#10593 COPY: 301-drupal8-vmss-glusterfs-mysql to application-workloads\drupal
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/README.md
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/azuredeploy.json
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/azuredeploy.parameters.json
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/images/AccessingDrupalSite.jpg
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/images/Deployment with new mysql server.jpg
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/images/Drupal 8 ARM template overview.jpg
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/images/azureResourceExplorer.png
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/metadata.json
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/scripts/install_drupal.sh
  application-workloads/drupal/drupal8-vmss-glusterfs-mysql/scripts/mount-azure-fileshare.sh
Labels: best practices violations

#10612 COPY: 201-dsc-linux-public-storage-on-ubuntu to quickstarts\microsoft.compute
  quickstarts/microsoft.compute/dsc-linux-public-storage-on-ubuntu/README.md
  quickstarts/microsoft.compute/dsc-linux-public-storage-on-ubuntu/azuredeploy.json
  quickstarts/microsoft.compute/dsc-linux-public-storage-on-ubuntu/azuredeploy.parameters.json
  quickstarts/microsoft.compute/dsc-linux-public-storage-on-ubuntu/metadata.json
  quickstarts/microsoft.compute/dsc-linux-public-storage-on-ubuntu/register-azure-automation.parameters.json
Labels: best practices violations

#9646 FIX-TEMPLATE: wordpress-mysql-replication
  wordpress-mysql-replication/azuredeploy.json
  wordpress-mysql-replication/nested/mysql-replication.json
  wordpress-mysql-replication/nested/website.json
Labels: ROOT, best practices violations, metadata violations, readme violations

#10167 FIX-TEMPLATE: visual-studio-vstsbuildagent-vm
  visual-studio-vstsbuildagent-vm/InstallVSTSAgent.ps1
  visual-studio-vstsbuildagent-vm/azuredeploy.json
  visual-studio-vstsbuildagent-vm/azuredeploy.parameters.json
Labels: ROOT, best practices violations, readme violations

#10687 COPY: wordpress-mysql-replication to application-workloads\wordpress
  application-workloads/wordpress/wordpress-mysql-replication/README.md
  application-workloads/wordpress/wordpress-mysql-replication/azuredeploy.json
  application-workloads/wordpress/wordpress-mysql-replication/azuredeploy.parameters.json
  application-workloads/wordpress/wordpress-mysql-replication/metadata.json
  application-workloads/wordpress/wordpress-mysql-replication/nested/mysql-replication.json
  application-workloads/wordpress/wordpress-mysql-replication/nested/vnet-existing.json
  application-workloads/wordpress/wordpress-mysql-replication/nested/vnet-new.json
  application-workloads/wordpress/wordpress-mysql-replication/nested/website.json
  application-workloads/wordpress/wordpress-mysql-replication/scripts/azuremysql.sh
  application-workloads/wordpress/wordpress-mysql-replication/scripts/my.cnf.template
  application-workloads/wordpress/wordpress-mysql-replication/scripts/switchMySQLNatRule.ps1
Labels: best practices violations

#10686 COPY: visual-studio-vstsbuildagent-vm to application-workloads\visualstudio
  application-workloads/visualstudio/visual-studio-vstsbuildagent-vm/InstallVSTSAgent.ps1
  application-workloads/visualstudio/visual-studio-vstsbuildagent-vm/README.md
  application-workloads/visualstudio/visual-studio-vstsbuildagent-vm/azuredeploy.json
  application-workloads/visualstudio/visual-studio-vstsbuildagent-vm/azuredeploy.parameters.json
  application-workloads/visualstudio/visual-studio-vstsbuildagent-vm/metadata.json
Labels: best practices violations

#10685 COPY: oms-scomacs-solution to demos
  demos/oms-scomacs-solution/README.md
  demos/oms-scomacs-solution/azuredeploy.json
  demos/oms-scomacs-solution/azuredeploy.parameters.json
  demos/oms-scomacs-solution/azuredeploy.parameters.us.json
  demos/oms-scomacs-solution/images/aeacssummarytile.png
  demos/oms-scomacs-solution/images/aearmscomacs.png
  demos/oms-scomacs-solution/images/aeomsworkspace.png
  demos/oms-scomacs-solution/images/aescomacssolutionview.png
  demos/oms-scomacs-solution/images/aescomacstemplatedeploy.png
  demos/oms-scomacs-solution/metadata.json
Labels: best practices violations

#10684 COPY: oms-hyperv-replica-solution to demos
  demos/oms-hyperv-replica-solution/README.md
  demos/oms-hyperv-replica-solution/assets/OMSDataInjection.zip
  demos/oms-hyperv-replica-solution/azuredeploy.json
  demos/oms-hyperv-replica-solution/azuredeploy.parameters.json
  demos/oms-hyperv-replica-solution/azuredeploy.parameters.us.json
  demos/oms-hyperv-replica-solution/images/hypervReplicaOMSLinkSchedule.png
  demos/oms-hyperv-replica-solution/images/hypervReplicaOMSOverview01.PNG
  demos/oms-hyperv-replica-solution/images/hypervReplicaOMSOverview02.PNG
  demos/oms-hyperv-replica-solution/images/hypervReplicaOMSSchedule.png
  demos/oms-hyperv-replica-solution/images/hypervReplicaOMSTile.png
  demos/oms-hyperv-replica-solution/metadata.json
  demos/oms-hyperv-replica-solution/scripts/Publish-omsHyperVReplica.ps1
Labels: best practices violations

#10683 COPY: docker-parse to application-workloads\parse
  application-workloads/parse/docker-parse/README.md
  application-workloads/parse/docker-parse/azuredeploy.json
  application-workloads/parse/docker-parse/azuredeploy.parameters.json
  application-workloads/parse/docker-parse/metadata.json
Labels: best practices violations

#10682 COPY: docker-neo4j to application-workloads\neo4j
  application-workloads/neo4j/docker-neo4j/README.md
  application-workloads/neo4j/docker-neo4j/azuredeploy.json
  application-workloads/neo4j/docker-neo4j/azuredeploy.parameters.json
  application-workloads/neo4j/docker-neo4j/metadata.json
  application-workloads/neo4j/docker-neo4j/scripts/setup_data_disk.sh
Labels: best practices violations

#10681 COPY: docker-ckan to application-workloads\ckan
  application-workloads/ckan/docker-ckan/README.md
  application-workloads/ckan/docker-ckan/azuredeploy.json
  application-workloads/ckan/docker-ckan/azuredeploy.parameters.json
  application-workloads/ckan/docker-ckan/metadata.json
Labels: best practices violations

#10320 FIX-TEMPLATE: 101-backup-create-storage-account-enable-protection
  101-backup-create-storage-account-enable-protection/azuredeploy.json
Labels: ROOT

#10465 COPY: 101-machine-learning-compute-attach-aks to quickstarts\Microsoft.MachineLearningServices
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-aks/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-aks/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-aks/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-aks/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-aks/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-aks/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-aks/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10466 COPY: 101-machine-learning-compute-create-akscompute to quickstarts\Microsoft.MachineLearningServices
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-create-akscompute/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-create-akscompute/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-create-akscompute/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-create-akscompute/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-create-akscompute/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-create-akscompute/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-create-akscompute/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10467 COPY: 101-machine-learning-dataset-create-tabular-from-sql-query to quickstarts\Microsoft.MachineLearningServices
  quickstarts/microsoft.machinelearningservices/machine-learning-dataset-create-tabular-from-sql-query/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-dataset-create-tabular-from-sql-query/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataset-create-tabular-from-sql-query/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataset-create-tabular-from-sql-query/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataset-create-tabular-from-sql-query/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataset-create-tabular-from-sql-query/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataset-create-tabular-from-sql-query/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10468 COPY: 101-machine-learning-datastore-create-sql to quickstarts\Microsoft.MachineLearningServices
  quickstarts/microsoft.machinelearningservices/machine-learning-datastore-create-sql/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-datastore-create-sql/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-datastore-create-sql/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-datastore-create-sql/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-datastore-create-sql/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-datastore-create-sql/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-datastore-create-sql/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10469 COPY: 101-machine-learning-service-create-aks to quickstarts\Microsoft.MachineLearningServices
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/prereqs/101-machine-learning-compute-create-akscompute-azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/prereqs/Driver.py
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/prereqs/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-service-create-aks/prereqs/sklearn_regression_model.pkl
Labels: best practices violations

#10470 COPY: 101-sql-elastic-pool-create to quickstarts\microsoft.sql
  quickstarts/microsoft.sql/sql-elastic-pool-create/README.md
  quickstarts/microsoft.sql/sql-elastic-pool-create/azuredeploy.json
  quickstarts/microsoft.sql/sql-elastic-pool-create/azuredeploy.parameters.json
  quickstarts/microsoft.sql/sql-elastic-pool-create/metadata.json
Labels: best practices violations

#10476 COPY: 201-cdn-with-web-app to quickstarts\microsoft.cdn
  quickstarts/microsoft.cdn/cdn-with-web-app/README.md
  quickstarts/microsoft.cdn/cdn-with-web-app/metadata.json
Labels: PORTAL SAMPLE

#10477 COPY: 201-data-factory-v2-azure-sql-database-to-sql-data-warehouse-copy to quickstarts\Microsoft.DataFactory
  quickstarts/microsoft.datafactory/data-factory-v2-azure-sql-database-to-sql-data-warehouse-copy/README.md
  quickstarts/microsoft.datafactory/data-factory-v2-azure-sql-database-to-sql-data-warehouse-copy/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-azure-sql-database-to-sql-data-warehouse-copy/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-azure-sql-database-to-sql-data-warehouse-copy/metadata.json
  quickstarts/microsoft.datafactory/data-factory-v2-azure-sql-database-to-sql-data-warehouse-copy/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-azure-sql-database-to-sql-data-warehouse-copy/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10478 COPY: 201-dependency-between-scripts-using-extensions to quickstarts\Microsoft.DataFactory
  quickstarts/microsoft.datafactory/dependency-between-scripts-using-extensions/README.md
  quickstarts/microsoft.datafactory/dependency-between-scripts-using-extensions/azuredeploy.json
  quickstarts/microsoft.datafactory/dependency-between-scripts-using-extensions/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/dependency-between-scripts-using-extensions/metadata.json
  quickstarts/microsoft.datafactory/dependency-between-scripts-using-extensions/scripts/mongo-configure-ubuntu.sh
  quickstarts/microsoft.datafactory/dependency-between-scripts-using-extensions/scripts/mongo-install-ubuntu.sh
  quickstarts/microsoft.datafactory/dependency-between-scripts-using-extensions/templates/install-mongo.json
Labels: best practices violations

#10481 COPY: 201-vmss-linux-jumpbox to demos
  demos/vmss-linux-jumpbox/README.md
  demos/vmss-linux-jumpbox/azuredeploy.json
  demos/vmss-linux-jumpbox/azuredeploy.parameters.json
  demos/vmss-linux-jumpbox/metadata.json
Labels: best practices violations

#10482 COPY: 201-vsts-cloudloadtest-rig-existing-vnet to application-workloads\visualstudio
  application-workloads/visualstudio/vsts-cloudloadtest-rig-existing-vnet/README.md
  application-workloads/visualstudio/vsts-cloudloadtest-rig-existing-vnet/azuredeploy.json
  application-workloads/visualstudio/vsts-cloudloadtest-rig-existing-vnet/azuredeploy.parameters.json
  application-workloads/visualstudio/vsts-cloudloadtest-rig-existing-vnet/images/CLTAgentsOnVnet.png
  application-workloads/visualstudio/vsts-cloudloadtest-rig-existing-vnet/metadata.json
Labels: best practices violations

#10484 COPY: 301-create-ad-forest-with-subdomain to application-workloads\active-directory
  application-workloads/active-directory/create-ad-forest-with-subdomain/Configure-DSC.ps1
  application-workloads/active-directory/create-ad-forest-with-subdomain/DSC/ConfigureADNextDC.ps1.zip
  application-workloads/active-directory/create-ad-forest-with-subdomain/DSC/CreateADChildDomainDC1.ps1.zip
  application-workloads/active-directory/create-ad-forest-with-subdomain/DSC/CreateADRootDC1.ps1.zip
  application-workloads/active-directory/create-ad-forest-with-subdomain/README.md
  application-workloads/active-directory/create-ad-forest-with-subdomain/azuredeploy.json
  application-workloads/active-directory/create-ad-forest-with-subdomain/azuredeploy.parameters.json
  application-workloads/active-directory/create-ad-forest-with-subdomain/metadata.json
  application-workloads/active-directory/create-ad-forest-with-subdomain/nested/CreateAndPrepnewVM.json
  application-workloads/active-directory/create-ad-forest-with-subdomain/nested/configureADNextDC.json
  application-workloads/active-directory/create-ad-forest-with-subdomain/nested/createChildDomain.json
  application-workloads/active-directory/create-ad-forest-with-subdomain/nested/createForest.json
  application-workloads/active-directory/create-ad-forest-with-subdomain/nested/vnet-with-dns-server.json
  application-workloads/active-directory/create-ad-forest-with-subdomain/nested/vnet.json
Labels: best practices violations

#10486 COPY: 301-eventhub-namespace-vnet to quickstarts\Microsoft.EventHub
  quickstarts/microsoft.eventhub/eventhub-namespace-vnet/README.md
  quickstarts/microsoft.eventhub/eventhub-namespace-vnet/azuredeploy.json
  quickstarts/microsoft.eventhub/eventhub-namespace-vnet/azuredeploy.parameters.json
  quickstarts/microsoft.eventhub/eventhub-namespace-vnet/metadata.json
Labels: best practices violations

#10487 COPY: cohesive-vns3-free-multiclient-overlay-linux to application-workloads\cohesive
  application-workloads/cohesive/cohesive-vns3-free-multiclient-overlay-linux/README.md
  application-workloads/cohesive/cohesive-vns3-free-multiclient-overlay-linux/azuredeploy.json
  application-workloads/cohesive/cohesive-vns3-free-multiclient-overlay-linux/azuredeploy.parameters.json
  application-workloads/cohesive/cohesive-vns3-free-multiclient-overlay-linux/metadata.json
  application-workloads/cohesive/cohesive-vns3-free-multiclient-overlay-linux/scripts/customextensionlinux.sh
Labels: best practices violations

#10488 COPY: concourse-ci to application-workloads\concourse
  application-workloads/concourse/concourse-ci/CHANGELOG.md
  application-workloads/concourse/concourse-ci/README.md
  application-workloads/concourse/concourse-ci/azuredeploy.json
  application-workloads/concourse/concourse-ci/azuredeploy.parameters.json
  application-workloads/concourse/concourse-ci/generate-customdata.json
  application-workloads/concourse/concourse-ci/manifests/bosh.yml
  application-workloads/concourse/concourse-ci/manifests/cloud-config.yml
  application-workloads/concourse/concourse-ci/manifests/concourse.yml
  application-workloads/concourse/concourse-ci/manifests/cpi.yml
  application-workloads/concourse/concourse-ci/manifests/custom-cpi-release.yml
  application-workloads/concourse/concourse-ci/manifests/custom-environment.yml
  application-workloads/concourse/concourse-ci/manifests/jumpbox-user.yml
  application-workloads/concourse/concourse-ci/manifests/keep-failed-or-unreachable-vms.yml
  application-workloads/concourse/concourse-ci/manifests/use-azure-dns.yml
  application-workloads/concourse/concourse-ci/manifests/use-managed-disks.yml
  application-workloads/concourse/concourse-ci/manifests/use-mirror-releases-for-bosh.yml
  application-workloads/concourse/concourse-ci/manifests/use-mirror-releases-for-concourse.yml
  application-workloads/concourse/concourse-ci/metadata.json
  application-workloads/concourse/concourse-ci/scripts/setup_env.sh
Labels: best practices violations

#10490 COPY: docker-swarm-cluster to application-workloads\swarm
  application-workloads/swarm/docker-swarm-cluster/README.md
  application-workloads/swarm/docker-swarm-cluster/azuredeploy.json
  application-workloads/swarm/docker-swarm-cluster/azuredeploy.parameters.json
  application-workloads/swarm/docker-swarm-cluster/img/HOWTO.txt
  application-workloads/swarm/docker-swarm-cluster/img/cluster-leader-election.dot
  application-workloads/swarm/docker-swarm-cluster/img/cluster-leader-election.png
  application-workloads/swarm/docker-swarm-cluster/img/cluster-management.dot
  application-workloads/swarm/docker-swarm-cluster/img/cluster-management.png
  application-workloads/swarm/docker-swarm-cluster/img/cluster-network.dot
  application-workloads/swarm/docker-swarm-cluster/img/cluster-network.png
  application-workloads/swarm/docker-swarm-cluster/img/cluster-node-discovery.dot
  application-workloads/swarm/docker-swarm-cluster/img/cluster-node-discovery.png
  application-workloads/swarm/docker-swarm-cluster/metadata.json
Labels: best practices violations

#10491 COPY: ethereum-studio-docker-standalone-ubuntu to application-workloads\ethereum
  application-workloads/ethereum/ethereum-studio-docker-standalone-ubuntu/README.md
  application-workloads/ethereum/ethereum-studio-docker-standalone-ubuntu/azuredeploy.json
  application-workloads/ethereum/ethereum-studio-docker-standalone-ubuntu/azuredeploy.parameters.json
  application-workloads/ethereum/ethereum-studio-docker-standalone-ubuntu/install.sh
  application-workloads/ethereum/ethereum-studio-docker-standalone-ubuntu/metadata.json
Labels: best practices violations

#10492 COPY: safekit-cluster-farm to application-workloads\safekit
  application-workloads/safekit/safekit-cluster-farm/README.md
  application-workloads/safekit/safekit-cluster-farm/azuredeploy.json
  application-workloads/safekit/safekit-cluster-farm/azuredeploy.parameters.json
  application-workloads/safekit/safekit-cluster-farm/azuredeploy.parameters.us.json
  application-workloads/safekit/safekit-cluster-farm/images/farmarch.png
  application-workloads/safekit/safekit-cluster-farm/metadata.json
  application-workloads/safekit/safekit-cluster-farm/nestedtemplates/cfgFarm.json
  application-workloads/safekit/safekit-cluster-farm/nestedtemplates/cluster.json
  application-workloads/safekit/safekit-cluster-farm/nestedtemplates/createvip.json
  application-workloads/safekit/safekit-cluster-farm/nestedtemplates/installCluster.json
  application-workloads/safekit/safekit-cluster-farm/nestedtemplates/installModule.json
  application-workloads/safekit/safekit-cluster-farm/nestedtemplates/safekitdepl.json
  application-workloads/safekit/safekit-cluster-farm/scripts/InstallSafeKit.ps1
  application-workloads/safekit/safekit-cluster-farm/scripts/InstallSafeKit.sh
  application-workloads/safekit/safekit-cluster-farm/scripts/UpdateSafeKit.sh
  application-workloads/safekit/safekit-cluster-farm/scripts/cfgFarm.ps1
  application-workloads/safekit/safekit-cluster-farm/scripts/configCluster.ps1
  application-workloads/safekit/safekit-cluster-farm/scripts/installAzureRM.ps1
  application-workloads/safekit/safekit-cluster-farm/scripts/installCluster.ps1
  application-workloads/safekit/safekit-cluster-farm/scripts/installCluster.sh
  application-workloads/safekit/safekit-cluster-farm/scripts/installModule.ps1
  application-workloads/safekit/safekit-cluster-farm/scripts/uploadcerts.ps1
Labels: best practices violations

#10493 COPY: sap-2-tier-marketplace-image to application-workloads\sap
  application-workloads/sap/sap-2-tier-marketplace-image/README.md
  application-workloads/sap/sap-2-tier-marketplace-image/azuredeploy.json
  application-workloads/sap/sap-2-tier-marketplace-image/azuredeploy.parameters.json
  application-workloads/sap/sap-2-tier-marketplace-image/metadata.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/configureSAPVM.ps1
  application-workloads/sap/sap-2-tier-marketplace-image/shared/configureSAPVM.sh
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_D13_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_D14_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_DS11_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_DS13_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_DS14_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_DS2_v2_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_GS5_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/db-server-Standard_GS2_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/db-server-Standard_GS3_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/db-server-Standard_GS4_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/db-server-Standard_GS5_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/disks.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/disks0.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/existingnsg.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/existingpip.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/existingvnet.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/existingvnetnsg.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-DB-HANA.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-DB-SQL.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-DB0.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-ERS-Linux.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-ERS-Windows.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-ERS0.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-SCS.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-SCS0.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/loadbalancer.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/newnsg.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/newpip.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/newvnet.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/newvnetnsg.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/nic-config.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/noop.ps1
  application-workloads/sap/sap-2-tier-marketplace-image/shared/noop.sh
  application-workloads/sap/sap-2-tier-marketplace-image/shared/os-disk-parts-md.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/os-disk-parts.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server-Standard_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server-md.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server2-noplan.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server2.json
Labels: best practices violations

#10494 COPY: shibboleth-singlevm-windows to application-workloads\shibboleth
  application-workloads/shibboleth/shibboleth-singlevm-windows/README.md
  application-workloads/shibboleth/shibboleth-singlevm-windows/azuredeploy.json
  application-workloads/shibboleth/shibboleth-singlevm-windows/azuredeploy.parameters.json
  application-workloads/shibboleth/shibboleth-singlevm-windows/install_shibboleth_idp.ps1
  application-workloads/shibboleth/shibboleth-singlevm-windows/metadata.json
Labels: best practices violations

#10677 COPY: 201-cdn-with-ruleseengine-cacheoverride to quickstarts\microsoft.cdn
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-cacheoverride/README.md
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-cacheoverride/azuredeploy.json
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-cacheoverride/azuredeploy.parameters.json
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-cacheoverride/metadata.json
Labels: best practices violations

#10678 COPY: 301-multi-vmss-linux-lb-zones to quickstarts\microsoft.compute
  quickstarts/microsoft.compute/multi-vmss-linux-lb-zones/README.md
  quickstarts/microsoft.compute/multi-vmss-linux-lb-zones/azuredeploy.json
  quickstarts/microsoft.compute/multi-vmss-linux-lb-zones/azuredeploy.parameters.json
  quickstarts/microsoft.compute/multi-vmss-linux-lb-zones/azuredeploy.parameters.us.json
  quickstarts/microsoft.compute/multi-vmss-linux-lb-zones/metadata.json
Labels: best practices violations

#10679 COPY: 301-multi-vmss-windows to quickstarts\microsoft.compute
  quickstarts/microsoft.compute/multi-vmss-windows/README.md
  quickstarts/microsoft.compute/multi-vmss-windows/azuredeploy.json
  quickstarts/microsoft.compute/multi-vmss-windows/azuredeploy.parameters.json
  quickstarts/microsoft.compute/multi-vmss-windows/metadata.json
  quickstarts/microsoft.compute/multi-vmss-windows/nestedtemplates/base.json
Labels: best practices violations

#10475 COPY: 201-cdn-with-storage-account to quickstarts\microsoft.cdn
  quickstarts/microsoft.cdn/cdn-with-storage-account/README.md
  quickstarts/microsoft.cdn/cdn-with-storage-account/azuredeploy.json
  quickstarts/microsoft.cdn/cdn-with-storage-account/azuredeploy.parameters.json
  quickstarts/microsoft.cdn/cdn-with-storage-account/metadata.json
Labels: best practices violations

#10719 FIX-TEMPLATE: 201-timeseriesinsights-environment-with-eventhub
  201-timeseriesinsights-environment-with-eventhub/metadata.json
Labels: ROOT, best practices violations

#10711 FIX-TEMPLATE: eset-vm-extension
  eset-vm-extension/azuredeploy.json
  eset-vm-extension/metadata.json
Labels: ROOT, best practices violations

#10710 FIX-TEMPLATE: mcafee-extension-windows-vm
  mcafee-extension-windows-vm/azuredeploy.json
  mcafee-extension-windows-vm/metadata.json
Labels: ROOT, best practices violations

#10709 FIX-TEMPLATE: symantec-extension-windows-vm
  symantec-extension-windows-vm/azuredeploy.json
  symantec-extension-windows-vm/metadata.json
Labels: ROOT, best practices violations

#10676 FIX-TEMPLATE: 101-hdinsight-linux-add-edge-node
  101-hdinsight-linux-add-edge-node/azuredeploy.json
  101-hdinsight-linux-add-edge-node/prereqs/.settings.json
  101-hdinsight-linux-add-edge-node/prereqs/prereq.azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#10674 FIX-TEMPLATE: 101-hdinsight-linux-with-edge-node
  101-hdinsight-linux-with-edge-node/azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#10423 FIX-TEMPLATE: barracuda-waf-iis
  barracuda-waf-iis/azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#10453 FIX-TEMPLATE: 101-aks-advanced-networking
  101-aks-advanced-networking/azuredeploy.json
  101-aks-advanced-networking/azuredeploy.parameters.json
Labels: ROOT

#10525 FIX-TEMPLATE: spark-2.0-on-suse
  spark-2.0-on-suse/azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#10539 FIX-BESTPRACTICES: front-door-custom-domain
  quickstarts/microsoft.network/front-door-custom-domain/azuredeploy.json
Labels: manual validation required

#10663 FIX-BESTPRACTICES: 101-Telegraf-InfluxDB-Grafana
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/azuredeploy.json
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/azuredeploy.parameters.json
Labels: UPPERCASE

#9020 FIX-TEMPLATE: 101-sig-image-version-create
  101-sig-image-version-create/README.md
  101-sig-image-version-create/azuredeploy.json
  101-sig-image-version-create/azuredeploy.parameters.json
  101-sig-image-version-create/metadata.json
  101-sig-image-version-create/prereqs/.settings.json
  101-sig-image-version-create/prereqs/prereq.azuredeploy.json
  101-sig-image-version-create/prereqs/prereq.azuredeploy.parameters.json
Labels: ROOT, best practices violations

#10557 FIX-TEMPLATE: 201-front-door-create-caching
  201-front-door-create-caching/azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#10556 FIX-TEMPLATE: 201-front-door-health-probes
  201-front-door-health-probes/azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#10554 FIX-TEMPLATE: 201-front-door-session-affinity
  201-front-door-session-affinity/azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#10549 FIX-TEMPLATE: intel-lustre-clients-on-centos
  intel-lustre-clients-on-centos/azuredeploy.json
  intel-lustre-clients-on-centos/azuredeploy.parameters.json
  intel-lustre-clients-on-centos/lustre_client.sh
  intel-lustre-clients-on-centos/prereqs/.settings.json
  intel-lustre-clients-on-centos/prereqs/prereq.azuredeploy.json
  intel-lustre-clients-on-centos/prereqs/prereq.azuredeploy.parameters.json
Labels: ROOT, best practices violations, readme violations

#10532 FIX-TEMPLATE: kafka-on-ubuntu
  kafka-on-ubuntu/azuredeploy.json
  kafka-on-ubuntu/jumpbox-resources-disabled.json
  kafka-on-ubuntu/jumpbox-resources-enabled.json
  kafka-on-ubuntu/kafka-cluster-install.sh
Labels: ROOT, best practices violations, readme violations

#10531 FIX-TEMPLATE: mahara-autoscale-cache
  mahara-autoscale-cache/azuredeploy.json
  mahara-autoscale-cache/scripts/setup_webserver.sh
Labels: ROOT, best practices violations, readme violations

#10529 FIX-TEMPLATE: pubnub-eventhub-bridge
  pubnub-eventhub-bridge/README.md
  pubnub-eventhub-bridge/azuredeploy.json
  pubnub-eventhub-bridge/azuredeploy.parameters.json
Labels: ROOT, best practices violations, readme violations

#10526 Added Bicep sample for managementgroup-deployments/mg-policy-different-targets
  managementgroup-deployments/mg-policy-different-targets/README.md
  managementgroup-deployments/mg-policy-different-targets/azuredeploy.json
  managementgroup-deployments/mg-policy-different-targets/azuredeploy.parameters.json
  managementgroup-deployments/mg-policy-different-targets/main.bicep
  managementgroup-deployments/mg-policy-different-targets/metadata.json
  managementgroup-deployments/mg-policy-different-targets/modules/empty.bicep
  managementgroup-deployments/mg-policy-different-targets/modules/location-lock-assignment.bicep
Labels: bicep, manual validation required

#10499 Update azuredeploy.json to parse uri content
  quickstarts/microsoft.compute/vm-virus-attack-prevention/azuredeploy.json
Labels: best practices violations

#9164 storage-iops-latency-throughput-demo
  storage-iops-latency-throughput-demo/azuredeploy.json
  storage-iops-latency-throughput-demo/dsc/vmDemo.ps1
  storage-iops-latency-throughput-demo/dsc/vmDemo.zip
  storage-iops-latency-throughput-demo/sample-managed-disks/README.md
  storage-iops-latency-throughput-demo/sample-managed-disks/managedDisksDemo.json
  storage-iops-latency-throughput-demo/sample-managed-disks/managedDisksDemo.parameters.json
Labels: ROOT, best practices violations, readme violations

#10757 Fix for azure vm yum update issue
  ibm-cloud-pak-for-data/README.md
  ibm-cloud-pak-for-data/azuredeploy.json
  ibm-cloud-pak-for-data/scripts/deployOpenShift.sh
  ibm-cloud-pak-for-data/scripts/openshiftCloudPakConfig.sh
  ibm-cloud-pak-for-data/scripts/setup-nfs.sh
Labels: ROOT, best practices violations, manual validation required

#10759 FIX-BESTPRACTICES: jboss-eap-clustered-multivm-rhel
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/azuredeploy.json
Labels: manual validation required

#10789 1-v-loaderbalancer-2-nics: minor grammar fix and try redeploying (regressed)
  quickstarts/microsoft.compute/1-vm-loadbalancer-2-nics/README.md
  quickstarts/microsoft.compute/1-vm-loadbalancer-2-nics/metadata.json
Labels: best practices violations

#10781 cosmos-web: Fix readme, rerun validation (BP and deployment regressed)
  quickstarts/microsoft.documentdb/cosmosdb-webapp/README.md
  quickstarts/microsoft.documentdb/cosmosdb-webapp/metadata.json
Labels: bicep

#10843 COPY: 101-hdinsight-linux-with-edge-node to quickstarts\microsoft.hdinsight
  quickstarts/microsoft.hdinsight/hdinsight-linux-with-edge-node/README.md
  quickstarts/microsoft.hdinsight/hdinsight-linux-with-edge-node/azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-linux-with-edge-node/azuredeploy.parameters.json
  quickstarts/microsoft.hdinsight/hdinsight-linux-with-edge-node/metadata.json
  quickstarts/microsoft.hdinsight/hdinsight-linux-with-edge-node/scripts/EmptyNodeSetup.sh
Labels: best practices violations

#10844 COPY: 201-front-door-create-caching to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-create-caching/README.md
  quickstarts/microsoft.network/front-door-create-caching/azuredeploy.json
  quickstarts/microsoft.network/front-door-create-caching/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-create-caching/metadata.json
Labels: best practices violations

#10845 COPY: 201-front-door-health-probes to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-health-probes/README.md
  quickstarts/microsoft.network/front-door-health-probes/azuredeploy.json
  quickstarts/microsoft.network/front-door-health-probes/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-health-probes/metadata.json
Labels: best practices violations

#10846 COPY: 201-timeseriesinsights-environment-with-eventhub to quickstarts\microsoft.timeseriesinsights
  quickstarts/microsoft.timeseriesinsights/timeseriesinsights-environment-with-eventhub/README.md
  quickstarts/microsoft.timeseriesinsights/timeseriesinsights-environment-with-eventhub/azuredeploy.json
  quickstarts/microsoft.timeseriesinsights/timeseriesinsights-environment-with-eventhub/azuredeploy.parameters.json
  quickstarts/microsoft.timeseriesinsights/timeseriesinsights-environment-with-eventhub/metadata.json
Labels: best practices violations

#10848 COPY: eset-vm-extension to demos
  demos/eset-vm-extension/README.md
  demos/eset-vm-extension/azuredeploy.json
  demos/eset-vm-extension/azuredeploy.parameters.json
  demos/eset-vm-extension/eset-create-deployment-cli.sh
  demos/eset-vm-extension/eset-create-deployment.ps1
  demos/eset-vm-extension/metadata.json
Labels: best practices violations

#10849 COPY: intel-lustre-clients-on-centos to application-workloads\intel-lustre
  application-workloads/intel-lustre/intel-lustre-clients-on-centos/README.md
  application-workloads/intel-lustre/intel-lustre-clients-on-centos/azuredeploy.json
  application-workloads/intel-lustre/intel-lustre-clients-on-centos/azuredeploy.parameters.json
  application-workloads/intel-lustre/intel-lustre-clients-on-centos/lustre_client.sh
  application-workloads/intel-lustre/intel-lustre-clients-on-centos/metadata.json
  application-workloads/intel-lustre/intel-lustre-clients-on-centos/prereqs/.settings.json
  application-workloads/intel-lustre/intel-lustre-clients-on-centos/prereqs/prereq.azuredeploy.json
  application-workloads/intel-lustre/intel-lustre-clients-on-centos/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10850 COPY: kafka-on-ubuntu to application-workloads\kafka
  application-workloads/kafka/kafka-on-ubuntu/README.md
  application-workloads/kafka/kafka-on-ubuntu/azuredeploy.json
  application-workloads/kafka/kafka-on-ubuntu/azuredeploy.parameters.json
  application-workloads/kafka/kafka-on-ubuntu/jumpbox-resources-disabled.json
  application-workloads/kafka/kafka-on-ubuntu/jumpbox-resources-enabled.json
  application-workloads/kafka/kafka-on-ubuntu/kafka-cluster-install.sh
  application-workloads/kafka/kafka-on-ubuntu/metadata.json
  application-workloads/kafka/kafka-on-ubuntu/shared-resources.json
Labels: best practices violations

#10852 COPY: mcafee-extension-windows-vm to demos
  demos/mcafee-extension-windows-vm/README.md
  demos/mcafee-extension-windows-vm/azuredeploy.json
  demos/mcafee-extension-windows-vm/azuredeploy.parameters.json
  demos/mcafee-extension-windows-vm/metadata.json
Labels: best practices violations

#10853 COPY: pubnub-eventhub-bridge to application-workloads\pubnub
  application-workloads/pubnub/pubnub-eventhub-bridge/.deployment
  application-workloads/pubnub/pubnub-eventhub-bridge/.gitignore
  application-workloads/pubnub/pubnub-eventhub-bridge/App_Data/jobs/continuous/pnwebjob/PNSubscribeToEH1EH2ToPNPublish.js
  application-workloads/pubnub/pubnub-eventhub-bridge/App_Data/jobs/continuous/pnwebjob/package.json
  application-workloads/pubnub/pubnub-eventhub-bridge/App_Data/jobs/continuous/pnwebjob/settings.job
  application-workloads/pubnub/pubnub-eventhub-bridge/README.md
  application-workloads/pubnub/pubnub-eventhub-bridge/azuredeploy.json
  application-workloads/pubnub/pubnub-eventhub-bridge/azuredeploy.parameters.json
  application-workloads/pubnub/pubnub-eventhub-bridge/cdd.bat
  application-workloads/pubnub/pubnub-eventhub-bridge/metadata.json
  application-workloads/pubnub/pubnub-eventhub-bridge/tools/package.json
  application-workloads/pubnub/pubnub-eventhub-bridge/tools/provisioningListener.js
Labels: best practices violations

#10854 COPY: spark-2.0-on-suse to application-workloads\spark
  application-workloads/spark/spark-2.0-on-suse/spark-2.0-on-suse/README.md
  application-workloads/spark/spark-2.0-on-suse/spark-2.0-on-suse/azuredeploy.json
  application-workloads/spark/spark-2.0-on-suse/spark-2.0-on-suse/azuredeploy.parameters.json
  application-workloads/spark/spark-2.0-on-suse/spark-2.0-on-suse/metadata.json
  application-workloads/spark/spark-2.0-on-suse/spark-2.0-on-suse/scripts/install_spark_environment.sh
Labels: best practices violations

#10855 COPY: storage-iops-latency-throughput-demo to demos
  demos/storage-iops-latency-throughput-demo/README.md
  demos/storage-iops-latency-throughput-demo/azuredeploy.json
  demos/storage-iops-latency-throughput-demo/azuredeploy.parameters.json
  demos/storage-iops-latency-throughput-demo/dsc/vmDemo.ps1
  demos/storage-iops-latency-throughput-demo/dsc/vmDemo.zip
  demos/storage-iops-latency-throughput-demo/files/iometerTests.zip
  demos/storage-iops-latency-throughput-demo/metadata.json
Labels: best practices violations

#10856 COPY: symantec-extension-windows-vm to demos
  demos/symantec-extension-windows-vm/README.md
  demos/symantec-extension-windows-vm/azuredeploy.json
  demos/symantec-extension-windows-vm/azuredeploy.parameters.json
  demos/symantec-extension-windows-vm/metadata.json
Labels: best practices violations

#10392 FIX-TEMPLATE: create-hpc-cluster
  create-hpc-cluster/azuredeploy.json
  create-hpc-cluster/headnode-rdma-disabled.json
  create-hpc-cluster/headnode-rdma-enabled.json
  create-hpc-cluster/linuxnode.json
  create-hpc-cluster/mainTemplate.json
  create-hpc-cluster/metadata.json
  create-hpc-cluster/windowsnode-rdma-disabled.json
  create-hpc-cluster/windowsnode-rdma-enabled.json
Labels: ROOT, best practices violations

#10747 Picking update merge changes, minimal update
  101-hdinsight-linux-add-edge-node/README.md
  101-hdinsight-linux-add-edge-node/azuredeploy.json
  101-hdinsight-linux-add-edge-node/metadata.json
  101-hdinsight-linux-add-edge-node/prereqs/prereq.azuredeploy.json
  101-hdinsight-linux-add-edge-node/prereqs/prereq.azuredeploy.parameters.json
Labels: ROOT

#10796 Custom ambari db3
  quickstarts/microsoft.hdinsight/hdinsight-custom-ambari-db/azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-custom-ambari-db/metadata.json
Labels: best practices violations

#10801 FIX-TEMPLATE: 201-api-management-create-with-reference-keyvault
  201-api-management-create-with-reference-keyvault/azuredeploy.json
  201-api-management-create-with-reference-keyvault/azuredeploy.parameters.json
Labels: ROOT, best practices violations, readme violations

#10816 Sync bicep samples: 101-container-registry
  quickstarts/microsoft.containerregistry/container-registry/README.md
  quickstarts/microsoft.containerregistry/container-registry/azuredeploy.json
  quickstarts/microsoft.containerregistry/container-registry/main.bicep
Labels: bicep

#10818 FIX-TEMPLATE: 201-application-gateway-2vms-iis-ssl
  201-application-gateway-2vms-iis-ssl/DSC/iisInstall.ps1.zip
  201-application-gateway-2vms-iis-ssl/azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#10819 FIX-TEMPLATE: 201-application-gateway-multihosting
  201-application-gateway-multihosting/azuredeploy.json
  201-application-gateway-multihosting/azuredeploy.parameters.json
Labels: ROOT, best practices violations, readme violations

#10820 FIX-TEMPLATE: 201-application-gateway-sslpolicy-custom
  201-application-gateway-sslpolicy-custom/azuredeploy.json
  201-application-gateway-sslpolicy-custom/azuredeploy.parameters.json
Labels: ROOT, best practices violations, readme violations

#10821 FIX-TEMPLATE: 201-application-gateway-sslpolicy-predefined
  201-application-gateway-sslpolicy-predefined/azuredeploy.json
  201-application-gateway-sslpolicy-predefined/azuredeploy.parameters.json
Labels: ROOT, best practices violations, readme violations

#10822 FIX-TEMPLATE: 201-asev2-ilb-with-web-app
  201-asev2-ilb-with-web-app/azuredeploy.json
  201-asev2-ilb-with-web-app/azuredeploy.parameters.json
  201-asev2-ilb-with-web-app/prereqs/prereq.azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#10895 COPY: diagnostics-eventhub-elk to application-workloads\elk
  application-workloads/elk/diagnostics-eventhub-elk/README.md
  application-workloads/elk/diagnostics-eventhub-elk/azuredeploy.json
  application-workloads/elk/diagnostics-eventhub-elk/azuredeploy.parameters.json
  application-workloads/elk/diagnostics-eventhub-elk/metadata.json
  application-workloads/elk/diagnostics-eventhub-elk/scripts/logstash-eventhub-install-ubuntu.sh
Labels: best practices violations

#10889 COPY: 201-front-door-session-affinity to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-session-affinity/README.md
  quickstarts/microsoft.network/front-door-session-affinity/azuredeploy.json
  quickstarts/microsoft.network/front-door-session-affinity/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-session-affinity/metadata.json
Labels: best practices violations

#10888 COPY: create-hpc-cluster to demos
  demos/create-hpc-cluster/ConfigComputeNode.ps1.zip
  demos/create-hpc-cluster/CreateADPDC.ps1.zip
  demos/create-hpc-cluster/HPCHNPrepare.ps1
  demos/create-hpc-cluster/PrepareHN.ps1
  demos/create-hpc-cluster/README.md
  demos/create-hpc-cluster/azuredeploy.json
  demos/create-hpc-cluster/azuredeploy.parameters.json
  demos/create-hpc-cluster/headnode-rdma-disabled.json
  demos/create-hpc-cluster/headnode-rdma-enabled.json
  demos/create-hpc-cluster/linuxnode.json
  demos/create-hpc-cluster/mainTemplate.json
  demos/create-hpc-cluster/metadata.json
  demos/create-hpc-cluster/publicip-existing.json
  demos/create-hpc-cluster/publicip-new.json
  demos/create-hpc-cluster/vnet-with-dns-server.json
  demos/create-hpc-cluster/windowsnode-rdma-disabled.json
  demos/create-hpc-cluster/windowsnode-rdma-enabled.json
Labels: best practices violations

#10886 COPY: 201-application-gateway-sslpolicy-predefined to quickstarts\microsoft.network
  quickstarts/microsoft.network/application-gateway-sslpolicy-predefined/README.md
  quickstarts/microsoft.network/application-gateway-sslpolicy-predefined/azuredeploy.json
  quickstarts/microsoft.network/application-gateway-sslpolicy-predefined/azuredeploy.parameters.json
  quickstarts/microsoft.network/application-gateway-sslpolicy-predefined/metadata.json
Labels: best practices violations

#10884 COPY: 201-application-gateway-multihosting to quickstarts\microsoft.network
  quickstarts/microsoft.network/application-gateway-multihosting/README.md
  quickstarts/microsoft.network/application-gateway-multihosting/azuredeploy.json
  quickstarts/microsoft.network/application-gateway-multihosting/azuredeploy.parameters.json
  quickstarts/microsoft.network/application-gateway-multihosting/metadata.json
Labels: best practices violations

#10883 COPY: 201-application-gateway-2vms-iis-ssl to quickstarts\microsoft.network
  quickstarts/microsoft.network/application-gateway-2vms-iis-ssl/DSC/iisInstall.ps1.zip
  quickstarts/microsoft.network/application-gateway-2vms-iis-ssl/README.md
  quickstarts/microsoft.network/application-gateway-2vms-iis-ssl/artifacts/vm1.default.htm
  quickstarts/microsoft.network/application-gateway-2vms-iis-ssl/artifacts/vm2.default.htm
  quickstarts/microsoft.network/application-gateway-2vms-iis-ssl/artifacts/web.config
  quickstarts/microsoft.network/application-gateway-2vms-iis-ssl/azuredeploy.json
  quickstarts/microsoft.network/application-gateway-2vms-iis-ssl/azuredeploy.parameters.json
  quickstarts/microsoft.network/application-gateway-2vms-iis-ssl/metadata.json
Labels: best practices violations

#10882 COPY: 201-api-management-create-with-reference-keyvault to quickstarts\microsoft.apimanagement
  quickstarts/microsoft.apimanagement/api-management-create-with-reference-keyvault/README.md
  quickstarts/microsoft.apimanagement/api-management-create-with-reference-keyvault/azuredeploy.json
  quickstarts/microsoft.apimanagement/api-management-create-with-reference-keyvault/azuredeploy.parameters.json
  quickstarts/microsoft.apimanagement/api-management-create-with-reference-keyvault/metadata.json
Labels: best practices violations

#10555 FIX-TEMPLATE: 201-front-door-priority-lb
  201-front-door-priority-lb/azuredeploy.json
Labels: ROOT, best practices violations, readme violations

#8801 Update to ev3 VMs, and add deploy to Az Gov
  101-hdinsight-linux-with-edge-node/README.md
  101-hdinsight-linux-with-edge-node/azuredeploy.json
  101-hdinsight-linux-with-edge-node/azuredeploy.parameters.json
  101-hdinsight-linux-with-edge-node/metadata.json
Labels: ROOT

#10144 FIX-TEMPLATE: 101-vm-customdata
  101-vm-customdata/azuredeploy.json
  101-vm-customdata/azuredeploy.parameters.json
Labels: best practices violations, readme violations

#10887 COPY: 201-asev2-ilb-with-web-app to quickstarts\microsoft.web
  quickstarts/microsoft.web/asev2-ilb-with-web-app/README.md
  quickstarts/microsoft.web/asev2-ilb-with-web-app/azuredeploy.json
  quickstarts/microsoft.web/asev2-ilb-with-web-app/azuredeploy.parameters.json
  quickstarts/microsoft.web/asev2-ilb-with-web-app/metadata.json
  quickstarts/microsoft.web/asev2-ilb-with-web-app/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.web/asev2-ilb-with-web-app/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10902 COPY: 201-front-door-standard-premium-storage-static-website to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/README.md
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/images/diagram.png
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/main.bicep
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/metadata.json
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/modules/front-door.bicep
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/modules/storage-static-website.bicep
Labels: best practices violations, bicep

#10904 COPY: 101-hdinsight-linux-add-edge-node to quickstarts\microsoft.hdinsight
  quickstarts/microsoft.hdinsight/hdinsight-linux-add-edge-node/README.md
  quickstarts/microsoft.hdinsight/hdinsight-linux-add-edge-node/azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-linux-add-edge-node/azuredeploy.parameters.json
  quickstarts/microsoft.hdinsight/hdinsight-linux-add-edge-node/metadata.json
  quickstarts/microsoft.hdinsight/hdinsight-linux-add-edge-node/prereqs/.settings.json
  quickstarts/microsoft.hdinsight/hdinsight-linux-add-edge-node/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-linux-add-edge-node/prereqs/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.hdinsight/hdinsight-linux-add-edge-node/scripts/EmptyNodeSetup.sh
Labels: best practices violations

#10634 FIX-TEMPLATE: 201-web-app-blob-connection
  201-web-app-blob-connection/azuredeploy.json
  201-web-app-blob-connection/prereqs/.settings.json
Labels: ROOT, best practices violations, readme violations

#10600 COPY: haproxy-redundant-floatingip-ubuntu to demos
  demos/haproxy-redundant-floatingip-ubuntu/README.md
  demos/haproxy-redundant-floatingip-ubuntu/apache-setup.sh
  demos/haproxy-redundant-floatingip-ubuntu/azuredeploy.json
  demos/haproxy-redundant-floatingip-ubuntu/azuredeploy.parameters.json
  demos/haproxy-redundant-floatingip-ubuntu/haproxyvm-configure.sh
  demos/haproxy-redundant-floatingip-ubuntu/keepalived-action.sh
  demos/haproxy-redundant-floatingip-ubuntu/keepalived-check-appsvc.sh
  demos/haproxy-redundant-floatingip-ubuntu/metadata.json
Labels: best practices violations

#10935 COPY-NOT-FIXED: jboss-eap-standalone-rhel7 to application-workloads\jboss
  application-workloads/jboss/jboss-eap-standalone-rhel7/README.md
  application-workloads/jboss/jboss-eap-standalone-rhel7/azuredeploy.json
  application-workloads/jboss/jboss-eap-standalone-rhel7/azuredeploy.parameters.json
  application-workloads/jboss/jboss-eap-standalone-rhel7/metadata.json
  application-workloads/jboss/jboss-eap-standalone-rhel7/scripts/eap-setup-redhat.sh
Labels: best practices violations

#10936 COPY-NOT-FIXED: jenkins-cicd-container to application-workloads\jenkins
  application-workloads/jenkins/jenkins-cicd-container/.gitignore
  application-workloads/jenkins/jenkins-cicd-container/Dockerfile
  application-workloads/jenkins/jenkins-cicd-container/README.md
  application-workloads/jenkins/jenkins-cicd-container/azuredeploy.json
  application-workloads/jenkins/jenkins-cicd-container/azuredeploy.parameters.json
  application-workloads/jenkins/jenkins-cicd-container/images/architecture.png
  application-workloads/jenkins/jenkins-cicd-container/images/azure-deployment-output.png
  application-workloads/jenkins/jenkins-cicd-container/images/azure-resource-group-deployments.png
  application-workloads/jenkins/jenkins-cicd-container/images/grafana-01.png
  application-workloads/jenkins/jenkins-cicd-container/images/grafana-02.png
  application-workloads/jenkins/jenkins-cicd-container/images/grafana-03.png
  application-workloads/jenkins/jenkins-cicd-container/images/jenkins-pipline-job.png
  application-workloads/jenkins/jenkins-cicd-container/kubernetes/hello-world-deployment.yaml
  application-workloads/jenkins/jenkins-cicd-container/kubernetes/hello-world-service.yaml
  application-workloads/jenkins/jenkins-cicd-container/metadata.json
  application-workloads/jenkins/jenkins-cicd-container/nested/grafana.json
  application-workloads/jenkins/jenkins-cicd-container/nested/jenkins.json
  application-workloads/jenkins/jenkins-cicd-container/scripts/grafana/configure-grafana.sh
  application-workloads/jenkins/jenkins-cicd-container/scripts/grafana/dashboard-aks-target.json
  application-workloads/jenkins/jenkins-cicd-container/scripts/grafana/dashboard-aks.json
  application-workloads/jenkins/jenkins-cicd-container/scripts/grafana/dashboard-db.json
  application-workloads/jenkins/jenkins-cicd-container/scripts/grafana/dashboard.json
  application-workloads/jenkins/jenkins-cicd-container/scripts/grafana/install-grafana.sh
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/add-docker-build-job.sh
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/basic-docker-build-job.xml
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/basic-docker-build.groovy
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/basic-user-pwd-credentials.xml
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/install_jenkins.sh
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-acr-aks.sh
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-on-azure/azure.svg
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-on-azure/copy.png
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-on-azure/headshot.png
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-on-azure/index.html
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-on-azure/install-web-page.sh
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-on-azure/site.css
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-on-azure/site.js
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-on-azure/title.png
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/jenkins-verified-ver
  application-workloads/jenkins/jenkins-cicd-container/scripts/jenkins/run-cli-command.sh
  application-workloads/jenkins/jenkins-cicd-container/server.js
Labels: best practices violations

#10938 COPY-NOT-FIXED: jenkins-cicd-vmss to application-workloads\jenkins
  application-workloads/jenkins/jenkins-cicd-vmss/HelloWorld/WebContent/WEB-INF/web.xml
  application-workloads/jenkins/jenkins-cicd-vmss/HelloWorld/WebContent/index.jsp
  application-workloads/jenkins/jenkins-cicd-vmss/README.md
  application-workloads/jenkins/jenkins-cicd-vmss/azuredeploy.json
  application-workloads/jenkins/jenkins-cicd-vmss/azuredeploy.parameters.json
  application-workloads/jenkins/jenkins-cicd-vmss/images/arm-output.png
  application-workloads/jenkins/jenkins-cicd-vmss/images/jenkins-anonymous.png
  application-workloads/jenkins/jenkins-cicd-vmss/images/jenkins-build-output.png
  application-workloads/jenkins/jenkins-cicd-vmss/images/jenkins-build-overview.png
  application-workloads/jenkins/jenkins-cicd-vmss/images/jenkins-login-ssh.png
  application-workloads/jenkins/jenkins-cicd-vmss/images/jenkins-login.png
  application-workloads/jenkins/jenkins-cicd-vmss/images/jenkins-publicip.png
  application-workloads/jenkins/jenkins-cicd-vmss/images/vmss-publicip.png
  application-workloads/jenkins/jenkins-cicd-vmss/images/vmss-resources.png
  application-workloads/jenkins/jenkins-cicd-vmss/images/vmss-webapp.png
  application-workloads/jenkins/jenkins-cicd-vmss/metadata.json
  application-workloads/jenkins/jenkins-cicd-vmss/nested/jenkins.json
  application-workloads/jenkins/jenkins-cicd-vmss/scripts/jenkins/credentials-basic.xml
  application-workloads/jenkins/jenkins-cicd-vmss/scripts/jenkins/jobs-build-vm.xml
  application-workloads/jenkins/jenkins-cicd-vmss/scripts/jenkins/setup.sh
  application-workloads/jenkins/jenkins-cicd-vmss/scripts/packer/script.sh
  application-workloads/jenkins/jenkins-cicd-vmss/scripts/packer/ubuntu.json
  application-workloads/jenkins/jenkins-cicd-vmss/scripts/terraform/output.tf
  application-workloads/jenkins/jenkins-cicd-vmss/scripts/terraform/variables.tf
  application-workloads/jenkins/jenkins-cicd-vmss/scripts/terraform/vmss.tf
Labels: best practices violations

#10955 COPY-NOT-FIXED: spark-and-cassandra-on-centos to application-workloads\spark
  application-workloads/spark/spark-and-cassandra-on-centos/CustomScripts/scriptCassandraProvisioner.sh
  application-workloads/spark/spark-and-cassandra-on-centos/CustomScripts/scriptSparkProvisioner.sh
  application-workloads/spark/spark-and-cassandra-on-centos/README.md
  application-workloads/spark/spark-and-cassandra-on-centos/azuredeploy.json
  application-workloads/spark/spark-and-cassandra-on-centos/azuredeploy.parameters.json
  application-workloads/spark/spark-and-cassandra-on-centos/metadata.json
Labels: best practices violations

#10957 COPY-NOT-FIXED: intel-lustre-client-server to application-workloads\intel-lustre
  application-workloads/intel-lustre/intel-lustre-client-server/README.md
  application-workloads/intel-lustre/intel-lustre-client-server/azuredeploy.json
  application-workloads/intel-lustre/intel-lustre-client-server/azuredeploy.parameters.json
  application-workloads/intel-lustre/intel-lustre-client-server/metadata.json
  application-workloads/intel-lustre/intel-lustre-client-server/monitoring.json
  application-workloads/intel-lustre/intel-lustre-client-server/prerequisite/deploy.bat
  application-workloads/intel-lustre/intel-lustre-client-server/prerequisite/parameters.txt
  application-workloads/intel-lustre/intel-lustre-client-server/scripts/lustre.sh
  application-workloads/intel-lustre/intel-lustre-client-server/scripts/lustre_client.sh
  application-workloads/intel-lustre/intel-lustre-client-server/scripts/monitoring.sh
  application-workloads/intel-lustre/intel-lustre-client-server/vnet-existing.json
  application-workloads/intel-lustre/intel-lustre-client-server/vnet-new.json
Labels: best practices violations

#10960 COPY-NOT-FIXED: informatica-adf-hdinsight-powerbi to application-workloads\informatica
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/README.md
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/azuredeploy.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/azuredeploy.parameters.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/images/ic1.png
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/images/ic2.png
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/images/informatica-cloud.png
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/images/reference-arch.png
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/metadata.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/azuredatafactory.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/contcreate-automation.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/createtableautomationjob.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/info-csa-extension.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/info-nsg.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/info-signup-automation.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/network-interface.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/public-ip.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/sqldatawarehouse.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/storage.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/virtual-machine-with-plan.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/vnet-subnet.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/nested/workflow-automation.json
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/runbooks/info-container-crt.ps1
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/runbooks/info-restapi-signup.ps1
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/runbooks/info-restapi-workflow.ps1
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/scripts/ICExtentionScript.ps1
  application-workloads/informatica/informatica-adf-hdinsight-powerbi/scripts/createTable.ps1
Labels: best practices violations

#10962 COPY-NOT-FIXED: 101-data-factory-blob-to-sql-copy-stored-proc to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/data-factory-blob-to-sql-copy-stored-proc/README.md
  quickstarts/microsoft.datafactory/data-factory-blob-to-sql-copy-stored-proc/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-blob-to-sql-copy-stored-proc/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-blob-to-sql-copy-stored-proc/metadata.json
Labels: best practices violations

#10963 COPY-NOT-FIXED: 101-data-factory-hive-transformation to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/data-factory-hive-transformation/README.md
  quickstarts/microsoft.datafactory/data-factory-hive-transformation/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-hive-transformation/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-hive-transformation/metadata.json
Labels: best practices violations

#10965 COPY-NOT-FIXED: 101-data-factory-chained-copy-activities to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/data-factory-chained-copy-activities/README.md
  quickstarts/microsoft.datafactory/data-factory-chained-copy-activities/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-chained-copy-activities/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-chained-copy-activities/images/pipeline.png
  quickstarts/microsoft.datafactory/data-factory-chained-copy-activities/metadata.json
Labels: best practices violations

#10967 COPY-NOT-FIXED: docker-kibana-elasticsearch to application-workloads\elk
  application-workloads/elk/docker-kibana-elasticsearch/README.md
  application-workloads/elk/docker-kibana-elasticsearch/azuredeploy.json
  application-workloads/elk/docker-kibana-elasticsearch/azuredeploy.parameters.json
  application-workloads/elk/docker-kibana-elasticsearch/metadata.json
Labels: best practices violations

#10969 COPY-NOT-FIXED: 101-data-factory-v2-onprem-sql-to-blob-copy to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/README.md
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/metadata.json
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10970 COPY-NOT-FIXED: diagnostics-with-elk to application-workloads\elk
  application-workloads/elk/diagnostics-with-elk/README.md
  application-workloads/elk/diagnostics-with-elk/azuredeploy.json
  application-workloads/elk/diagnostics-with-elk/azuredeploy.parameters.json
  application-workloads/elk/diagnostics-with-elk/metadata.json
  application-workloads/elk/diagnostics-with-elk/scripts/elk-simple-install-ubuntu.sh
  application-workloads/elk/diagnostics-with-elk/scripts/logstash-install-ubuntu.sh
Labels: best practices violations

#10971 COPY-NOT-FIXED: 101-data-factory-v2-transform-using-spark to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/data-factory-v2-transform-using-spark/README.md
  quickstarts/microsoft.datafactory/data-factory-v2-transform-using-spark/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-transform-using-spark/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-transform-using-spark/metadata.json
  quickstarts/microsoft.datafactory/data-factory-v2-transform-using-spark/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-transform-using-spark/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10929 COPY: openchain-blockchain-coinprism to application-workloads\blockchain
  application-workloads/blockchain/openchain-blockchain-coinprism/README.md
  application-workloads/blockchain/openchain-blockchain-coinprism/azuredeploy.json
  application-workloads/blockchain/openchain-blockchain-coinprism/azuredeploy.parameters.json
  application-workloads/blockchain/openchain-blockchain-coinprism/install_openchain.sh
  application-workloads/blockchain/openchain-blockchain-coinprism/metadata.json
Labels: best practices violations

#10930 COPY: 201-front-door-priority-lb to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-priority-lb/README.md
  quickstarts/microsoft.network/front-door-priority-lb/azuredeploy.json
  quickstarts/microsoft.network/front-door-priority-lb/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-priority-lb/metadata.json
Labels: best practices violations

#10931 COPY-NOT-FIXED: 101-aks-advanced-networking-aad to quickstarts\Microsoft.ContainerInstance
  quickstarts/microsoft.containerinstance/aks-advanced-networking-aad/README.md
  quickstarts/microsoft.containerinstance/aks-advanced-networking-aad/azuredeploy.json
  quickstarts/microsoft.containerinstance/aks-advanced-networking-aad/azuredeploy.parameters.json
  quickstarts/microsoft.containerinstance/aks-advanced-networking-aad/metadata.json
  quickstarts/microsoft.containerinstance/aks-advanced-networking-aad/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.containerinstance/aks-advanced-networking-aad/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10932 COPY-NOT-FIXED: 101-data-factory-blob-to-sql-copy to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/data-factory-blob-to-sql-copy/README.md
  quickstarts/microsoft.datafactory/data-factory-blob-to-sql-copy/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-blob-to-sql-copy/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-blob-to-sql-copy/images/adfDiagram.PNG
  quickstarts/microsoft.datafactory/data-factory-blob-to-sql-copy/metadata.json
Labels: best practices violations

#10953 COPY-NOT-FIXED: sas9.4-viya to application-workloads\sas
  application-workloads/sas/sas9.4-viya/sas9.4-viya/README.md
  application-workloads/sas/sas9.4-viya/sas9.4-viya/azuredeploy.json
  application-workloads/sas/sas9.4-viya/sas9.4-viya/azuredeploy.parameters.json
  application-workloads/sas/sas9.4-viya/sas9.4-viya/client_install.zip
  application-workloads/sas/sas9.4-viya/sas9.4-viya/images/configuration.jpg
  application-workloads/sas/sas9.4-viya/sas9.4-viya/images/forward_ports.jpg
  application-workloads/sas/sas9.4-viya/sas9.4-viya/images/pubip_port.jpg
  application-workloads/sas/sas9.4-viya/sas9.4-viya/images/rdp_connection.jpg
  application-workloads/sas/sas9.4-viya/sas9.4-viya/images/sas94-viya-architecture-diagram.svg
  application-workloads/sas/sas9.4-viya/sas9.4-viya/images/source_destination.jpg
  application-workloads/sas/sas9.4-viya/sas9.4-viya/images/vmuser_ppk.jpg
  application-workloads/sas/sas9.4-viya/sas9.4-viya/metadata.json
  application-workloads/sas/sas9.4-viya/sas9.4-viya/nestedtemplates/access_policy.json
  application-workloads/sas/sas9.4-viya/sas9.4-viya/nestedtemplates/role_assignments.json
  application-workloads/sas/sas9.4-viya/sas9.4-viya/nestedtemplates/vm_linux_extension.json
  application-workloads/sas/sas9.4-viya/sas9.4-viya/nestedtemplates/vm_windows_extension.json
  application-workloads/sas/sas9.4-viya/sas9.4-viya/properties/response-properties.tar.gz
  application-workloads/sas/sas9.4-viya/sas9.4-viya/properties/viya-ark.tar.gz
  application-workloads/sas/sas9.4-viya/sas9.4-viya/sas_client_install.ps1
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/ansible_setup.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/ansible_ssl.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/compute_config.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/compute_install.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/meta_config.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/meta_install.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/mid_config.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/mid_install.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/sasapp_prereq.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/viya_ark.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/viya_prereq.sh
  application-workloads/sas/sas9.4-viya/sas9.4-viya/scripts/viyainstall.sh
Labels: best practices violations

#10966 COPY-NOT-FIXED: 101-data-factory-v2-blob-to-sql-copy to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-sql-copy/README.md
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-sql-copy/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-sql-copy/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-sql-copy/metadata.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-sql-copy/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-sql-copy/prereqs/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-sql-copy/scripts/runmonitor.ps1
Labels: best practices violations

#10975 COPY-NOT-FIXED: 101-iothub-auto-route-messages to quickstarts\microsoft.devices
  quickstarts/microsoft.devices/iothub-auto-route-messages/README.md
  quickstarts/microsoft.devices/iothub-auto-route-messages/azuredeploy.json
  quickstarts/microsoft.devices/iothub-auto-route-messages/azuredeploy.parameters.json
  quickstarts/microsoft.devices/iothub-auto-route-messages/metadata.json
Labels: best practices violations

#10977 COPY-NOT-FIXED: datastax to application-workloads\datastax
  application-workloads/datastax/datastax/README.md
  application-workloads/datastax/datastax/azuredeploy.json
  application-workloads/datastax/datastax/azuredeploy.parameters.json
  application-workloads/datastax/datastax/metadata.json
  application-workloads/datastax/datastax/nested/nodes.json
  application-workloads/datastax/datastax/nested/opscenter.json
  application-workloads/datastax/datastax/scripts/node.sh
  application-workloads/datastax/datastax/scripts/opscenter.sh
Labels: best practices violations

#10981 COPY-NOT-FIXED: custom-private-dns to demos
  demos/custom-private-dns/README.md
  demos/custom-private-dns/azuredeploy.json
  demos/custom-private-dns/azuredeploy.parameters.json
  demos/custom-private-dns/metadata.json
  demos/custom-private-dns/nested/genericvm.json
  demos/custom-private-dns/nested/linux-client/ddns-dhcphook
  demos/custom-private-dns/nested/linux-client/setuplinuxclient.json
  demos/custom-private-dns/nested/linux-client/setuplinuxclient.sh
  demos/custom-private-dns/nested/server/setupserver.json
  demos/custom-private-dns/nested/server/setupserver.ps1
  demos/custom-private-dns/nested/windows-client/setupwinclient.json
  demos/custom-private-dns/nested/windows-client/setupwinclient.ps1
  demos/custom-private-dns/test-it.ps1
Labels: best practices violations

#10982 COPY-NOT-FIXED: 101-machine-learning-compute-attach-adla to quickstarts\microsoft.machinelearningservices
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-adla/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-adla/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-adla/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-adla/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-adla/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-adla/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-adla/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10983 COPY-NOT-FIXED: 101-mutiple-vms-with-data-management-gateway to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/mutiple-vms-with-data-management-gateway/README.md
  quickstarts/microsoft.datafactory/mutiple-vms-with-data-management-gateway/azuredeploy.json
  quickstarts/microsoft.datafactory/mutiple-vms-with-data-management-gateway/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/mutiple-vms-with-data-management-gateway/images/online.png
  quickstarts/microsoft.datafactory/mutiple-vms-with-data-management-gateway/metadata.json
  quickstarts/microsoft.datafactory/mutiple-vms-with-data-management-gateway/nested/VMtemplate.json
  quickstarts/microsoft.datafactory/mutiple-vms-with-data-management-gateway/scripts/gatewayInstall.ps1
Labels: best practices violations

#10986 COPY-NOT-FIXED: 101-recovery-services-vm-workload-backup to quickstarts\microsoft.recoveryservices
  quickstarts/microsoft.recoveryservices/recovery-services-vm-workload-backup/README.md
  quickstarts/microsoft.recoveryservices/recovery-services-vm-workload-backup/azuredeploy.json
  quickstarts/microsoft.recoveryservices/recovery-services-vm-workload-backup/azuredeploy.parameters.json
  quickstarts/microsoft.recoveryservices/recovery-services-vm-workload-backup/images/WorkloadBackup.png
  quickstarts/microsoft.recoveryservices/recovery-services-vm-workload-backup/metadata.json
  quickstarts/microsoft.recoveryservices/recovery-services-vm-workload-backup/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.recoveryservices/recovery-services-vm-workload-backup/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#10988 COPY-NOT-FIXED: couchbase to application-workloads\couchbase
  application-workloads/couchbase/couchbase/README.md
  application-workloads/couchbase/couchbase/azuredeploy.json
  application-workloads/couchbase/couchbase/azuredeploy.parameters.json
  application-workloads/couchbase/couchbase/metadata.json
  application-workloads/couchbase/couchbase/scripts/server.sh
  application-workloads/couchbase/couchbase/scripts/syncGateway.sh
  application-workloads/couchbase/couchbase/scripts/util.sh
Labels: best practices violations

#10989 COPY-NOT-FIXED: 101-scheduler-service-bus to quickstarts\microsoft.servicebus
  quickstarts/microsoft.servicebus/scheduler-service-bus/README.md
  quickstarts/microsoft.servicebus/scheduler-service-bus/azuredeploy.json
  quickstarts/microsoft.servicebus/scheduler-service-bus/azuredeploy.parameters.json
  quickstarts/microsoft.servicebus/scheduler-service-bus/metadata.json
Labels: best practices violations

#10993 COPY-NOT-FIXED: 101-sql-vm-aglistener-setup to quickstarts\microsoft.sqlvirtualmachine
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-aglistener-setup/README.md
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-aglistener-setup/azuredeploy.json
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-aglistener-setup/metadata.json
Labels: best practices violations

#10995 COPY-NOT-FIXED: 101-sql-vm-ag-setup to quickstarts\microsoft.sqlvirtualmachine
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-ag-setup/README.md
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-ag-setup/azuredeploy.json
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-ag-setup/metadata.json
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-ag-setup/nested/join-cluster.json
Labels: best practices violations

#10996 COPY-NOT-FIXED: cloudera-director-on-centos to application-workloads\cloudera
  application-workloads/cloudera/cloudera-director-on-centos/CHANGELOG.md
  application-workloads/cloudera/cloudera-director-on-centos/LICENSE.txt
  application-workloads/cloudera/cloudera-director-on-centos/README.md
  application-workloads/cloudera/cloudera-director-on-centos/azuredeploy.json
  application-workloads/cloudera/cloudera-director-on-centos/azuredeploy.parameters.json
  application-workloads/cloudera/cloudera-director-on-centos/director-node-and-shared-resources.json
  application-workloads/cloudera/cloudera-director-on-centos/metadata.json
  application-workloads/cloudera/cloudera-director-on-centos/network-restart-existing-vnet.json
  application-workloads/cloudera/cloudera-director-on-centos/network-restart-new-vnet.json
  application-workloads/cloudera/cloudera-director-on-centos/prepare-conf-launch-cluster.json
  application-workloads/cloudera/cloudera-director-on-centos/scripts/azure.simple.conf
  application-workloads/cloudera/cloudera-director-on-centos/scripts/director_user_passwd.py
  application-workloads/cloudera/cloudera-director-on-centos/scripts/initialize-director-server.sh
  application-workloads/cloudera/cloudera-director-on-centos/scripts/initialize-dns-server.sh
  application-workloads/cloudera/cloudera-director-on-centos/scripts/initialize-mysql-server.sh
  application-workloads/cloudera/cloudera-director-on-centos/scripts/marketing.py
  application-workloads/cloudera/cloudera-director-on-centos/scripts/prepare-director-conf.py
  application-workloads/cloudera/cloudera-director-on-centos/scripts/prepare-mysql-disks.sh
  application-workloads/cloudera/cloudera-director-on-centos/scripts/requirements.txt
  application-workloads/cloudera/cloudera-director-on-centos/scripts/setup-default.py
  application-workloads/cloudera/cloudera-director-on-centos/scripts/update-vm-dns.sh
  application-workloads/cloudera/cloudera-director-on-centos/shared-resources-existing-vnet.json
  application-workloads/cloudera/cloudera-director-on-centos/shared-resources-new-vnet.json
  application-workloads/cloudera/cloudera-director-on-centos/update-existing-vnet-dns.json
  application-workloads/cloudera/cloudera-director-on-centos/update-new-vnet-dns.json
Labels: best practices violations

#10997 COPY-NOT-FIXED: chef-ha-cluster to application-workloads\chef
  application-workloads/chef/chef-ha-cluster/README.md
  application-workloads/chef/chef-ha-cluster/azuredeploy.json
  application-workloads/chef/chef-ha-cluster/azuredeploy.parameters.json
  application-workloads/chef/chef-ha-cluster/metadata.json
  application-workloads/chef/chef-ha-cluster/scripts/BEFollowerSetup.sh
  application-workloads/chef/chef-ha-cluster/scripts/BELeaderSetup.sh
  application-workloads/chef/chef-ha-cluster/scripts/FE0Setup.sh
  application-workloads/chef/chef-ha-cluster/scripts/FESetup.sh
Labels: best practices violations

#10998 COPY-NOT-FIXED: 101-visual-studio-team-services-project-create to application-workloads\visualstudio
  application-workloads/visualstudio/visual-studio-team-services-project-create/README.md
  application-workloads/visualstudio/visual-studio-team-services-project-create/azuredeploy.json
  application-workloads/visualstudio/visual-studio-team-services-project-create/azuredeploy.parameters.json
  application-workloads/visualstudio/visual-studio-team-services-project-create/metadata.json
Labels: best practices violations

#10999 COPY-NOT-FIXED: chef-automate-ha to application-workloads\chef
  application-workloads/chef/chef-automate-ha/.gitignore
  application-workloads/chef/chef-automate-ha/LICENSE
  application-workloads/chef/chef-automate-ha/README.md
  application-workloads/chef/chef-automate-ha/azuredeploy.json
  application-workloads/chef/chef-automate-ha/azuredeploy.parameters.json
  application-workloads/chef/chef-automate-ha/metadata.json
  application-workloads/chef/chef-automate-ha/nested/availabilitySetsResource.json
  application-workloads/chef/chef-automate-ha/nested/be-networkInterfacesResource.json
  application-workloads/chef/chef-automate-ha/nested/chefAuto-networkInterfacesResource.json
  application-workloads/chef/chef-automate-ha/nested/diagnosticStorageAccountResource.json
  application-workloads/chef/chef-automate-ha/nested/fe-be-virtualmachines-with-extensions.json
  application-workloads/chef/chef-automate-ha/nested/fe-be-virtualmachines-with-extensions1.json
  application-workloads/chef/chef-automate-ha/nested/fe-networkInterfacesResource.json
  application-workloads/chef/chef-automate-ha/nested/keyvaultResource.json
  application-workloads/chef/chef-automate-ha/nested/loadBalancersResource.json
  application-workloads/chef/chef-automate-ha/nested/managedDisksResource.json
  application-workloads/chef/chef-automate-ha/nested/networkSecurityGroupsResource.json
  application-workloads/chef/chef-automate-ha/nested/publicIPAddressResource.json
  application-workloads/chef/chef-automate-ha/nested/virtualNetworksResource.json
Labels: best practices violations

#11000 COPY-NOT-FIXED: centos-2nics-lb-cluster to demos
  demos/centos-2nics-lb-cluster/README.md
  demos/centos-2nics-lb-cluster/azuredeploy.json
  demos/centos-2nics-lb-cluster/azuredeploy.parameters.json
  demos/centos-2nics-lb-cluster/deploy.sh
  demos/centos-2nics-lb-cluster/metadata.json
Labels: best practices violations

#11003 COPY-NOT-FIXED: bosh-cf-crossregion to application-workloads\bosh
  application-workloads/bosh/bosh-cf-crossregion/README.md
  application-workloads/bosh/bosh-cf-crossregion/azuredeploy.json
  application-workloads/bosh/bosh-cf-crossregion/azuredeploy.parameters.json
  application-workloads/bosh/bosh-cf-crossregion/manifests/bosh.yml
  application-workloads/bosh/bosh-cf-crossregion/manifests/cross.yml
  application-workloads/bosh/bosh-cf-crossregion/metadata.json
  application-workloads/bosh/bosh-cf-crossregion/scripts/create_cert.sh
  application-workloads/bosh/bosh-cf-crossregion/scripts/deploy_bosh.sh
  application-workloads/bosh/bosh-cf-crossregion/scripts/deploy_cloudfoundry.sh
  application-workloads/bosh/bosh-cf-crossregion/scripts/init.sh
  application-workloads/bosh/bosh-cf-crossregion/scripts/setup_env
  application-workloads/bosh/bosh-cf-crossregion/scripts/setup_env.py
Labels: best practices violations

#11004 COPY-NOT-FIXED: bootstorm-vm-boot-time to demos
  demos/bootstorm-vm-boot-time/README.md
  demos/bootstorm-vm-boot-time/VMBootAll.zip
  demos/bootstorm-vm-boot-time/azuredeploy.json
  demos/bootstorm-vm-boot-time/azuredeploy.parameters.json
  demos/bootstorm-vm-boot-time/metadata.json
Labels: best practices violations

#11007 COPY-NOT-FIXED: azmgmt-demo to demos
  demos/azmgmt-demo/README.md
  demos/azmgmt-demo/azuredeploy.json
  demos/azmgmt-demo/azuredeploy.parameters.json
  demos/azmgmt-demo/images/dashboard-new.png
  demos/azmgmt-demo/metadata.json
  demos/azmgmt-demo/nestedtemplates/asrRunbooks.json
  demos/azmgmt-demo/nestedtemplates/drEnablement.json
  demos/azmgmt-demo/nestedtemplates/dscConfigs.json
  demos/azmgmt-demo/nestedtemplates/managedLinuxBackup.json
  demos/azmgmt-demo/nestedtemplates/managedVms.json
  demos/azmgmt-demo/nestedtemplates/managedVmsBackup.json
  demos/azmgmt-demo/nestedtemplates/mgmtDashboards.json
  demos/azmgmt-demo/nestedtemplates/omsAutomation.json
  demos/azmgmt-demo/nestedtemplates/omsRecoveryServices.json
  demos/azmgmt-demo/nestedtemplates/omsWorkspace.json
  demos/azmgmt-demo/nestedtemplates/scripts/ASR-AddMultipleLoadBalancers.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/ASR-AddPublicIp.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/ASR-AddSingleLoadBalancer.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/ASR-AddSingleNSGPublicIp.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/ASR-DNS-UpdateIP.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/ASR-SQL-FailoverAG.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/ASR-SQL-FailoverAGClassic.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/ASR-Wordpress-ChangeMysqlConfig.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/Automated-IaaS-Backup.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/SQLAGFailover.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/UpdateDNS.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/UpdateLCMforAAPull.zip
  demos/azmgmt-demo/nestedtemplates/scripts/oms.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/omsasr.ps1
  demos/azmgmt-demo/nestedtemplates/scripts/omsservice.ps1
Labels: best practices violations

#11010 COPY-NOT-FIXED: ansible-advancedlinux to application-workloads\ansible
  application-workloads/ansible/ansible-advancedlinux/GetSSHFromPrivateStorageAccount.py
  application-workloads/ansible/ansible-advancedlinux/InitStorage_RAID.yml
  application-workloads/ansible/ansible-advancedlinux/README.md
  application-workloads/ansible/ansible-advancedlinux/azuredeploy.json
  application-workloads/ansible/ansible-advancedlinux/azuredeploy.parameters.json
  application-workloads/ansible/ansible-advancedlinux/configure_ansible.sh
  application-workloads/ansible/ansible-advancedlinux/configure_ssh_root.sh
  application-workloads/ansible/ansible-advancedlinux/metadata.json
Labels: best practices violations
