Repository Azure/azure-quickstart-templates, pull requests merged in 2021-04, with the labels that each got.

#8946 Updates to ev3, HDI 4.0 and network API versions
  101-hdinsight-hbase-replication-two-vnets-same-region/README.md
  101-hdinsight-hbase-replication-two-vnets-same-region/azuredeploy.json
  101-hdinsight-hbase-replication-two-vnets-same-region/metadata.json
Labels: best practices

#8952 add storage module
  modules/Microsoft.Storage/storageAccounts/0.9/README.md
  modules/Microsoft.Storage/storageAccounts/0.9/azuredeploy.json
  modules/Microsoft.Storage/storageAccounts/0.9/azuredeploy.parameters.json
  modules/Microsoft.Storage/storageAccounts/0.9/metadata.json
Labels: readme

#8362 Update API version on 201-aci-wordpress-vnet
  201-aci-wordpress-vnet/README.md
  201-aci-wordpress-vnet/azuredeploy.json
  201-aci-wordpress-vnet/metadata.json
Labels: readme

#8985 FIX-TEMPLATE: 101-automation
  101-automation/azuredeploy.json
  101-automation/azuredeploy.parameters.json
  101-automation/azuredeploy.parameters.us.json
Labels: best practices, metadata

#9006 Merge to microsoft branch
  201-api-management-logs-to-moesif-using-eventhub-webapp/README.md
  201-api-management-logs-to-moesif-using-eventhub-webapp/azuredeploy.json
  201-api-management-logs-to-moesif-using-eventhub-webapp/metadata.json
  201-api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/apis/policies.json
  201-api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/sites.json
  201-api-management-logs-to-moesif-using-eventhub-webapp/scripts/apim-2-moesif-webjob-webdeploy.zip
  201-api-management-logs-to-moesif-using-eventhub-webapp/scripts/build-webdeploy.sh
Labels: best practices, needs/author feedback

#9007 201-encrypt-create-new-vm-gallery-image
  201-encrypt-create-new-vm-gallery-image/azuredeploy.json
  201-encrypt-create-new-vm-gallery-image/azuredeploy.parameters.json
  201-encrypt-create-new-vm-gallery-image/azuredeploy.parameters.us.json
Labels: best practices, metadata

#9144 added sample for subscription creation
  managementgroup-deployments/create-subscription/README.md
  managementgroup-deployments/create-subscription/azuredeploy.json
  managementgroup-deployments/create-subscription/azuredeploy.parameters.json
  managementgroup-deployments/create-subscription/metadata.json
Labels: manual validation

#9146 added sample
  managementgroup-deployments/create-subscription-resourcegroup/README.md
  managementgroup-deployments/create-subscription-resourcegroup/azuredeploy.json
  managementgroup-deployments/create-subscription-resourcegroup/azuredeploy.parameters.json
  managementgroup-deployments/create-subscription-resourcegroup/metadata.json
Labels: best practices, manual validation

#9214 MOVE: 101-azure-database-migration-service to quickstarts\microsoft.datamigration
  101-azure-database-migration-service/README.md
  101-azure-database-migration-service/metadata.json
  quickstarts/microsoft.datamigration/azure-database-migration-service/AddDatabaseToSqlServer.ps1
  quickstarts/microsoft.datamigration/azure-database-migration-service/README.md
  quickstarts/microsoft.datamigration/azure-database-migration-service/azuredeploy.json
  quickstarts/microsoft.datamigration/azure-database-migration-service/azuredeploy.parameters.json
  quickstarts/microsoft.datamigration/azure-database-migration-service/metadata.json
  quickstarts/microsoft.datamigration/azure-database-migration-service/templatefiles/AdventureWorks2016.bacpac
Labels: best practices

#9210 MOVE: 101-hdinsight-autoscale-schedulebased to quickstarts\microsoft.hdinsight
  101-hdinsight-autoscale-schedulebased/README.md
  quickstarts/microsoft.hdinsight/hdinsight-autoscale-schedulebased/README.md
  quickstarts/microsoft.hdinsight/hdinsight-autoscale-schedulebased/azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-autoscale-schedulebased/azuredeploy.parameters.json
  quickstarts/microsoft.hdinsight/hdinsight-autoscale-schedulebased/metadata.json
Labels: best practices

#9209 MOVE: 101-hdinsight-autoscale-loadbased to quickstarts\microsoft.hdinsight
  101-hdinsight-autoscale-loadbased/README.md
  quickstarts/microsoft.hdinsight/hdinsight-autoscale-loadbased/README.md
  quickstarts/microsoft.hdinsight/hdinsight-autoscale-loadbased/azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-autoscale-loadbased/azuredeploy.parameters.json
  quickstarts/microsoft.hdinsight/hdinsight-autoscale-loadbased/metadata.json
Labels: best practices

#9205 MOVE: 101-expressroute-circuit-create to quickstarts\microsoft.network
  101-expressroute-circuit-create/README.md
  101-expressroute-circuit-create/metadata.json
  quickstarts/microsoft.network/expressroute-circuit-create/README.md
  quickstarts/microsoft.network/expressroute-circuit-create/azuredeploy.json
  quickstarts/microsoft.network/expressroute-circuit-create/azuredeploy.parameters.json
  quickstarts/microsoft.network/expressroute-circuit-create/metadata.json
Labels: best practices

#9072 Update SignalR 101 to include Managed Identity field
  101-signalr/azuredeploy.json
Labels: metadata

#9191 MOVE: 101-data-factory-v2-blob-to-postgresql-copy to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-postgresql-copy/README.md
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-postgresql-copy/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-postgresql-copy/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-postgresql-copy/metadata.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-postgresql-copy/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-postgresql-copy/prereqs/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-postgresql-copy/scripts/runmonitor.ps1
Labels: best practices

#9190 MOVE: 101-data-factory-v2-blob-to-mysql-copy to quickstarts\microsoft.datafactory
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-mysql-copy/README.md
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-mysql-copy/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-mysql-copy/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-mysql-copy/metadata.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-mysql-copy/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-mysql-copy/prereqs/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-mysql-copy/scripts/runmonitor.ps1
Labels: best practices

#9121 MOVE: 101-cosmosdb-mongodb to quickstarts\microsoft.documentdb
  101-cosmosdb-mongodb/README.md
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/README.md
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/azuredeploy.parameters.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/azuredeploy.parameters.us.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/metadata.json
Labels: best practices

#9088 MOVE: 101-batch-with-keyvault-pfx-password to quickstarts\microsoft.batch
  101-batch-with-keyvault-pfx-password/README.md
  101-batch-with-keyvault-pfx-password/metadata.json
  quickstarts/microsoft.batch/batch-with-keyvault-pfx-password/README.md
  quickstarts/microsoft.batch/batch-with-keyvault-pfx-password/azuredeploy.json
  quickstarts/microsoft.batch/batch-with-keyvault-pfx-password/azuredeploy.parameters.json
  quickstarts/microsoft.batch/batch-with-keyvault-pfx-password/metadata.json
  quickstarts/microsoft.batch/batch-with-keyvault-pfx-password/prereqs/.settings.json
  quickstarts/microsoft.batch/batch-with-keyvault-pfx-password/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.batch/batch-with-keyvault-pfx-password/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices

#9060 MOVE: 101-automation-configuration to quickstarts\microsoft.automation
  quickstarts/microsoft.automation/automation-configuration/README.md
  quickstarts/microsoft.automation/automation-configuration/azuredeploy.json
  quickstarts/microsoft.automation/automation-configuration/azuredeploy.parameters.json
  quickstarts/microsoft.automation/automation-configuration/metadata.json
  quickstarts/microsoft.automation/automation-configuration/nested/DomainControllerConfig.ps1
  quickstarts/microsoft.automation/automation-configuration/nested/provisionConfiguration.json
  quickstarts/microsoft.automation/automation-configuration/nested/provisionDNS.json
  quickstarts/microsoft.automation/automation-configuration/nested/provisionNetwork.json
  quickstarts/microsoft.automation/automation-configuration/nested/provisionServer.json
Labels: best practices

#9332 MOVE: 201-front-door-rate-limiting to quickstarts\microsoft.network
  201-front-door-rate-limiting/README.md
  201-front-door-rate-limiting/metadata.json
  quickstarts/microsoft.network/front-door-rate-limiting/README.md
  quickstarts/microsoft.network/front-door-rate-limiting/azuredeploy.json
  quickstarts/microsoft.network/front-door-rate-limiting/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-rate-limiting/metadata.json
Labels: best practices

#9331 MOVE: 201-front-door-waf-clientip to quickstarts\microsoft.network
  201-front-door-waf-clientip/README.md
  201-front-door-waf-clientip/metadata.json
  quickstarts/microsoft.network/front-door-waf-clientip/README.md
  quickstarts/microsoft.network/front-door-waf-clientip/azuredeploy.json
  quickstarts/microsoft.network/front-door-waf-clientip/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-waf-clientip/metadata.json
Labels: best practices

#9330 MOVE: 201-front-door-waf-http-params to quickstarts\microsoft.network
  201-front-door-waf-http-params/README.md
  201-front-door-waf-http-params/metadata.json
  quickstarts/microsoft.network/front-door-waf-http-params/README.md
  quickstarts/microsoft.network/front-door-waf-http-params/azuredeploy.json
  quickstarts/microsoft.network/front-door-waf-http-params/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-waf-http-params/metadata.json
Labels: best practices

#9325 MOVE: 201-key-vault-use-dynamic-id to quickstarts\microsoft.keyvault
  201-key-vault-use-dynamic-id/README.md
  quickstarts/microsoft.keyvault/key-vault-use-dynamic-id/README.md
  quickstarts/microsoft.keyvault/key-vault-use-dynamic-id/azuredeploy.json
  quickstarts/microsoft.keyvault/key-vault-use-dynamic-id/azuredeploy.parameters.json
  quickstarts/microsoft.keyvault/key-vault-use-dynamic-id/metadata.json
  quickstarts/microsoft.keyvault/key-vault-use-dynamic-id/nested/sqlserver.json
Labels: best practices

#9322 MOVE: 201-logic-app-correlation-using-servicebus to quickstarts\microsoft.logic
  201-logic-app-correlation-using-servicebus/README.md
  quickstarts/microsoft.logic/logic-app-correlation-using-servicebus/README.md
  quickstarts/microsoft.logic/logic-app-correlation-using-servicebus/azuredeploy.json
  quickstarts/microsoft.logic/logic-app-correlation-using-servicebus/azuredeploy.parameters.json
  quickstarts/microsoft.logic/logic-app-correlation-using-servicebus/metadata.json
Labels: best practices

#9277 MOVE: 201-vm-custom-script-windows to quickstarts\microsoft.compute
  201-vm-custom-script-windows/README.md
  quickstarts/microsoft.compute/vm-custom-script-windows/Copy-FileFromAzure.ps1
  quickstarts/microsoft.compute/vm-custom-script-windows/FileToBeCopied.txt
  quickstarts/microsoft.compute/vm-custom-script-windows/README.md
  quickstarts/microsoft.compute/vm-custom-script-windows/azuredeploy.json
  quickstarts/microsoft.compute/vm-custom-script-windows/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-custom-script-windows/metadata.json
Labels: best practices

#9276 MOVE: 201-vm-dedicated-hosts to quickstarts\microsoft.compute
  201-vm-dedicated-hosts/README.md
  201-vm-dedicated-hosts/metadata.json
  quickstarts/microsoft.compute/vm-dedicated-hosts/README.md
  quickstarts/microsoft.compute/vm-dedicated-hosts/azuredeploy.json
  quickstarts/microsoft.compute/vm-dedicated-hosts/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-dedicated-hosts/metadata.json
Labels: best practices

#9275 MOVE: 201-vm-dynamic-data-disks-selection to quickstarts\microsoft.compute
  201-vm-dynamic-data-disks-selection/README.md
  quickstarts/microsoft.compute/vm-dynamic-data-disks-selection/README.md
  quickstarts/microsoft.compute/vm-dynamic-data-disks-selection/azuredeploy.json
  quickstarts/microsoft.compute/vm-dynamic-data-disks-selection/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-dynamic-data-disks-selection/metadata.json
Labels: best practices

#9267 MOVE: 101-perforce-helix-core-server to application-workloads\perforce
  101-perforce-helix-core-server/metadata.json
  application-workloads/perforce/perforce-helix-core-server/README.md
  application-workloads/perforce/perforce-helix-core-server/azuredeploy.json
  application-workloads/perforce/perforce-helix-core-server/azuredeploy.parameters.json
  application-workloads/perforce/perforce-helix-core-server/metadata.json
  application-workloads/perforce/perforce-helix-core-server/scripts/configure-linux.sh
Labels: best practices

#9313 MOVE: 201-servicebus-create-topic-subscription-rule to quickstarts\microsoft.servicebus
  201-servicebus-create-topic-subscription-rule/README.md
  quickstarts/microsoft.servicebus/servicebus-create-topic-subscription-rule/README.md
  quickstarts/microsoft.servicebus/servicebus-create-topic-subscription-rule/azuredeploy.json
  quickstarts/microsoft.servicebus/servicebus-create-topic-subscription-rule/azuredeploy.parameters.json
  quickstarts/microsoft.servicebus/servicebus-create-topic-subscription-rule/metadata.json
Labels: best practices

#9297 MOVE: 201-storage-account-service-encryption-create to quickstarts\microsoft.storage
  201-storage-account-service-encryption-create/README.md
  quickstarts/microsoft.storage/storage-account-service-encryption-create/README.md
  quickstarts/microsoft.storage/storage-account-service-encryption-create/azuredeploy.json
  quickstarts/microsoft.storage/storage-account-service-encryption-create/azuredeploy.parameters.json
  quickstarts/microsoft.storage/storage-account-service-encryption-create/metadata.json
Labels: best practices

#9296 MOVE: 201-storage-advanced-threat-protection-create to quickstarts\microsoft.storage
  201-storage-advanced-threat-protection-create/README.md
  quickstarts/microsoft.storage/storage-advanced-threat-protection-create/README.md
  quickstarts/microsoft.storage/storage-advanced-threat-protection-create/azuredeploy.json
  quickstarts/microsoft.storage/storage-advanced-threat-protection-create/azuredeploy.parameters.json
  quickstarts/microsoft.storage/storage-advanced-threat-protection-create/metadata.json
Labels: best practices

#9288 MOVE: 101-servicebus-pn-ar to quickstarts\microsoft.servicebus
  101-servicebus-pn-ar/README.md
  quickstarts/microsoft.servicebus/servicebus-pn-ar/README.md
  quickstarts/microsoft.servicebus/servicebus-pn-ar/azuredeploy.json
  quickstarts/microsoft.servicebus/servicebus-pn-ar/azuredeploy.parameters.json
  quickstarts/microsoft.servicebus/servicebus-pn-ar/metadata.json
Labels: best practices

#9286 MOVE: 101-recovery-services-weekly-backup-policy-create to quickstarts\microsoft.recoveryservices
  101-recovery-services-weekly-backup-policy-create/README.md
  quickstarts/microsoft.recoveryservices/recovery-services-weekly-backup-policy-create/README.md
  quickstarts/microsoft.recoveryservices/recovery-services-weekly-backup-policy-create/azuredeploy.json
  quickstarts/microsoft.recoveryservices/recovery-services-weekly-backup-policy-create/azuredeploy.parameters.json
  quickstarts/microsoft.recoveryservices/recovery-services-weekly-backup-policy-create/metadata.json
Labels: best practices

#9255 MOVE: 101-mongodb-sharded-on-centos to application-workloads\airflow
  application-workloads/airflow/mongodb-sharded-on-centos/README.md
  application-workloads/airflow/mongodb-sharded-on-centos/azuredeploy.json
  application-workloads/airflow/mongodb-sharded-on-centos/azuredeploy.parameters.json
  application-workloads/airflow/mongodb-sharded-on-centos/images/Mongo Sharded Cluster.png
  application-workloads/airflow/mongodb-sharded-on-centos/metadata.json
  application-workloads/airflow/mongodb-sharded-on-centos/nested/config-resources.json
  application-workloads/airflow/mongodb-sharded-on-centos/nested/replica-resources.json
  application-workloads/airflow/mongodb-sharded-on-centos/nested/router-resources.json
  application-workloads/airflow/mongodb-sharded-on-centos/nested/shared-resources.json
  application-workloads/airflow/mongodb-sharded-on-centos/scripts/config_primary.sh
  application-workloads/airflow/mongodb-sharded-on-centos/scripts/config_secondary.sh
  application-workloads/airflow/mongodb-sharded-on-centos/scripts/replica_primary.sh
  application-workloads/airflow/mongodb-sharded-on-centos/scripts/replica_secondary.sh
  application-workloads/airflow/mongodb-sharded-on-centos/scripts/router.sh
Labels: best practices

#9358 FIX-TEMPLATE: 101-backup-la-reporting
  101-backup-la-reporting/README.md
  101-backup-la-reporting/azuredeploy.json
  101-backup-la-reporting/azuredeploy.parameters.json
  101-backup-la-reporting/metadata.json
  101-backup-la-reporting/nested/azure_alerts.json
  101-backup-la-reporting/nested/backup_items.json
  101-backup-la-reporting/nested/backup_jobs_log.json
  101-backup-la-reporting/nested/backup_jobs_non_log.json
  101-backup-la-reporting/nested/cloud_storage.json
  101-backup-la-reporting/nested/on_prem_alerts.json
  101-backup-la-reporting/nested/restore_jobs.json
  101-backup-la-reporting/prereqs/.settings.json
  101-backup-la-reporting/prereqs/prereq.azuredeploy.json
  101-backup-la-reporting/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices

#9360 FIX-TEMPLATE: 101-VM-Virus-Attack-Prevention
  101-VM-Virus-Attack-Prevention/README.md
  101-VM-Virus-Attack-Prevention/azuredeploy.json
  101-VM-Virus-Attack-Prevention/metadata.json
  101-VM-Virus-Attack-Prevention/nested/microsoft.loganalytics/workspaces.json
Labels: best practices

#9361 FIX-TEMPLATE: 101-XSS-Attack-Prevention
  101-XSS-Attack-Prevention/README.md
  101-XSS-Attack-Prevention/azuredeploy.json
  101-XSS-Attack-Prevention/azuredeploy.parameters.json
  101-XSS-Attack-Prevention/metadata.json
  101-XSS-Attack-Prevention/nested/microsoft.loganalytics/workspaces.json
Labels: best practices
