Repository Azure/azure-quickstart-templates, pull requests merged in 2021-07, with the labels that each got.

#10671 FIX-BESTPRACTICES: 101-VM-Virus-Attack-Prevention
  quickstarts/microsoft.compute/vm-virus-attack-prevention/azuredeploy.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.compute/vm.windows.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.loganalytics/workspaces.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.network/nic-with-pip.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.network/nsg.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.network/publicipaddress.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.network/virtualnetworks.json
Labels: best practices violations

#11043 Migrate bicep example: 101/databricks-workspace
  quickstarts/microsoft.databricks/databricks-workspace/README.md
  quickstarts/microsoft.databricks/databricks-workspace/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace/main.bicep
  quickstarts/microsoft.databricks/databricks-workspace/metadata.json
Labels: bicep, bicep example migration

#11134 multi-api add bicep support
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/README.md
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/metadata.json
Labels: best practices violations, bicep, bicep-decompile

#11272 COPY: 101-datacollectionrule-create-syslog to quickstarts\microsoft.insights
  quickstarts/microsoft.insights/datacollectionrule-create-syslog/README.md
  quickstarts/microsoft.insights/datacollectionrule-create-syslog/SECURITY.md
  quickstarts/microsoft.insights/datacollectionrule-create-syslog/azuredeploy.json
  quickstarts/microsoft.insights/datacollectionrule-create-syslog/azuredeploy.parameters.json
  quickstarts/microsoft.insights/datacollectionrule-create-syslog/metadata.json
  quickstarts/microsoft.insights/datacollectionrule-create-syslog/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.insights/datacollectionrule-create-syslog/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#11275 COPY: 101-route-server-quagga to quickstarts\microsoft.network
  quickstarts/microsoft.network/route-server-quagga/README.md
  quickstarts/microsoft.network/route-server-quagga/azuredeploy.json
  quickstarts/microsoft.network/route-server-quagga/azuredeploy.parameters.json
  quickstarts/microsoft.network/route-server-quagga/images/1.png
  quickstarts/microsoft.network/route-server-quagga/metadata.json
  quickstarts/microsoft.network/route-server-quagga/scripts/quaggadeploy.sh
Labels: best practices violations

#11278 COPY: 101-vm-userdata to quickstarts\microsoft.compute
  quickstarts/microsoft.compute/vm-userdata/README.md
  quickstarts/microsoft.compute/vm-userdata/azuredeploy.json
  quickstarts/microsoft.compute/vm-userdata/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-userdata/metadata.json
Labels: best practices violations

#11280 COPY: 201-file-share-private-endpoint to quickstarts\microsoft.storage
  quickstarts/microsoft.storage/file-share-private-endpoint/README.md
  quickstarts/microsoft.storage/file-share-private-endpoint/azuredeploy.json
  quickstarts/microsoft.storage/file-share-private-endpoint/azuredeploy.parameters.json
  quickstarts/microsoft.storage/file-share-private-endpoint/images/architecture.png
  quickstarts/microsoft.storage/file-share-private-endpoint/images/nslookup.png
  quickstarts/microsoft.storage/file-share-private-endpoint/images/resourcegroup.png
  quickstarts/microsoft.storage/file-share-private-endpoint/metadata.json
  quickstarts/microsoft.storage/file-share-private-endpoint/scripts/file_nslookup.sh
Labels: best practices violations

#11281 COPY: 201-front-door-premium-waf-managed to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-premium-waf-managed/README.md
  quickstarts/microsoft.network/front-door-premium-waf-managed/azuredeploy.json
  quickstarts/microsoft.network/front-door-premium-waf-managed/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-premium-waf-managed/main.bicep
  quickstarts/microsoft.network/front-door-premium-waf-managed/metadata.json
  quickstarts/microsoft.network/front-door-premium-waf-managed/prereqs/prereq.azuredeploy.bicep
  quickstarts/microsoft.network/front-door-premium-waf-managed/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.network/front-door-premium-waf-managed/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, bicep

#11282 COPY: 201-front-door-standard-premium to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-standard-premium/README.md
  quickstarts/microsoft.network/front-door-standard-premium/azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-standard-premium/main.bicep
  quickstarts/microsoft.network/front-door-standard-premium/metadata.json
  quickstarts/microsoft.network/front-door-standard-premium/prereqs/prereq.azuredeploy.bicep
  quickstarts/microsoft.network/front-door-standard-premium/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, bicep

#11284 COPY: 201-front-door-standard-premium-geo-filtering to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-standard-premium-geo-filtering/README.md
  quickstarts/microsoft.network/front-door-standard-premium-geo-filtering/azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-geo-filtering/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-standard-premium-geo-filtering/main.bicep
  quickstarts/microsoft.network/front-door-standard-premium-geo-filtering/metadata.json
  quickstarts/microsoft.network/front-door-standard-premium-geo-filtering/prereqs/prereq.azuredeploy.bicep
  quickstarts/microsoft.network/front-door-standard-premium-geo-filtering/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-geo-filtering/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, bicep

#11285 COPY: 201-front-door-standard-premium-rate-limit to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-standard-premium-rate-limit/README.md
  quickstarts/microsoft.network/front-door-standard-premium-rate-limit/azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-rate-limit/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-standard-premium-rate-limit/main.bicep
  quickstarts/microsoft.network/front-door-standard-premium-rate-limit/metadata.json
  quickstarts/microsoft.network/front-door-standard-premium-rate-limit/prereqs/prereq.azuredeploy.bicep
  quickstarts/microsoft.network/front-door-standard-premium-rate-limit/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-rate-limit/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, bicep

#11286 COPY: 201-front-door-standard-premium-rule-set to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-standard-premium-rule-set/README.md
  quickstarts/microsoft.network/front-door-standard-premium-rule-set/azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-rule-set/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-standard-premium-rule-set/main.bicep
  quickstarts/microsoft.network/front-door-standard-premium-rule-set/metadata.json
  quickstarts/microsoft.network/front-door-standard-premium-rule-set/prereqs/prereq.azuredeploy.bicep
  quickstarts/microsoft.network/front-door-standard-premium-rule-set/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-rule-set/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, bicep

#11287 COPY: 201-front-door-standard-premium-waf-custom to quickstarts\microsoft.network
  quickstarts/microsoft.network/front-door-standard-premium-waf-custom/README.md
  quickstarts/microsoft.network/front-door-standard-premium-waf-custom/azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-waf-custom/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-standard-premium-waf-custom/main.bicep
  quickstarts/microsoft.network/front-door-standard-premium-waf-custom/metadata.json
  quickstarts/microsoft.network/front-door-standard-premium-waf-custom/prereqs/prereq.azuredeploy.bicep
  quickstarts/microsoft.network/front-door-standard-premium-waf-custom/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-waf-custom/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, bicep

#11290 COPY: 301-azure-firewall-dns-proxy to quickstarts\microsoft.network
  quickstarts/microsoft.network/azure-firewall-dns-proxy/README.md
  quickstarts/microsoft.network/azure-firewall-dns-proxy/azuredeploy.json
  quickstarts/microsoft.network/azure-firewall-dns-proxy/azuredeploy.parameters.json
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/architecture-with-custom-dns-forwader.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/architecture-without-custom-dns-forwader.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/dnat-rules.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/dns-proxy-with-custom-dns-forwarder.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/dns-proxy-without-custom-dns-forwarder.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/dns-settings.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/internet-rules.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/nslookup.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/resource-group.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/route-table.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/images/vnet-to-vnet.png
  quickstarts/microsoft.network/azure-firewall-dns-proxy/metadata.json
  quickstarts/microsoft.network/azure-firewall-dns-proxy/scripts/configure-custom-dns-forwarder.sh
  quickstarts/microsoft.network/azure-firewall-dns-proxy/scripts/test-dns-and-private-endpoints.sh
Labels: best practices violations

#11291 COPY: cohesive-vns3-free-try-now to application-workloads\cohesive
  application-workloads/cohesive/cohesive-vns3-free-try-now/README.md
  application-workloads/cohesive/cohesive-vns3-free-try-now/azuredeploy.json
  application-workloads/cohesive/cohesive-vns3-free-try-now/azuredeploy.parameters.json
  application-workloads/cohesive/cohesive-vns3-free-try-now/metadata.json
  application-workloads/cohesive/cohesive-vns3-free-try-now/scripts/CustomExtensionWindows.ps1
  application-workloads/cohesive/cohesive-vns3-free-try-now/scripts/customextensionlinux.sh
Labels: best practices violations

#11295 COPY: zookeeper-cluster-ubuntu-vm to application-workloads\apache
  application-workloads/apache/zookeeper-cluster-ubuntu-vm/README.md
  application-workloads/apache/zookeeper-cluster-ubuntu-vm/azuredeploy.json
  application-workloads/apache/zookeeper-cluster-ubuntu-vm/azuredeploy.parameters.json
  application-workloads/apache/zookeeper-cluster-ubuntu-vm/metadata.json
  application-workloads/apache/zookeeper-cluster-ubuntu-vm/zookeeper.sh
Labels: best practices violations

#11390 Migrate bicep example: 201/vnet-to-vnet-bgp
  quickstarts/microsoft.network/vnet-to-vnet-bgp/README.md
  quickstarts/microsoft.network/vnet-to-vnet-bgp/azuredeploy.json
  quickstarts/microsoft.network/vnet-to-vnet-bgp/main.bicep
  quickstarts/microsoft.network/vnet-to-vnet-bgp/metadata.json
Labels: bicep, bicep example migration

#11392 Migrate bicep example: 201/vnet-to-vnet-peering
  quickstarts/microsoft.network/vnet-to-vnet-peering/README.md
  quickstarts/microsoft.network/vnet-to-vnet-peering/azuredeploy.json
  quickstarts/microsoft.network/vnet-to-vnet-peering/main.bicep
  quickstarts/microsoft.network/vnet-to-vnet-peering/metadata.json
Labels: bicep, bicep example migration

#11421 fix install client issue
  application-workloads/sccm/sccm-technicalpreview/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-technicalpreview/DSC/InstallClient.ps1
Labels: best practices violations

#11420 Fix install client issue
  application-workloads/sccm/sccm-currentbranch/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-currentbranch/DSC/InstallClient.ps1
Labels: best practices violations

#11405 Migrate bicep example: 101/front-door-custom-domain
  quickstarts/microsoft.network/front-door-custom-domain/README.md
  quickstarts/microsoft.network/front-door-custom-domain/azuredeploy.json
  quickstarts/microsoft.network/front-door-custom-domain/main.bicep
  quickstarts/microsoft.network/front-door-custom-domain/metadata.json
Labels: bicep, bicep example migration, manual validation required

#11402 Migrate bicep example: 201/web-app-sql-database
  quickstarts/microsoft.web/web-app-sql-database/README.md
  quickstarts/microsoft.web/web-app-sql-database/azuredeploy.json
  quickstarts/microsoft.web/web-app-sql-database/main.bicep
  quickstarts/microsoft.web/web-app-sql-database/metadata.json
Labels: bicep, bicep example migration

#11398 Migrate bicep example: 201/cdn-with-storage-account
  quickstarts/microsoft.cdn/cdn-with-storage-account/README.md
  quickstarts/microsoft.cdn/cdn-with-storage-account/azuredeploy.json
  quickstarts/microsoft.cdn/cdn-with-storage-account/main.bicep
  quickstarts/microsoft.cdn/cdn-with-storage-account/metadata.json
Labels: bicep, bicep example migration

#11395 Migrate bicep example: 101/expressroute-circuit-create
  quickstarts/microsoft.network/expressroute-circuit-create/README.md
  quickstarts/microsoft.network/expressroute-circuit-create/azuredeploy.json
  quickstarts/microsoft.network/expressroute-circuit-create/azuredeploy.parameters.json
  quickstarts/microsoft.network/expressroute-circuit-create/main.bicep
  quickstarts/microsoft.network/expressroute-circuit-create/metadata.json
Labels: bicep, bicep example migration

#11394 Migrate bicep example: 301/insights-alertrules-application-insights
  quickstarts/microsoft.insights/insights-alertrules-application-insights/README.md
  quickstarts/microsoft.insights/insights-alertrules-application-insights/azuredeploy.json
  quickstarts/microsoft.insights/insights-alertrules-application-insights/main.bicep
  quickstarts/microsoft.insights/insights-alertrules-application-insights/metadata.json
Labels: best practices violations, bicep, bicep example migration

#11433 FIX-TEMPLATE: 101-vm-sql-existing-autobackup-update
  quickstarts/microsoft.compute/vm-sql-existing-autobackup-update/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-sql-existing-autobackup-update/metadata.json
  quickstarts/microsoft.compute/vm-sql-existing-autobackup-update/prereqs/.settings.json
  quickstarts/microsoft.compute/vm-sql-existing-autobackup-update/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.compute/vm-sql-existing-autobackup-update/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, readme violations

#11444 FIX-TEMPLATE: 101-data-factory-v2-onprem-sql-to-blob-copy
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/metadata.json
Labels: best practices violations, manual validation required

#11445 FIX-TEMPLATE: 101-data-factory-chained-copy-activities
  quickstarts/microsoft.datafactory/data-factory-chained-copy-activities/metadata.json
Labels: best practices violations, manual validation required

#11465 Azure Backup: Disk protection bug fix
  quickstarts/microsoft.dataprotection/backup-create-disk-enable-protection/azuredeploy.json
  quickstarts/microsoft.dataprotection/backup-create-disk-enable-protection/metadata.json
Labels: best practices violations

#11469 FIX-BESTPRACTICES: kafka-on-ubuntu
  application-workloads/kafka/kafka-on-ubuntu/azuredeploy.json
  application-workloads/kafka/kafka-on-ubuntu/azuredeploy.parameters.json
  application-workloads/kafka/kafka-on-ubuntu/jumpbox-resources-disabled.json
  application-workloads/kafka/kafka-on-ubuntu/jumpbox-resources-enabled.json
  application-workloads/kafka/kafka-on-ubuntu/shared-resources.json
Labels: best practices violations

#11489 Replaced the version EAP 7.3 on RHEL 8.0 to EAP 7.3 on RHEL 8.4 for JBoss EAP on RHEL (stand-alone VM)
  application-workloads/jboss/jboss-eap-standalone-rhel/README.md
  application-workloads/jboss/jboss-eap-standalone-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-standalone-rhel/images/app.png
  application-workloads/jboss/jboss-eap-standalone-rhel/metadata.json
  application-workloads/jboss/jboss-eap-standalone-rhel/scripts/JBoss-EAP_on_Azure.war
  application-workloads/jboss/jboss-eap-standalone-rhel/scripts/jbosseap-setup-redhat.sh
Labels: manual validation required

#11490 Replace the version EAP 7.3 on RHEL 8.0 to EAP 7.3 on RHEL 8.4 for JBoss EAP on RHEL (clustered, multi-VM)
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/README.md
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/images/eap-session.png
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/metadata.json
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/scripts/eap-session-replication.war
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/scripts/jbosseap-setup-redhat.sh
Labels: manual validation required

#11493 Replaced the version EAP 7.3 on RHEL 8.0 to EAP 7.3 on RHEL 8.4 for JBoss EAP on RHEL (clustered, VMSS)
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/README.md
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/images/eap-session.png
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/metadata.json
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/scripts/eap-session-replication.war
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/scripts/jbosseap-setup-redhat.sh
Labels: manual validation required

#11389 (AZUREVAVS-105) Release 1.2MPP
  sas-9.4m7-VA-MPP/ansible/install_hadoop.yaml
  sas-9.4m7-VA-MPP/metadata.json
  sas-9.4m7-VA-MPP/scripts/SetupJump.sh
Labels: ROOT, UPPERCASE, best practices violations

#11207 sql analytical store add bicep support
  quickstarts/microsoft.documentdb/cosmosdb-sql-analytical-store/README.md
  quickstarts/microsoft.documentdb/cosmosdb-sql-analytical-store/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-sql-analytical-store/azuredeploy.parameters.us.json
  quickstarts/microsoft.documentdb/cosmosdb-sql-analytical-store/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-sql-analytical-store/metadata.json
Labels: bicep, bicep-decompile

#11546 Add missing description for param
  demos/cloud-shell-vnet/azuredeploy.json
  demos/cloud-shell-vnet/main.bicep
  demos/cloud-shell-vnet/metadata.json
Labels: bicep

#11118 Migrate bicep example: 101/1vm-2nics-2subnets-1vnet
  quickstarts/microsoft.compute/1vm-2nics-2subnets-1vnet/README.md
  quickstarts/microsoft.compute/1vm-2nics-2subnets-1vnet/azuredeploy.json
  quickstarts/microsoft.compute/1vm-2nics-2subnets-1vnet/main.bicep
  quickstarts/microsoft.compute/1vm-2nics-2subnets-1vnet/metadata.json
Labels: bicep, bicep example migration

#11396 Migrate bicep example: 101/webapp-managed-mysql
  quickstarts/microsoft.web/webapp-managed-mysql/README.md
  quickstarts/microsoft.web/webapp-managed-mysql/azuredeploy.json
  quickstarts/microsoft.web/webapp-managed-mysql/main.bicep
  quickstarts/microsoft.web/webapp-managed-mysql/metadata.json
Labels: bicep, bicep example migration

#11425 FIX-BESTPRACTICES: dynamic-web-tests
  demos/dynamic-web-tests/azuredeploy.json
  demos/dynamic-web-tests/prereqs/prereq.azuredeploy.json
Labels: best practices violations

#10440 FIX-BESTPRACTICES: insights-alertrules-servicehealth
  quickstarts/microsoft.insights/insights-alertrules-servicehealth/metadata.json
Labels: best practices violations

#10867 FIX-BESTPRACTICES: eventHub-create-authrule-namespace-and-eventHub
  quickstarts/microsoft.eventhub/eventhub-create-authrule-namespace-and-eventhub/azuredeploy.json
  quickstarts/microsoft.eventhub/eventhub-create-authrule-namespace-and-eventhub/azuredeploy.parameters.json
  quickstarts/microsoft.eventhub/eventhub-create-authrule-namespace-and-eventhub/metadata.json
Labels: best practices violations

#10919 FIX-BESTPRACTICES: 201-azure-relay-create-all-resources
  quickstarts/microsoft.relay/azure-relay-create-all-resources/azuredeploy.json
  quickstarts/microsoft.relay/azure-relay-create-all-resources/metadata.json
Labels: best practices violations

#11372 FIX-FAILED-BESTPRACTICES: servicebus-create-authrule-namespace-and-queue
  quickstarts/microsoft.servicebus/servicebus-create-authrule-namespace-and-queue/azuredeploy.json
  quickstarts/microsoft.servicebus/servicebus-create-authrule-namespace-and-queue/metadata.json
Labels: best practices violations

#11359 FIX-BESTPRACTICES: asr-oms-monitoring
  demos/asr-oms-monitoring/azuredeploy.json
  demos/asr-oms-monitoring/azuredeploy.parameters.json
Labels: best practices violations

#11226 FIX-BESTPRACTICES: pubnub-eventhub-bridge
  application-workloads/pubnub/pubnub-eventhub-bridge/azuredeploy.json
Labels: best practices violations

#11184 FIX-BESTPRACTICES: eventhub-namespace-vnet
  quickstarts/microsoft.eventhub/eventhub-namespace-vnet/azuredeploy.json
Labels: best practices violations

#11145 FIX-BESTPRACTICES: eventhub-create-namespace-geo-recoveryconfiguration
  quickstarts/microsoft.eventhub/eventhub-create-namespace-geo-recoveryconfiguration/azuredeploy.json
Labels: best practices violations

#11520 FIX-BESTPRACTICES: oms-azurensg-solution
  demos/oms-azurensg-solution/azuredeploy.json
Labels: best practices violations

#11077 Migrate bicep example: 101/event-grid-servicebus-queue
  quickstarts/microsoft.eventgrid/event-grid-servicebus-queue/README.md
  quickstarts/microsoft.eventgrid/event-grid-servicebus-queue/azuredeploy.json
  quickstarts/microsoft.eventgrid/event-grid-servicebus-queue/main.bicep
  quickstarts/microsoft.eventgrid/event-grid-servicebus-queue/metadata.json
Labels: best practices violations, bicep, bicep example migration

#10621 FIX-BESTPRACTICES: 101-servicebus-queue
  quickstarts/microsoft.servicebus/servicebus-queue/azuredeploy.json
  quickstarts/microsoft.servicebus/servicebus-queue/metadata.json
Labels: best practices violations

#11336 Migrate bicep example: 101/webapp-privateendpoint-vnet-injection
  quickstarts/microsoft.web/webapp-privateendpoint-vnet-injection/README.md
  quickstarts/microsoft.web/webapp-privateendpoint-vnet-injection/azuredeploy.json
  quickstarts/microsoft.web/webapp-privateendpoint-vnet-injection/main.bicep
  quickstarts/microsoft.web/webapp-privateendpoint-vnet-injection/metadata.json
Labels: bicep, bicep example migration

#11387 Migrate bicep example: 201/traffic-manager-webapp
  quickstarts/microsoft.network/traffic-manager-webapp/README.md
  quickstarts/microsoft.network/traffic-manager-webapp/azuredeploy.json
  quickstarts/microsoft.network/traffic-manager-webapp/azuredeploy.parameters.json
  quickstarts/microsoft.network/traffic-manager-webapp/main.bicep
  quickstarts/microsoft.network/traffic-manager-webapp/metadata.json
Labels: bicep, bicep example migration

#11369 FIX-FAILED-BESTPRACTICES: monitoring-webtest-metric-alert
  quickstarts/microsoft.insights/monitoring-webtest-metric-alert/azuredeploy.json
  quickstarts/microsoft.insights/monitoring-webtest-metric-alert/azuredeploy.parameters.json
  quickstarts/microsoft.insights/monitoring-webtest-metric-alert/azuredeploy.parameters.us.json
  quickstarts/microsoft.insights/monitoring-webtest-metric-alert/metadata.json
  quickstarts/microsoft.insights/monitoring-webtest-metric-alert/prereqs/prereq.azuredeploy.json
Labels: best practices violations

#11345 Migrate bicep example: 201/redis-premium-cluster-diagnostics
  quickstarts/microsoft.cache/redis-premium-cluster-diagnostics/README.md
  quickstarts/microsoft.cache/redis-premium-cluster-diagnostics/azuredeploy.json
  quickstarts/microsoft.cache/redis-premium-cluster-diagnostics/main.bicep
  quickstarts/microsoft.cache/redis-premium-cluster-diagnostics/metadata.json
Labels: bicep, bicep example migration

#11604 fix for yum install issue
  application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/README.md
  application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/azuredeploy.json
  application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/scripts/deployOpenShift.sh
  application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/scripts/openshiftCloudPakConfig.sh
  application-workloads/ibm-cloud-pak/ibm-cloud-pak-for-data/scripts/setup-nfs.sh
Labels: best practices violations, manual validation required

#11419 FIX-BESTPRACTICES: glassfish-on-suse
  quickstarts/microsoft.compute/glassfish-on-suse/azuredeploy.json
  quickstarts/microsoft.compute/glassfish-on-suse/azuredeploy.parameters.json
  quickstarts/microsoft.compute/glassfish-on-suse/nestedtemplates/azuredeploy.json
Labels: metadata violations

#11361 FIX-BESTPRACTICES: asr-automation-recovery
  demos/asr-automation-recovery/azuredeploy.json
Labels: best practices violations

#11618 FIX-BESTPRACTICES: 101-webappazure-oms-monitoring
  quickstarts/microsoft.web/webappazure-oms-monitoring/azuredeploy.json
  quickstarts/microsoft.web/webappazure-oms-monitoring/metadata.json
Labels: best practices violations

#11630 Add AdlsGen2 datastore external storage optional properties
  quickstarts/microsoft.machinelearningservices/machine-learning-datastore-create-adls-gen2/azuredeploy.json
Labels: metadata violations

#11340 Migrate bicep example: 201/aci-sftp-files
  quickstarts/microsoft.containerinstance/aci-sftp-files/README.md
  quickstarts/microsoft.containerinstance/aci-sftp-files/azuredeploy.json
  quickstarts/microsoft.containerinstance/aci-sftp-files/main.bicep
  quickstarts/microsoft.containerinstance/aci-sftp-files/metadata.json
Labels: bicep, bicep example migration

#11342 Migrate bicep example: 201/aci-wordpress
  application-workloads/wordpress/aci-wordpress/README.md
  application-workloads/wordpress/aci-wordpress/azuredeploy.json
  application-workloads/wordpress/aci-wordpress/main.bicep
  application-workloads/wordpress/aci-wordpress/metadata.json
Labels: bicep, bicep example migration

#11640 FIX-BESTPRACTICES: oms-active-directory-security-audit-solution-01
  demos/oms-active-directory-security-audit-solution/azuredeploy.json
  demos/oms-active-directory-security-audit-solution/metadata.json
Labels: best practices violations

#11629 FIX-BESTPRACTICES: backup-oms-monitoring
  demos/backup-oms-monitoring/azuredeploy.json
Labels: best practices violations

#11612 Updates from #11245
  quickstarts/microsoft.cache/redis-cache/README.md
  quickstarts/microsoft.cache/redis-cache/azuredeploy.json
  quickstarts/microsoft.cache/redis-cache/azuredeploy.parameters.json
  quickstarts/microsoft.cache/redis-cache/main.bicep
  quickstarts/microsoft.cache/redis-cache/metadata.json
  quickstarts/microsoft.cache/redis-cache/prereqs/prereq.azuredeploy.json
Labels: bicep

#11609 FIX-BESTPRACTICES: oms-all-deploy-01
  demos/oms-all-deploy/azuredeploy.json
  demos/oms-all-deploy/azuredeploy.parameters.json
  demos/oms-all-deploy/metadata.json
  demos/oms-all-deploy/nestedtemplates/omsAutomation.json
  demos/oms-all-deploy/nestedtemplates/omsRecoveryServices.json
  demos/oms-all-deploy/nestedtemplates/omsWorkspace.json
Labels: best practices violations

#11492 FIX-BESTPRACTICES: create-hpc-cluster
  demos/create-hpc-cluster/azuredeploy.json
  demos/create-hpc-cluster/headnode-rdma-disabled.json
  demos/create-hpc-cluster/headnode-rdma-enabled.json
  demos/create-hpc-cluster/linuxnode.json
  demos/create-hpc-cluster/mainTemplate.json
  demos/create-hpc-cluster/publicip-existing.json
  demos/create-hpc-cluster/publicip-new.json
  demos/create-hpc-cluster/vnet-with-dns-server.json
  demos/create-hpc-cluster/windowsnode-rdma-disabled.json
  demos/create-hpc-cluster/windowsnode-rdma-enabled.json
Labels: best practices violations

#11471 FIX-BESTPRACTICES: sap-2-tier-marketplace-image
  application-workloads/sap/sap-2-tier-marketplace-image/azuredeploy.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_D13_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_D14_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_DS11_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_DS13_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_DS14_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_DS2_v2_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/cs-server-Standard_GS5_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/db-server-Standard_GS2_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/db-server-Standard_GS3_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/db-server-Standard_GS4_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/db-server-Standard_GS5_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/disks.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/disks0.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/existingnsg.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/existingpip.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/existingvnet.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/existingvnetnsg.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-DB-HANA.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-DB-SQL.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-DB0.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-ERS-Linux.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-ERS-Windows.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-ERS0.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-SCS.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/lb-SCS0.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/loadbalancer.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/newnsg.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/newpip.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/newvnet.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/newvnetnsg.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/nic-config.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/os-disk-parts-md.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/os-disk-parts.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server-Standard_multiNIC_No.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server-md.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server2-noplan.json
  application-workloads/sap/sap-2-tier-marketplace-image/shared/server2.json
Labels: best practices violations

#11481 FIX-BESTPRACTICES: rds-deployment-full-ha
  demos/rds-deployment-full-ha/azuredeploy.json
  demos/rds-deployment-full-ha/metadata.json
Labels: best practices violations

#11641 FIX-BESTPRACTICES: oms-servicebus-solution-01
  demos/oms-servicebus-solution/azuredeploy.json
  demos/oms-servicebus-solution/metadata.json
  demos/oms-servicebus-solution/nestedtemplates/addMultipleSubscriptions.json
Labels: best practices violations

#11362 FIX-FAILED-BESTPRACTICES: machine-learning-compute-attach-hdi
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-hdi/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-compute-attach-hdi/prereqs/prereq.azuredeploy.json
Labels: best practices violations, metadata violations

#11637 FIX-BESTPRACTICES: cdn-customize
  quickstarts/microsoft.cdn/cdn-customize/azuredeploy.json
  quickstarts/microsoft.cdn/cdn-customize/azuredeploy.parameters.json
Labels: merge-conflict

#11526 FIX-BESTPRACTICES: sap-3-tier-marketplace-image-converged-md
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/azuredeploy.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/lb-DB-HANA.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/lb-DB-SQL.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/lb-DB0.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/lb-ERS-Linux.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/lb-ERS-Windows.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/lb-ERS0.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/lb-SCS.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/lb-SCS0.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/loadbalancer.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/newnsg.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/newpip.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/newvnetnsg.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/nic-config.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/os-disk-parts-md.json
  application-workloads/sap/sap-3-tier-marketplace-image-converged-md/shared/server-md.json
Labels: best practices violations

#11669 Latest eap-session-replication app
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/scripts/eap-session-replication.war
Labels: manual validation required

#11665 FIX-BESTPRACTICES: elasticsearch
  application-workloads/elastic/elasticsearch/azuredeploy.json
  application-workloads/elastic/elasticsearch/metadata.json
  application-workloads/elastic/elasticsearch/nestedtemplates/client-nodes-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/data-nodes-0disk-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/data-nodes-16disk-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/data-nodes-2disk-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/data-nodes-4disk-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/data-nodes-8disk-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/empty-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/jumpbox-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/kibana-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/marvel-nodes-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/master-nodes-resources.json
  application-workloads/elastic/elasticsearch/nestedtemplates/shared-resources.json
  application-workloads/elastic/elasticsearch/test/data-nodes-16disk-resources.json
Labels: best practices violations

#11674 FIX-BESTPRACTICES: api-management-logs-to-moesif-using-eventhub-webapp
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/azuredeploy.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/metadata.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/apis/policies.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/loggers.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.eventhub/namespaces.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.storage/storageaccounts.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/serverfarms.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/sites.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/sites/extensions.json
Labels: best practices violations

#11673 FIX-BESTPRACTICES: aci-linuxcontainer-volume-emptydir
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-emptydir/azuredeploy.json
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-emptydir/metadata.json
Labels: best practices violations

#11628 FIX-BESTPRACTICES: sqlvm-alwayson-cluster-01
  application-workloads/sql/sqlvm-alwayson-cluster/azuredeploy.json
  application-workloads/sql/sqlvm-alwayson-cluster/metadata.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/configuringAlwaysOn.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/configuringBackupADVM.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/creatingNICS.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/nic.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/preparingSqlServer.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/provisioningNetworkStorageAGSet.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/provisioningVM1.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/provisioningVM2.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/provisioningVM3.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/provisioningVM4.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/publicip-rdp.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/setupLBs.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/storageAccountVirtualNetworkPublicIP.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/vnet-new.json
  application-workloads/sql/sqlvm-alwayson-cluster/nested/vnet-with-dns-server.json
Labels: best practices violations

#11411 FIX-BESTPRACTICES: sccm-technicalpreview
  application-workloads/sccm/sccm-technicalpreview/azuredeploy.json
Labels: best practices violations

#11409 FIX-BESTPRACTICES: sccm-currentbranch
  application-workloads/sccm/sccm-currentbranch/azuredeploy.json
Labels: best practices violations

#11686 FIX-BESTPRACTICES: data-factory-chained-copy-activities
  quickstarts/microsoft.datafactory/data-factory-chained-copy-activities/azuredeploy.json
Labels: manual validation required

#11692 FIX-BESTPRACTICES: data-factory-v2-onprem-sql-to-blob-copy
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-v2-onprem-sql-to-blob-copy/prereqs/prereq.azuredeploy.json
Labels: manual validation required

#11685 Create Azure Bicep version.
  quickstarts/microsoft.web/function-app-storage-private-endpoints/README.md
  quickstarts/microsoft.web/function-app-storage-private-endpoints/azuredeploy.json
  quickstarts/microsoft.web/function-app-storage-private-endpoints/images/function-app-storage-private-endpoints.jpg
  quickstarts/microsoft.web/function-app-storage-private-endpoints/images/function-app-storage-privateendponts.png
  quickstarts/microsoft.web/function-app-storage-private-endpoints/main.bicep
  quickstarts/microsoft.web/function-app-storage-private-endpoints/metadata.json
Labels: bicep

#11698 FIX-TEMPLATE: elasticsearch-jmeter
  application-workloads/elastic/elasticsearch-jmeter/README.md
  application-workloads/elastic/elasticsearch-jmeter/azuredeploy.json
  application-workloads/elastic/elasticsearch-jmeter/metadata.json
  application-workloads/elastic/elasticsearch-jmeter/prereqs/prereq.azuredeploy.json
  application-workloads/elastic/elasticsearch-jmeter/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#11696 Update sample: Front Door (Standard/Premium) with Azure Storage static website
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/metadata.json
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/modules/storage-static-website.bicep
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/scripts/.gitattributes
  quickstarts/microsoft.network/front-door-standard-premium-storage-static-website/scripts/enable-storage-static-website.ps1
Labels: bicep

#11697 Update sample: Front Door (Standard/Premium) with API Management (external)
  quickstarts/microsoft.network/front-door-standard-premium-api-management-external/api-management-policies/.gitattributes
  quickstarts/microsoft.network/front-door-standard-premium-api-management-external/api-management-policies/global.xml
  quickstarts/microsoft.network/front-door-standard-premium-api-management-external/azuredeploy.json
  quickstarts/microsoft.network/front-door-standard-premium-api-management-external/main.bicep
  quickstarts/microsoft.network/front-door-standard-premium-api-management-external/metadata.json
  quickstarts/microsoft.network/front-door-standard-premium-api-management-external/modules/api-management.bicep
Labels: bicep

#11400 Migrate bicep example: 201/vm-domain-join
  quickstarts/microsoft.compute/vm-domain-join/README.md
  quickstarts/microsoft.compute/vm-domain-join/azuredeploy.json
  quickstarts/microsoft.compute/vm-domain-join/main.bicep
  quickstarts/microsoft.compute/vm-domain-join/metadata.json
Labels: bicep, bicep example migration

#11655 storage-blob-encryption-and-retention
  quickstarts/microsoft.storage/storage-blob-encryption-and-retention/README.md
  quickstarts/microsoft.storage/storage-blob-encryption-and-retention/azuredeploy.json
  quickstarts/microsoft.storage/storage-blob-encryption-and-retention/azuredeploy.parameters.json
  quickstarts/microsoft.storage/storage-blob-encryption-and-retention/main.bicep
  quickstarts/microsoft.storage/storage-blob-encryption-and-retention/metadata.json
Labels: bicep

#11736 Subalias
  managementgroup-deployments/create-subscription-resourcegroup/README.md
  managementgroup-deployments/create-subscription-resourcegroup/azuredeploy.json
  managementgroup-deployments/create-subscription-resourcegroup/main.bicep
  managementgroup-deployments/create-subscription-resourcegroup/metadata.json
  managementgroup-deployments/create-subscription-resourcegroup/modules/.create.resources.wrapper.bicep
  managementgroup-deployments/create-subscription-resourcegroup/modules/.microsoft.resources.resourcegroups.bicep
  managementgroup-deployments/create-subscription-resourcegroup/modules/.microsoft.storage.storageaccounts.bicep
  managementgroup-deployments/create-subscription-resourcegroup/modules/.microsoft.subscription.alias.bicep
Labels: best practices violations, bicep, manual validation required
