Repository Azure/azure-quickstart-templates, pull requests merged in 2021-05, with the labels that each got.

#9425 Change KeyVault to Key Vault
  101-api-management-key-vault-create/README.md
Labels: metadata

#9403 MOVE: 101-vm-linux-serial-output to quickstarts\microsoft.compute
  101-vm-linux-serial-output/README.md
  quickstarts/microsoft.compute/vm-linux-serial-output/README.md
  quickstarts/microsoft.compute/vm-linux-serial-output/azuredeploy.json
  quickstarts/microsoft.compute/vm-linux-serial-output/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-linux-serial-output/metadata.json
Labels: best practices

#9402 MOVE: 101-vm-linux-Jupyterhub to application-workloads\jupyter
  application-workloads/jupyter/vm-linux-Jupyterhub/GettingStarted.md
  application-workloads/jupyter/vm-linux-Jupyterhub/README.md
  application-workloads/jupyter/vm-linux-Jupyterhub/azuredeploy.json
  application-workloads/jupyter/vm-linux-Jupyterhub/azuredeploy.parameters.json
  application-workloads/jupyter/vm-linux-Jupyterhub/images/addUsers.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/addUsers2.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/addUsers3.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/addUsers4.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/azdeploy.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/azdeploy2.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/azgroup.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/azlogin.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/azportaldeploy3.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/aztemplate.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/aztemplate2.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/aztemplate3.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/httpsConfig1.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/httpsConfig2.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/httpsConfig3.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/installPackages.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/ipConnect.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/loginJupyter.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/loginJupyter2.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/off1.png
  application-workloads/jupyter/vm-linux-Jupyterhub/images/off2.png
  application-workloads/jupyter/vm-linux-Jupyterhub/metadata.json
  application-workloads/jupyter/vm-linux-Jupyterhub/scripts/bootstrap.py
  application-workloads/jupyter/vm-linux-Jupyterhub/scripts/install.sh
Labels: best practices

#9374 MOVE: 201-aci-linuxcontainer-volume-secret to quickstarts\microsoft.containerinstance
  201-aci-linuxcontainer-volume-secret/README.md
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-secret/README.md
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-secret/azuredeploy.json
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-secret/azuredeploy.parameters.json
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-secret/metadata.json
Labels: best practices

#9375 MOVE: 201-aci-linuxcontainer-volume-gitrepo to quickstarts\microsoft.containerinstance
  201-aci-linuxcontainer-volume-gitrepo/README.md
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-gitrepo/README.md
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-gitrepo/azuredeploy.json
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-gitrepo/azuredeploy.parameters.json
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-gitrepo/metadata.json
Labels: best practices

#9382 MOVE: 101-sql-managed-instance-azure-environment to quickstarts\microsoft.sql
  quickstarts/microsoft.sql/sql-managed-instance-azure-environment/README.md
  quickstarts/microsoft.sql/sql-managed-instance-azure-environment/azuredeploy.json
  quickstarts/microsoft.sql/sql-managed-instance-azure-environment/azuredeploy.parameters.json
  quickstarts/microsoft.sql/sql-managed-instance-azure-environment/metadata.json
Labels: best practices

#9376 MOVE: 201-aci-linuxcontainer-volume-emptydir to quickstarts\microsoft.containerinstance
  201-aci-linuxcontainer-volume-emptydir/README.md
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-emptydir/README.md
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-emptydir/azuredeploy.json
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-emptydir/azuredeploy.parameters.json
  quickstarts/microsoft.containerinstance/aci-linuxcontainer-volume-emptydir/metadata.json
Labels: best practices

#9370 MOVE: 201-aci-udp to quickstarts\microsoft.containerinstance
  201-aci-udp/README.md
  201-aci-udp/metadata.json
  quickstarts/microsoft.containerinstance/aci-udp/README.md
  quickstarts/microsoft.containerinstance/aci-udp/azuredeploy.json
  quickstarts/microsoft.containerinstance/aci-udp/azuredeploy.parameters.json
  quickstarts/microsoft.containerinstance/aci-udp/metadata.json
Labels: best practices

#9350 MOVE: 201-application-gateway-path-override to quickstarts\microsoft.network
  201-application-gateway-path-override/README.md
  quickstarts/microsoft.network/application-gateway-path-override/README.md
  quickstarts/microsoft.network/application-gateway-path-override/azuredeploy.json
  quickstarts/microsoft.network/application-gateway-path-override/azuredeploy.parameters.json
  quickstarts/microsoft.network/application-gateway-path-override/metadata.json
Labels: best practices

#9349 MOVE: 201-application-gateway-probe to quickstarts\microsoft.network
  201-application-gateway-probe/README.md
  quickstarts/microsoft.network/application-gateway-probe/README.md
  quickstarts/microsoft.network/application-gateway-probe/azuredeploy.json
  quickstarts/microsoft.network/application-gateway-probe/azuredeploy.parameters.json
  quickstarts/microsoft.network/application-gateway-probe/metadata.json
Labels: best practices

#9348 MOVE: 201-application-gateway-url-path-based-routing to quickstarts\microsoft.network
  201-application-gateway-url-path-based-routing/README.md
  quickstarts/microsoft.network/application-gateway-url-path-based-routing/README.md
  quickstarts/microsoft.network/application-gateway-url-path-based-routing/azuredeploy.json
  quickstarts/microsoft.network/application-gateway-url-path-based-routing/azuredeploy.parameters.json
  quickstarts/microsoft.network/application-gateway-url-path-based-routing/metadata.json
Labels: best practices

#9347 MOVE: 201-application-gateway-webapps to quickstarts\microsoft.network
  201-application-gateway-webapps/README.md
  quickstarts/microsoft.network/application-gateway-webapps/README.md
  quickstarts/microsoft.network/application-gateway-webapps/azuredeploy.json
  quickstarts/microsoft.network/application-gateway-webapps/azuredeploy.parameters.json
  quickstarts/microsoft.network/application-gateway-webapps/metadata.json
Labels: best practices

#9346 MOVE: 201-azure-relay-create-all-resources to quickstarts\microsoft.relay
  201-azure-relay-create-all-resources/README.md
  quickstarts/microsoft.relay/azure-relay-create-all-resources/README.md
  quickstarts/microsoft.relay/azure-relay-create-all-resources/azuredeploy.json
  quickstarts/microsoft.relay/azure-relay-create-all-resources/azuredeploy.parameters.json
  quickstarts/microsoft.relay/azure-relay-create-all-resources/metadata.json
Labels: best practices

#9345 MOVE: 201-azure-relay-create-hybridconnection to quickstarts\microsoft.relay
  201-azure-relay-create-hybridconnection/README.md
  quickstarts/microsoft.relay/azure-relay-create-hybridconnection/README.md
  quickstarts/microsoft.relay/azure-relay-create-hybridconnection/azuredeploy.json
  quickstarts/microsoft.relay/azure-relay-create-hybridconnection/azuredeploy.parameters.json
  quickstarts/microsoft.relay/azure-relay-create-hybridconnection/metadata.json
Labels: best practices

#9344 MOVE: 201-azure-relay-create-wcfrelay to quickstarts\microsoft.relay
  201-azure-relay-create-wcfrelay/README.md
  quickstarts/microsoft.relay/azure-relay-create-wcfrelay/README.md
  quickstarts/microsoft.relay/azure-relay-create-wcfrelay/azuredeploy.json
  quickstarts/microsoft.relay/azure-relay-create-wcfrelay/azuredeploy.parameters.json
  quickstarts/microsoft.relay/azure-relay-create-wcfrelay/metadata.json
Labels: best practices

#9342 MOVE: 201-cosmosdb-advanced-threat-protection-create-account to quickstarts\microsoft.documentdb
  201-cosmosdb-advanced-threat-protection-create-account/README.md
  201-cosmosdb-advanced-threat-protection-create-account/metadata.json
  quickstarts/microsoft.documentdb/cosmosdb-advanced-threat-protection-create-account/README.md
  quickstarts/microsoft.documentdb/cosmosdb-advanced-threat-protection-create-account/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-advanced-threat-protection-create-account/azuredeploy.parameters.json
  quickstarts/microsoft.documentdb/cosmosdb-advanced-threat-protection-create-account/metadata.json
Labels: best practices

#9333 MOVE: 201-front-door-managed-waf-ruleset to quickstarts\microsoft.network
  201-front-door-managed-waf-ruleset/README.md
  201-front-door-managed-waf-ruleset/metadata.json
  quickstarts/microsoft.network/front-door-managed-waf-ruleset/README.md
  quickstarts/microsoft.network/front-door-managed-waf-ruleset/azuredeploy.json
  quickstarts/microsoft.network/front-door-managed-waf-ruleset/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-managed-waf-ruleset/metadata.json
Labels: best practices

#9299 MOVE: 201-sqlmi-new-vnet-w-point-to-site-vpn to quickstarts\microsoft.sql
  quickstarts/microsoft.sql/sqlmi-new-vnet-w-point-to-site-vpn/README.md
  quickstarts/microsoft.sql/sqlmi-new-vnet-w-point-to-site-vpn/azuredeploy.json
  quickstarts/microsoft.sql/sqlmi-new-vnet-w-point-to-site-vpn/azuredeploy.parameters.json
  quickstarts/microsoft.sql/sqlmi-new-vnet-w-point-to-site-vpn/metadata.json
  quickstarts/microsoft.sql/sqlmi-new-vnet-w-point-to-site-vpn/scripts/deploy.ps1
Labels: best practices

#9481 MOVE: 201-vmss-linux-customimage-autoscale to quickstarts\Microsoft.Compute
  quickstarts/microsoft.compute/vmss-linux-customimage-autoscale/README.md
  quickstarts/microsoft.compute/vmss-linux-customimage-autoscale/app/package.tar.gz
  quickstarts/microsoft.compute/vmss-linux-customimage-autoscale/azuredeploy.json
  quickstarts/microsoft.compute/vmss-linux-customimage-autoscale/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vmss-linux-customimage-autoscale/metadata.json
  quickstarts/microsoft.compute/vmss-linux-customimage-autoscale/scripts/updateapp.sh
Labels: best practices

#9378 MOVE: 201-2-vms-loadbalancer-natrules to quickstarts\microsoft.compute
  201-2-vms-loadbalancer-natrules/README.md
  quickstarts/microsoft.compute/2-vms-loadbalancer-natrules/README.md
  quickstarts/microsoft.compute/2-vms-loadbalancer-natrules/azuredeploy.json
  quickstarts/microsoft.compute/2-vms-loadbalancer-natrules/azuredeploy.parameters.json
  quickstarts/microsoft.compute/2-vms-loadbalancer-natrules/metadata.json
Labels: best practices

#9115 FIX-TEMPLATE: 101-vm-sql-existing-autopatching-update
  101-vm-sql-existing-autopatching-update/README.md
  101-vm-sql-existing-autopatching-update/azuredeploy.json
  101-vm-sql-existing-autopatching-update/metadata.json
  101-vm-sql-existing-autopatching-update/prereqs/.settings.json
  101-vm-sql-existing-autopatching-update/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices

#9162 FIX-TEMPLATE: elasticsearch-vmss
  elasticsearch-vmss/azuredeploy.json
  elasticsearch-vmss/install-elasticsearch.sh
Labels: best practices, metadata, readme

#9542 MOVE: docker-portainer-traefik-windows-vm to application-workloads\traefik
  application-workloads/traefik/docker-portainer-traefik-windows-vm/README.md
  application-workloads/traefik/docker-portainer-traefik-windows-vm/azuredeploy.json
  application-workloads/traefik/docker-portainer-traefik-windows-vm/azuredeploy.parameters.json
  application-workloads/traefik/docker-portainer-traefik-windows-vm/configs/docker-compose.yml.template
  application-workloads/traefik/docker-portainer-traefik-windows-vm/configs/sshd_config_wpwd
  application-workloads/traefik/docker-portainer-traefik-windows-vm/createUiDefinition.json
  application-workloads/traefik/docker-portainer-traefik-windows-vm/metadata.json
  application-workloads/traefik/docker-portainer-traefik-windows-vm/setup.ps1
  docker-portainer-traefik-windows-vm/README.md
Labels: best practices

#9541 MOVE: diskraid-ubuntu-vm to demos
  demos/diskraid-ubuntu-vm/README.md
  demos/diskraid-ubuntu-vm/azuredeploy.json
  demos/diskraid-ubuntu-vm/azuredeploy.parameters.json
  demos/diskraid-ubuntu-vm/metadata.json
  diskraid-ubuntu-vm/README.md
Labels: best practices

#9536 MOVE: azure-sql-managed-instance to demos
  azure-sql-managed-instance/README.md
  azure-sql-managed-instance/metadata.json
  demos/azure-sql-managed-instance/README.md
  demos/azure-sql-managed-instance/azuredeploy.json
  demos/azure-sql-managed-instance/azuredeploy.parameters.json
  demos/azure-sql-managed-instance/metadata.json
  demos/azure-sql-managed-instance/nestedtemplates/vnet.json
Labels: best practices

#9528 MOVE: 301-web-app-diagnostics-logs-blob-container to quickstarts\microsoft.web
  301-web-app-diagnostics-logs-blob-container/README.md
  301-web-app-diagnostics-logs-blob-container/metadata.json
  quickstarts/microsoft.web/web-app-diagnostics-logs-blob-container/README.md
  quickstarts/microsoft.web/web-app-diagnostics-logs-blob-container/azuredeploy.json
  quickstarts/microsoft.web/web-app-diagnostics-logs-blob-container/azuredeploy.parameters.json
  quickstarts/microsoft.web/web-app-diagnostics-logs-blob-container/metadata.json
Labels: best practices

#9527 MOVE: 301-vm-32-data-disks-high-iops to demos
  301-vm-32-data-disks-high-iops/README.md
  demos/vm-32-data-disks-high-iops/DSC/StoragePool.ps1
  demos/vm-32-data-disks-high-iops/DSC/StoragePool.zip
  demos/vm-32-data-disks-high-iops/README.md
  demos/vm-32-data-disks-high-iops/azuredeploy.json
  demos/vm-32-data-disks-high-iops/azuredeploy.parameters.json
  demos/vm-32-data-disks-high-iops/metadata.json
Labels: best practices

#9526 MOVE: 301-servicebus-create-authrule-namespace-and-queue to quickstarts\microsoft.servicebus
  301-servicebus-create-authrule-namespace-and-queue/README.md
  quickstarts/microsoft.servicebus/servicebus-create-authrule-namespace-and-queue/README.md
  quickstarts/microsoft.servicebus/servicebus-create-authrule-namespace-and-queue/azuredeploy.json
  quickstarts/microsoft.servicebus/servicebus-create-authrule-namespace-and-queue/azuredeploy.parameters.json
  quickstarts/microsoft.servicebus/servicebus-create-authrule-namespace-and-queue/metadata.json
Labels: best practices

#9525 MOVE: 301-nested-vms-in-virtual-network to demos
  demos/nested-vms-in-virtual-network/README.md
  demos/nested-vms-in-virtual-network/azuredeploy.json
  demos/nested-vms-in-virtual-network/azuredeploy.parameters.json
  demos/nested-vms-in-virtual-network/dsc/dscinstallwindowsfeatures.zip
  demos/nested-vms-in-virtual-network/hvhostsetup.ps1
  demos/nested-vms-in-virtual-network/metadata.json
Labels: best practices

#9524 MOVE: 301-multi-vmss-linux to quickstarts\microsoft.compute
  301-multi-vmss-linux/README.md
  quickstarts/microsoft.compute/multi-vmss-linux/README.md
  quickstarts/microsoft.compute/multi-vmss-linux/azuredeploy.json
  quickstarts/microsoft.compute/multi-vmss-linux/azuredeploy.parameters.json
  quickstarts/microsoft.compute/multi-vmss-linux/metadata.json
  quickstarts/microsoft.compute/multi-vmss-linux/nestedtemplates/base.json
Labels: best practices

#9521 MOVE: 301-eventHub-create-authrule-namespace-and-eventHub to quickstarts\microsoft.eventhub
  301-eventHub-create-authrule-namespace-and-eventHub/README.md
  quickstarts/microsoft.eventhub/eventhub-create-authrule-namespace-and-eventhub/README.md
  quickstarts/microsoft.eventhub/eventhub-create-authrule-namespace-and-eventhub/azuredeploy.json
  quickstarts/microsoft.eventhub/eventhub-create-authrule-namespace-and-eventhub/azuredeploy.parameters.json
  quickstarts/microsoft.eventhub/eventhub-create-authrule-namespace-and-eventhub/metadata.json
Labels: best practices

#9519 MOVE: 301-azure-relay-create-authrule-namespace-and-wcfrelay to quickstarts\microsoft.relay
  301-azure-relay-create-authrule-namespace-and-wcfrelay/README.md
  quickstarts/microsoft.relay/azure-relay-create-authrule-namespace-and-wcfrelay/README.md
  quickstarts/microsoft.relay/azure-relay-create-authrule-namespace-and-wcfrelay/azuredeploy.json
  quickstarts/microsoft.relay/azure-relay-create-authrule-namespace-and-wcfrelay/azuredeploy.parameters.json
  quickstarts/microsoft.relay/azure-relay-create-authrule-namespace-and-wcfrelay/metadata.json
Labels: best practices

#9518 MOVE: 301-azure-relay-create-authrule-namespace-and-hybridconnection to quickstarts\microsoft.relay
  301-azure-relay-create-authrule-namespace-and-hybridconnection/README.md
  quickstarts/microsoft.relay/azure-relay-create-authrule-namespace-and-hybridconnection/README.md
  quickstarts/microsoft.relay/azure-relay-create-authrule-namespace-and-hybridconnection/azuredeploy.json
  quickstarts/microsoft.relay/azure-relay-create-authrule-namespace-and-hybridconnection/azuredeploy.parameters.json
  quickstarts/microsoft.relay/azure-relay-create-authrule-namespace-and-hybridconnection/metadata.json
Labels: best practices

#9488 MOVE: 201-vmss-windows-autoscale to quickstarts\microsoft.compute
  201-vmss-windows-autoscale/README.md
  quickstarts/microsoft.compute/vmss-windows-autoscale/README.md
  quickstarts/microsoft.compute/vmss-windows-autoscale/azuredeploy.json
  quickstarts/microsoft.compute/vmss-windows-autoscale/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vmss-windows-autoscale/metadata.json
Labels: best practices

#9487 MOVE: 201-vmss-windows-app-gateway to quickstarts\microsoft.compute
  201-vmss-windows-app-gateway/README.md
  quickstarts/microsoft.compute/vmss-windows-app-gateway/README.md
  quickstarts/microsoft.compute/vmss-windows-app-gateway/azuredeploy.json
  quickstarts/microsoft.compute/vmss-windows-app-gateway/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vmss-windows-app-gateway/metadata.json
Labels: best practices

#9486 MOVE: 201-vmss-ubuntu-autoscale to quickstarts\microsoft.compute
  201-vmss-ubuntu-autoscale/README.md
  quickstarts/microsoft.compute/vmss-ubuntu-autoscale/README.md
  quickstarts/microsoft.compute/vmss-ubuntu-autoscale/azuredeploy.json
  quickstarts/microsoft.compute/vmss-ubuntu-autoscale/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vmss-ubuntu-autoscale/metadata.json
Labels: best practices

#9477 MOVE: 201-vmss-automatic-repairs-slb-health-probe to quickstarts\Microsoft.Compute
  201-vmss-automatic-repairs-slb-health-probe/README.md
  quickstarts/microsoft.compute/vmss-automatic-repairs-slb-health-probe/README.md
  quickstarts/microsoft.compute/vmss-automatic-repairs-slb-health-probe/azuredeploy.json
  quickstarts/microsoft.compute/vmss-automatic-repairs-slb-health-probe/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vmss-automatic-repairs-slb-health-probe/install_apache.sh
  quickstarts/microsoft.compute/vmss-automatic-repairs-slb-health-probe/metadata.json
Labels: best practices

#9474 MOVE: 201-vm-new-or-existing-conditions to quickstarts\microsoft.compute
  201-vm-new-or-existing-conditions/README.md
  quickstarts/microsoft.compute/vm-new-or-existing-conditions/README.md
  quickstarts/microsoft.compute/vm-new-or-existing-conditions/azuredeploy.json
  quickstarts/microsoft.compute/vm-new-or-existing-conditions/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-new-or-existing-conditions/metadata.json
Labels: best practices

#9472 MOVE: 201-vm-msi-storage to quickstarts\Microsoft.Compute
  201-vm-msi-storage/README.md
  quickstarts/microsoft.compute/vm-msi-storage/README.md
  quickstarts/microsoft.compute/vm-msi-storage/azuredeploy.json
  quickstarts/microsoft.compute/vm-msi-storage/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-msi-storage/metadata.json
  quickstarts/microsoft.compute/vm-msi-storage/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.compute/vm-msi-storage/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices

#9469 MOVE: 201-vm-linux-jupyterhub to quickstarts\Microsoft.Compute
  quickstarts/microsoft.compute/vm-linux-jupyterhub/GettingStarted.md
  quickstarts/microsoft.compute/vm-linux-jupyterhub/README.md
  quickstarts/microsoft.compute/vm-linux-jupyterhub/azuredeploy.json
  quickstarts/microsoft.compute/vm-linux-jupyterhub/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/Arch.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/TLJHPortal.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/addUsers.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/addUsers2.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/addUsers3.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/addUsers4.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/azdeploy.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/azdeploy2.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/azgroup.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/azlogin.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/azportaldeploy3.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/aztemplate.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/aztemplate2.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/aztemplate3.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/httpsConfig1.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/httpsConfig2.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/httpsConfig3.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/installPackages.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/ipConnect.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/loginJupyter.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/loginJupyter2.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/off1.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/images/off2.png
  quickstarts/microsoft.compute/vm-linux-jupyterhub/metadata.json
  quickstarts/microsoft.compute/vm-linux-jupyterhub/scripts/bootstrap.py
  quickstarts/microsoft.compute/vm-linux-jupyterhub/scripts/install.sh
Labels: best practices

#9398 MOVE: 101-Telegraf-InfluxDB-Grafana to application-workloads\grafana
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/README.md
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/azuredeploy.json
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/azuredeploy.parameters.json
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/metadata.json
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles.zip
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles/ansible/docker_install.yml
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles/ansible/grafanacfg.input.jk2
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles/ansible/telegraf.conf.jk2
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles/config.monitoring
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles/dashboards/DockerMetricsperContainer.json
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles/dashboards/TelegrafHostMetrics.json
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles/docker-compose.yml
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles/env.influxdb
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/Configfiles/telegraf.conf
  application-workloads/grafana/Telegraf-InfluxDB-Grafana/scripts/tigscript.sh
Labels: best practices

#9543 FIX-TEMPLATE: lap-neo4j-ubuntu
  lap-neo4j-ubuntu/azuredeploy.json
  lap-neo4j-ubuntu/install-lap.sh
  lap-neo4j-ubuntu/install-neo4j.sh
  lap-neo4j-ubuntu/metadata.json
Labels: best practices, readme

#9013 FIX-TEMPLATE: 201-encrypt-running-vmss-linux
  201-encrypt-running-vmss-linux/azuredeploy.json
  201-encrypt-running-vmss-linux/prereqs/.settings.json
  201-encrypt-running-vmss-linux/prereqs/prereq.azuredeploy.json
Labels: best practices, metadata, readme

#9038 FIX-TEMPLATE: 201-hdinsight-datalake-store-azure-storage
  201-hdinsight-datalake-store-azure-storage/azuredeploy.json
  201-hdinsight-datalake-store-azure-storage/azuredeploy.parameters.json
  201-hdinsight-datalake-store-azure-storage/metadata.json
Labels: best practices, metadata

#9408 FIX-TEMPLATE: 201-decrypt-vmss-windows
  201-decrypt-vmss-windows/azuredeploy.parameters.json
  201-decrypt-vmss-windows/metadata.json
  201-decrypt-vmss-windows/prereqs/.settings.json
  201-decrypt-vmss-windows/prereqs/prereq.azuredeploy.json
  201-decrypt-vmss-windows/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices, readme

#9039 FIX-TEMPLATE: 201-front-door-api-management
  201-front-door-api-management/azuredeploy.json
Labels: best practices, metadata

#9041 FIX-TEMPLATE: 201-expressroute-circuit-public-private-peering
  201-expressroute-circuit-public-private-peering/azuredeploy.json
  201-expressroute-circuit-public-private-peering/azuredeploy.parameters.json
Labels: best practices, metadata, readme

#9042 FIX-TEMPLATE: 201-logic-app-b2b-disaster-recovery-replication
  201-logic-app-b2b-disaster-recovery-replication/azuredeploy.json
  201-logic-app-b2b-disaster-recovery-replication/azuredeploy.parameters.json
Labels: best practices, metadata, readme

#9043 FIX-TEMPLATE: 201-encrypt-running-linux-vm
  201-encrypt-running-linux-vm/azuredeploy.json
  201-encrypt-running-linux-vm/azuredeploy.parameters.json
  201-encrypt-running-linux-vm/prereqs/.settings.json
  201-encrypt-running-linux-vm/prereqs/prereq.azuredeploy.json
  201-encrypt-running-linux-vm/prereqs/prereq.azuredeploy.parameters.json
  201-encrypt-running-linux-vm/updatevm-kek.json
  201-encrypt-running-linux-vm/updatevm-nokek.json
Labels: best practices, metadata

#9407 FIX-TEMPLATE: 201-decrypt-vmss-linux
  201-decrypt-vmss-linux/azuredeploy.parameters.json
  201-decrypt-vmss-linux/metadata.json
  201-decrypt-vmss-linux/prereqs/.settings.json
  201-decrypt-vmss-linux/prereqs/prereq.azuredeploy.json
  201-decrypt-vmss-linux/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices, readme

#9309 FIX-TEMPLATE: 201-decrypt-running-linux-vm-without-aad
  201-decrypt-running-linux-vm-without-aad/metadata.json
  201-decrypt-running-linux-vm-without-aad/prereqs/.settings.json
Labels: best practices, readme

#9308 FIX-TEMPLATE: hdinsight-linux-run-script-action
  hdinsight-linux-run-script-action/azuredeploy.json
  hdinsight-linux-run-script-action/azuredeploy.parameters.json
Labels: best practices, metadata, readme

#9168 FIX-TEMPLATE: hdinsight-genomics-adam
  hdinsight-genomics-adam/azuredeploy.json
Labels: best practices, metadata, readme

#9166 FIX-TEMPLATE: guacamole-rdp-vnc-gateway-existing-vnet
  guacamole-rdp-vnc-gateway-existing-vnet/azuredeploy.json
  guacamole-rdp-vnc-gateway-existing-vnet/prereqs/.settings.json
Labels: best practices, metadata, readme

#9136 FIX-TEMPLATE: 201-vm-msi
  201-vm-msi/azuredeploy.json
  201-vm-msi/scripts/install-and-run-cli-2.sh
Labels: metadata, readme

#9068 FIX-TEMPLATE: 201-rbac-builtinrole-multipleVMs
  201-rbac-builtinrole-multipleVMs/azuredeploy.json
  201-rbac-builtinrole-multipleVMs/azuredeploy.parameters.json
  201-rbac-builtinrole-multipleVMs/prereqs/.settings.json
  201-rbac-builtinrole-multipleVMs/prereqs/prereq.azuredeploy.json
  201-rbac-builtinrole-multipleVMs/prereqs/prereq.azuredeploy.parameters.json
Labels: metadata, readme

#9102 FIX-TEMPLATE: kafka-ubuntu-multidisks
  kafka-ubuntu-multidisks/azuredeploy.json
  kafka-ubuntu-multidisks/kafka-cluster-install.sh
Labels: best practices, metadata, readme

#9104 FIX-TEMPLATE: 201-redis-premium-cluster-diagnostics
  201-redis-premium-cluster-diagnostics/azuredeploy.json
  201-redis-premium-cluster-diagnostics/azuredeploy.parameters.json
  201-redis-premium-cluster-diagnostics/prereqs/.settings.json
  201-redis-premium-cluster-diagnostics/prereqs/prereq.azuredeploy.json
  201-redis-premium-cluster-diagnostics/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices, metadata, readme

#9108 FIX-TEMPLATE: 201-traffic-manager-vm
  201-traffic-manager-vm/azuredeploy.json
Labels: metadata

#9545 Refactor groestlcoin script
  application-workloads/blockchain/blockchain/azuredeploy.json
  application-workloads/blockchain/blockchain/scripts/groestlcoin.sh
Labels: merge-conflict

#9587 MOVE: 201-vnet-2subnets-service-endpoints-storage-integration to quickstarts\Microsoft.Network
  201-vnet-2subnets-service-endpoints-storage-integration/README.md
  quickstarts/microsoft.network/vnet-2subnets-service-endpoints-storage-integration/README.md
  quickstarts/microsoft.network/vnet-2subnets-service-endpoints-storage-integration/azuredeploy.json
  quickstarts/microsoft.network/vnet-2subnets-service-endpoints-storage-integration/azuredeploy.parameters.json
  quickstarts/microsoft.network/vnet-2subnets-service-endpoints-storage-integration/metadata.json
Labels: best practices, best practices (bicep)

#9586 MOVE: 201-vm-winrm-keyvault-windows to demos
  201-vm-winrm-keyvault-windows/README.md
  demos/vm-winrm-keyvault-windows/README.md
  demos/vm-winrm-keyvault-windows/azuredeploy.json
  demos/vm-winrm-keyvault-windows/azuredeploy.parameters.json
  demos/vm-winrm-keyvault-windows/metadata.json
Labels: best practices, best practices (bicep)

#9577 MOVE: mysql-mha-haproxy-ubuntu to application-workloads\mysql
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/README.md
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/azuredeploy.json
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/azuredeploy.parameters.json
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/metadata.json
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/nested/haproxy-resources.json
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/nested/master-resources.json
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/nested/shared-resources.json
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/nested/slave01-resources.json
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/nested/slave02-resources.json
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/scripts/haproxy.sh
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/scripts/master.sh
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/scripts/slave01.sh
  application-workloads/mysql/mysql-mha-haproxy-ubuntu/scripts/slave02.sh
Labels: best practices

#9574 MOVE: 201-vmss-ubuntu-app-gateway to quickstarts\microsoft.compute
  201-vmss-ubuntu-app-gateway/README.md
  quickstarts/microsoft.compute/vmss-ubuntu-app-gateway/README.md
  quickstarts/microsoft.compute/vmss-ubuntu-app-gateway/azuredeploy.json
  quickstarts/microsoft.compute/vmss-ubuntu-app-gateway/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vmss-ubuntu-app-gateway/metadata.json
Labels: best practices

#9566 MOVE: minio-azure-gateway to application-workloads\minio
  application-workloads/minio/minio-azure-gateway/README.md
  application-workloads/minio/minio-azure-gateway/azuredeploy.json
  application-workloads/minio/minio-azure-gateway/azuredeploy.parameters.json
  application-workloads/minio/minio-azure-gateway/azuredeploy.parameters.us.json
  application-workloads/minio/minio-azure-gateway/metadata.json
  application-workloads/minio/minio-azure-gateway/scripts/minio.sh
  application-workloads/minio/minio-azure-gateway/scripts/values.yaml
Labels: best practices

#9539 MOVE: cloudlens-suricata-ubuntu to application-workloads\cloudlens
  application-workloads/cloudlens/cloudlens-suricata-ubuntu/README.md
  application-workloads/cloudlens/cloudlens-suricata-ubuntu/azuredeploy.json
  application-workloads/cloudlens/cloudlens-suricata-ubuntu/azuredeploy.parameters.json
  application-workloads/cloudlens/cloudlens-suricata-ubuntu/images/architecture.png
  application-workloads/cloudlens/cloudlens-suricata-ubuntu/metadata.json
  application-workloads/cloudlens/cloudlens-suricata-ubuntu/scripts/setup-suricata.sh
  application-workloads/cloudlens/cloudlens-suricata-ubuntu/scripts/setup-tap.sh
Labels: best practices

#9538 MOVE: cloudlens-moloch-ubuntu to application-workloads\cloudlens
  application-workloads/cloudlens/cloudlens-moloch-ubuntu/README.md
  application-workloads/cloudlens/cloudlens-moloch-ubuntu/azuredeploy.json
  application-workloads/cloudlens/cloudlens-moloch-ubuntu/azuredeploy.parameters.json
  application-workloads/cloudlens/cloudlens-moloch-ubuntu/images/architecture.png
  application-workloads/cloudlens/cloudlens-moloch-ubuntu/metadata.json
  application-workloads/cloudlens/cloudlens-moloch-ubuntu/scripts/setup-moloch.sh
  application-workloads/cloudlens/cloudlens-moloch-ubuntu/scripts/setup-tap.sh
Labels: best practices

#9535 MOVE: azure-resource-optimization-toolkit to demos
  demos/azure-resource-optimization-toolkit/README.md
  demos/azure-resource-optimization-toolkit/azuredeploy.json
  demos/azure-resource-optimization-toolkit/azuredeploy.parameters.json
  demos/azure-resource-optimization-toolkit/azuredeploy.parameters.us.json
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image10.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image11.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image12.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image13a.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image14a.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image15.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image16.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image17.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image18.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image19.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image20.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image21.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image22.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image23.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image24.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image25.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image3.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image4.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image5.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image6.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image7.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image8.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/image9.png
  demos/azure-resource-optimization-toolkit/images/AROToolkit/validateRunAs.png
  demos/azure-resource-optimization-toolkit/images/git1.png
  demos/azure-resource-optimization-toolkit/images/git2.png
  demos/azure-resource-optimization-toolkit/images/git3.png
  demos/azure-resource-optimization-toolkit/images/namingConvention.png
  demos/azure-resource-optimization-toolkit/images/nestedTemplateDesign.png
  demos/azure-resource-optimization-toolkit/metadata.json
  demos/azure-resource-optimization-toolkit/scripts/AROToolkit_AutoUpdate.ps1
  demos/azure-resource-optimization-toolkit/scripts/AutoUpdateWorker.ps1
  demos/azure-resource-optimization-toolkit/scripts/Bootstrap_Main.ps1
  demos/azure-resource-optimization-toolkit/scripts/DeleteRG/DeleteResourceGroup_Child.ps1
  demos/azure-resource-optimization-toolkit/scripts/DeleteRG/DeleteResourceGroups_Parent.ps1
  demos/azure-resource-optimization-toolkit/scripts/DisableAllOptimizations.ps1
  demos/azure-resource-optimization-toolkit/scripts/ScheduleSnooze/ScheduledSnooze_Child.ps1
  demos/azure-resource-optimization-toolkit/scripts/ScheduleSnooze/ScheduledSnooze_Parent.ps1
  demos/azure-resource-optimization-toolkit/scripts/SequencedSnooze/SequencedSnooze_Parent.ps1
  demos/azure-resource-optimization-toolkit/scripts/Snooze/AutoSnooze_CreateAlert_Child.ps1
  demos/azure-resource-optimization-toolkit/scripts/Snooze/AutoSnooze_CreateAlert_Parent.ps1
  demos/azure-resource-optimization-toolkit/scripts/Snooze/AutoSnooze_Disable.ps1
  demos/azure-resource-optimization-toolkit/scripts/Snooze/AutoSnooze_StopVM_Child.ps1
Labels: best practices, best practices (bicep)

#9609 Groestlcoin: Fix strip and move paths
  application-workloads/blockchain/blockchain/scripts/groestlcoin.sh
Labels: best practices (bicep)

#9016 FIX-TEMPLATE: 201-encrypt-running-windows-vm
  201-encrypt-running-windows-vm/azuredeploy.json
  201-encrypt-running-windows-vm/azuredeploy.parameters.json
  201-encrypt-running-windows-vm/metadata.json
  201-encrypt-running-windows-vm/prereqs/.settings.json
  201-encrypt-running-windows-vm/prereqs/prereq.azuredeploy.json
  201-encrypt-running-windows-vm/prereqs/prereq.azuredeploy.parameters.json
  201-encrypt-running-windows-vm/updatevm-kek.json
  201-encrypt-running-windows-vm/updatevm-nokek.json
Labels: best practices, metadata

#9019 FIX-TEMPLATE: 201-encrypt-vmss-windows-jumpbox
  201-encrypt-vmss-windows-jumpbox/azuredeploy.json
  201-encrypt-vmss-windows-jumpbox/azuredeploy.parameters.json
Labels: best practices, metadata, readme

#9022 FIX-TEMPLATE: 201-encrypt-running-vmss-windows
  201-encrypt-running-vmss-windows/azuredeploy.json
  201-encrypt-running-vmss-windows/azuredeploy.parameters.json
  201-encrypt-running-vmss-windows/prereqs/.settings.json
  201-encrypt-running-vmss-windows/prereqs/prereq.azuredeploy.json
Labels: best practices, metadata, readme

#9036 FIX-TEMPLATE: 201-list-storage-keys-windows-vm
  201-list-storage-keys-windows-vm/Copy-FileFromAzure.ps1
  201-list-storage-keys-windows-vm/FileToBeCopied.txt
  201-list-storage-keys-windows-vm/azuredeploy.json
  201-list-storage-keys-windows-vm/azuredeploy.parameters.json
  201-list-storage-keys-windows-vm/getprocess.ps1
  201-list-storage-keys-windows-vm/prereqs/.settings.json
  201-list-storage-keys-windows-vm/prereqs/prereq.azuredeploy.json
  201-list-storage-keys-windows-vm/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices, metadata, readme

#9065 FIX-TEMPLATE: 201-oms-extension-ubuntu-vm
  201-oms-extension-ubuntu-vm/azuredeploy.json
  201-oms-extension-ubuntu-vm/azuredeploy.parameters.json
  201-oms-extension-ubuntu-vm/prereqs/.settings.json
  201-oms-extension-ubuntu-vm/prereqs/prereq.azuredeploy.json
  201-oms-extension-ubuntu-vm/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices, metadata, readme

#9066 FIX-TEMPLATE: 201-oms-extension-windows-vm
  201-oms-extension-windows-vm/azuredeploy.json
  201-oms-extension-windows-vm/azuredeploy.parameters.json
  201-oms-extension-windows-vm/prereqs/.settings.json
  201-oms-extension-windows-vm/prereqs/prereq.azuredeploy.json
  201-oms-extension-windows-vm/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices, metadata, readme

#9067 FIX-TEMPLATE: 201-private-aks-cluster
  201-private-aks-cluster/azuredeploy.json
Labels: metadata

#9145 FIX-TEMPLATE: 201-vm-sql-full-autopatching
  201-vm-sql-full-autopatching/azuredeploy.json
  201-vm-sql-full-autopatching/azuredeploy.parameters.json
  201-vm-sql-full-autopatching/nested/preparingSqlServerSa.json
  201-vm-sql-full-autopatching/scripts/PrepareSqlServer.ps1.zip
Labels: best practices, metadata, readme

#9143 FIX-TEMPLATE: 201-vmss-scale-existing
  201-vmss-scale-existing/azuredeploy.json
  201-vmss-scale-existing/azuredeploy.parameters.json
  201-vmss-scale-existing/prereqs/.settings.json
  201-vmss-scale-existing/prereqs/prereq.azuredeploy.json
  201-vmss-scale-existing/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices, metadata, readme

#9142 FIX-TEMPLATE: 201-vmss-msi
  201-vmss-msi/azuredeploy.json
  201-vmss-msi/scripts/install-and-run-cli-2.sh
Labels: metadata, readme

#9105 FIX-TEMPLATE: 201-redis-premium-persistence
  201-redis-premium-persistence/azuredeploy.json
  201-redis-premium-persistence/azuredeploy.parameters.json
  201-redis-premium-persistence/prereqs/.settings.json
  201-redis-premium-persistence/prereqs/prereq.azuredeploy.json
Labels: metadata, readme

#9226 FIX-TEMPLATE: 201-encrypt-create-new-vm-gallery-image
  201-encrypt-create-new-vm-gallery-image/azuredeploy.json
  201-encrypt-create-new-vm-gallery-image/azuredeploy.parameters.json
  201-encrypt-create-new-vm-gallery-image/azuredeploy.parameters.us.json
Labels: best practices, metadata

#9222 FIX-TEMPLATE: 201-encrypt-create-new-vm-gallery-image-managed-disks
  201-encrypt-create-new-vm-gallery-image-managed-disks/azuredeploy.json
  201-encrypt-create-new-vm-gallery-image-managed-disks/azuredeploy.parameters.json
Labels: best practices, metadata

#9419 AKS + Application Gateway Ingress Controller
  301-aks-application-gateway-ingress-controller/README.md
  301-aks-application-gateway-ingress-controller/azuredeploy.json
  301-aks-application-gateway-ingress-controller/azuredeploy.parameters.json
  301-aks-application-gateway-ingress-controller/images/architecture.png
  301-aks-application-gateway-ingress-controller/images/mc_resourcegroup.png
  301-aks-application-gateway-ingress-controller/images/resourcegroup.png
  301-aks-application-gateway-ingress-controller/images/setup.png
  301-aks-application-gateway-ingress-controller/metadata.json
Labels: readme

#9629 Update azuredeploy.json
  demos/nested-vms-in-virtual-network/azuredeploy.json
Labels: best practices, best practices violations, readme violations

#9628 Groestlcoin: Add missing space
  application-workloads/blockchain/blockchain/azuredeploy.json
Labels: best practices violations, readme violations

#9617 MOVE: rds-deployment to application-workloads\rds
  application-workloads/rds/rds-deployment/Configuration.zip
  application-workloads/rds/rds-deployment/README.md
  application-workloads/rds/rds-deployment/azuredeploy.json
  application-workloads/rds/rds-deployment/azuredeploy.parameters.json
  application-workloads/rds/rds-deployment/metadata.json
  application-workloads/rds/rds-deployment/vnet-with-dns-server.json
  rds-deployment/README.md
Labels: best practices, best practices violations

#9612 MOVE: openedx-fullstack-ubuntu to application-workloads\opendx
  application-workloads/opendx/openedx-fullstack-ubuntu/LICENSE
  application-workloads/opendx/openedx-fullstack-ubuntu/README.md
  application-workloads/opendx/openedx-fullstack-ubuntu/azuredeploy.json
  application-workloads/opendx/openedx-fullstack-ubuntu/azuredeploy.parameters.json
  application-workloads/opendx/openedx-fullstack-ubuntu/install-openedx.sh
  application-workloads/opendx/openedx-fullstack-ubuntu/metadata.json
  application-workloads/opendx/openedx-fullstack-ubuntu/server-vars.yml
  openedx-fullstack-ubuntu/README.md
Labels: best practices, best practices violations

#9606 MOVE: opensis-singlevm-ubuntu to application-workloads\opensis
  application-workloads/opensis/opensis-singlevm-ubuntu/README.md
  application-workloads/opensis/opensis-singlevm-ubuntu/azuredeploy.json
  application-workloads/opensis/opensis-singlevm-ubuntu/azuredeploy.parameters.json
  application-workloads/opensis/opensis-singlevm-ubuntu/install_lamp_opensis.sh
  application-workloads/opensis/opensis-singlevm-ubuntu/metadata.json
  opensis-singlevm-ubuntu/README.md
Labels: best practices, best practices violations

#9112 FIX-TEMPLATE: 201-vm-domain-join
  201-vm-domain-join/azuredeploy.json
  201-vm-domain-join/azuredeploy.parameters.json
  201-vm-domain-join/prereqs/.settings.json
  201-vm-domain-join/prereqs/prereq.azuredeploy.json
  201-vm-domain-join/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices, best practices violations, metadata, metadata violations

#9165 FIX-TEMPLATE: glassfish-on-suse
  glassfish-on-suse/azuredeploy.json
  glassfish-on-suse/nestedtemplates/azuredeploy.json
Labels: best practices, best practices violations, metadata, metadata violations, readme

#9436 FIX-TEMPLATE: visual-studio-dev-vm-O365
  visual-studio-dev-vm-O365/azuredeploy.json
  visual-studio-dev-vm-O365/azuredeploy.parameters.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9450 FIX-TEMPLATE: ubuntu-netdisk-setup
  ubuntu-netdisk-setup/azuredeploy.json
  ubuntu-netdisk-setup/azuredeploy.parameters.json
  ubuntu-netdisk-setup/script/install.sh
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9491 FIX-TEMPLATE: tfs-basic-domain
  tfs-basic-domain/azuredeploy.json
  tfs-basic-domain/scripts/ConfigureTfsBasic.ps1
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9492 FIX-TEMPLATE: tfs-basic-workgroup
  tfs-basic-workgroup/azuredeploy.json
  tfs-basic-workgroup/scripts/ConfigureTfsWorkgroup.ps1
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9631 FIX-TEMPLATE: Add BYO resource support in CMK Workspace creation
  quickstarts/microsoft.machinelearningservices/machine-learning-advanced/azuredeploy.json
Labels: best practices violations, readme violations

#9654 FIX-TEMPLATE: vm-cpu-sysbench-meter
  vm-cpu-sysbench-meter/azuredeploy.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9657 FIX-TEMPLATE: vsts-fullbuild-redhat-vm
  vsts-fullbuild-redhat-vm/azuredeploy.json
  vsts-fullbuild-redhat-vm/azuredeploy.parameters.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9658 FIX-TEMPLATE: vsts-fullbuild-ubuntu-vm
  vsts-fullbuild-ubuntu-vm/azuredeploy.json
  vsts-fullbuild-ubuntu-vm/azuredeploy.parameters.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9660 FIX-TEMPLATE: sap-lama-apps
  sap-lama-apps/azuredeploy.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9661 FIX-TEMPLATE: sap-lama-ascs
  sap-lama-ascs/azuredeploy.json
  sap-lama-ascs/azuredeploy.parameters.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9662 FIX-TEMPLATE: sap-lama-database
  sap-lama-database/azuredeploy.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9663 FIX-TEMPLATE: sap-2-tier-marketplace-image-md
  sap-2-tier-marketplace-image-md/azuredeploy.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9665 FIX-TEMPLATE: sap-3-tier-marketplace-image-converged-md
  sap-3-tier-marketplace-image-converged-md/azuredeploy.json
  sap-3-tier-marketplace-image-converged-md/azuredeploy.parameters.json
  sap-3-tier-marketplace-image-converged-md/shared/loadbalancer.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9684 FIX-TEMPLATE: openedx-devstack-ubuntu
  openedx-devstack-ubuntu/azuredeploy.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9678 FIX-TEMPLATE: scrapy-on-ubuntu
  scrapy-on-ubuntu/azuredeploy.json
  scrapy-on-ubuntu/azuredeploy.parameters.json
  scrapy-on-ubuntu/scrapy-install-ubuntu.sh
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9677 FIX-TEMPLATE: shibboleth-cluster-ubuntu
  shibboleth-cluster-windows/azuredeploy.json
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9676 FIX-TEMPLATE: shibboleth-singlevm-ubuntu
  shibboleth-singlevm-ubuntu/azuredeploy.json
  shibboleth-singlevm-ubuntu/install_shibboleth_idp.sh
Labels: best practices, best practices violations, metadata, metadata violations, readme, readme violations

#9428 update api-version, add bicep support
  quickstarts/microsoft.documentdb/cosmosdb-sql/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-sql/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-sql/metadata.json
Labels: bicep, readme violations

#9249 FIX-TEMPLATE: 201-customscript-extension-public-storage-on-ubuntu
  201-customscript-extension-public-storage-on-ubuntu/README.md
  201-customscript-extension-public-storage-on-ubuntu/azuredeploy.json
  201-customscript-extension-public-storage-on-ubuntu/azuredeploy.parameters.json
  201-customscript-extension-public-storage-on-ubuntu/metadata.json
Labels: best practices, best practices violations

#9781 MOVE: 101-front-door-create-redirect to quickstarts\microsoft.network
  101-front-door-create-redirect/README.md
  quickstarts/microsoft.network/front-door-create-redirect/README.md
  quickstarts/microsoft.network/front-door-create-redirect/azuredeploy.json
  quickstarts/microsoft.network/front-door-create-redirect/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-create-redirect/metadata.json
Labels: best practices violations

#9695 MOVE: sonarqube-azuresql to application-workloads\sonarqube
  application-workloads/sonarqube/sonarqube-azuresql/DSC/SQdscAppConfiguration.ps1.zip
  application-workloads/sonarqube/sonarqube-azuresql/README.md
  application-workloads/sonarqube/sonarqube-azuresql/azuredeploy.json
  application-workloads/sonarqube/sonarqube-azuresql/azuredeploy.parameters.json
  application-workloads/sonarqube/sonarqube-azuresql/docs/SonarQube ARM Template enUS.docx
  application-workloads/sonarqube/sonarqube-azuresql/docs/SonarQube ARM Template ptBR.docx
  application-workloads/sonarqube/sonarqube-azuresql/images/visualize.png
  application-workloads/sonarqube/sonarqube-azuresql/metadata.json
  application-workloads/sonarqube/sonarqube-azuresql/nested/azureDBDeploy.json
  application-workloads/sonarqube/sonarqube-azuresql/oss/License.txt
  application-workloads/sonarqube/sonarqube-azuresql/oss/ThirdPartyNotices.txt
  application-workloads/sonarqube/sonarqube-azuresql/secureSonarQube.ps1
Labels: best practices, best practices violations

#9863 MOVE: 201-cdn-with-ruleseengine-rewriteandredirect to quickstarts\microsoft.cdn
  201-cdn-with-ruleseengine-rewriteandredirect/README.md
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-rewriteandredirect/README.md
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-rewriteandredirect/azuredeploy.json
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-rewriteandredirect/azuredeploy.parameters.json
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-rewriteandredirect/metadata.json
Labels: best practices violations

#9862 MOVE: 201-cdn-with-ruleseengine-responseheader to quickstarts\microsoft.cdn
  201-cdn-with-ruleseengine-responseheader/README.md
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-responseheader/README.md
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-responseheader/azuredeploy.json
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-responseheader/azuredeploy.parameters.json
  quickstarts/microsoft.cdn/cdn-with-ruleseengine-responseheader/metadata.json
Labels: best practices violations

#9830 MOVE: 101-managed-application-with-linked-templates to quickstarts\microsoft.solutions
  quickstarts/microsoft.solutions/managed-application-with-linked-templates/README.md
  quickstarts/microsoft.solutions/managed-application-with-linked-templates/artifacts/ManagedAppZip/createUiDefinition.json
  quickstarts/microsoft.solutions/managed-application-with-linked-templates/artifacts/ManagedAppZip/linkedtemplates/storageAccountdeploy.json
  quickstarts/microsoft.solutions/managed-application-with-linked-templates/artifacts/ManagedAppZip/mainTemplate.json
  quickstarts/microsoft.solutions/managed-application-with-linked-templates/artifacts/ManagedAppZip/pkg.zip
  quickstarts/microsoft.solutions/managed-application-with-linked-templates/azuredeploy.json
  quickstarts/microsoft.solutions/managed-application-with-linked-templates/azuredeploy.parameters.json
  quickstarts/microsoft.solutions/managed-application-with-linked-templates/images/linkeddeployments.png
  quickstarts/microsoft.solutions/managed-application-with-linked-templates/metadata.json
Labels: best practices violations

#9829 MOVE: 101-managed-application-with-metrics-and-alerts to quickstarts\microsoft.solutions
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/README.md
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/artifacts/ManagedAppZip/createUiDefinition.json
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/artifacts/ManagedAppZip/mainTemplate.json
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/artifacts/ManagedAppZip/pkg.zip
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/artifacts/ManagedAppZip/viewDefinition.json
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/azuredeploy.json
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/azuredeploy.parameters.json
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/images/app-alerts-toc.png
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/images/app-alerts.png
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/images/app-metrics and alerts-toc.png
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/images/app-metrics.png
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/images/app-mrg.png
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/images/default-view.png
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/images/essentials.png
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/images/metrics-toc.png
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/images/sa-operations.png
  quickstarts/microsoft.solutions/managed-application-with-metrics-and-alerts/metadata.json
Labels: best practices violations

#9751 MOVE: 201-api-management-logs-to-moesif-using-eventhub-webapp to quickstarts\microsoft.apimanagement
  201-api-management-logs-to-moesif-using-eventhub-webapp/metadata.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/README.md
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/azuredeploy.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/azuredeploy.parameters.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/metadata.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/apis/policies.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/loggers.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.eventhub/namespaces.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.storage/storageaccounts.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/serverfarms.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/sites.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/sites/extensions.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/scripts/apim-2-moesif-webjob-webdeploy.zip
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/scripts/build-webdeploy.sh
Labels: best practices violations

#9140 FIX-TEMPLATE: 201-vmss-custom-script-windows
  201-vmss-custom-script-windows/azuredeploy.json
  201-vmss-custom-script-windows/azuredeploy.parameters.json
Labels: best practices violations, metadata violations, readme violations

#9413 update api version add bicep
  quickstarts/microsoft.documentdb/cosmosdb-cassandra/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-cassandra/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-cassandra/metadata.json
Labels: bicep, readme violations

#9415 update api-version, add bicep support
  quickstarts/microsoft.documentdb/cosmosdb-cassandra-autoscale/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-cassandra-autoscale/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-cassandra-autoscale/metadata.json
Labels: bicep, readme violations

#9438 FIX-TEMPLATE: umbraco-cms-webapp-redis-cache
  umbraco-cms-webapp-redis-cache/azuredeploy.json
  umbraco-cms-webapp-redis-cache/azuredeploy.parameters.json
  umbraco-cms-webapp-redis-cache/prereqs/.settings.json
  umbraco-cms-webapp-redis-cache/prereqs/prereq.azuredeploy.json
  umbraco-cms-webapp-redis-cache/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, metadata violations, readme violations

#9970 MOVE: solace-message-router to application-workloads\solace
  application-workloads/solace/solace-message-router/CONTRIBUTING.md
  application-workloads/solace/solace-message-router/LICENSE
  application-workloads/solace/solace-message-router/README.md
  application-workloads/solace/solace-message-router/azuredeploy.json
  application-workloads/solace/solace-message-router/azuredeploy.parameters.json
  application-workloads/solace/solace-message-router/images/azure-soladmin.png
  application-workloads/solace/solace-message-router/images/azure_console.png
  application-workloads/solace/solace-message-router/images/deployment.png
  application-workloads/solace/solace-message-router/images/ha-cluster.png
  application-workloads/solace/solace-message-router/images/remote_access.png
  application-workloads/solace/solace-message-router/images/single-node.png
  application-workloads/solace/solace-message-router/images/solace_tutorial.png
  application-workloads/solace/solace-message-router/metadata.json
  application-workloads/solace/solace-message-router/nestedtemplates/loadbalancer-shared-resources.json
  application-workloads/solace/solace-message-router/nestedtemplates/security-shared-resources.json
  application-workloads/solace/solace-message-router/nestedtemplates/update-subnet-shared-resources.json
  application-workloads/solace/solace-message-router/nestedtemplates/workspace-enabled-shared-resources.json
  application-workloads/solace/solace-message-router/scripts/deploy_solace.sh
  application-workloads/solace/solace-message-router/scripts/install-solace.sh
  application-workloads/solace/solace-message-router/scripts/semp_query.sh
Labels: best practices violations

#9965 MOVE: 101-backup-la-reporting to demos
  demos/backup-la-reporting/README.md
  demos/backup-la-reporting/azuredeploy.json
  demos/backup-la-reporting/azuredeploy.parameters.json
  demos/backup-la-reporting/images/ActiveDatasources.jpg
  demos/backup-la-reporting/images/ActiveDatasources.png
  demos/backup-la-reporting/images/ActiveStorageParams.JPG
  demos/backup-la-reporting/images/CloudStorageInGB.jpg
  demos/backup-la-reporting/images/CloudStorageInGB.png
  demos/backup-la-reporting/images/DiagnosticSettings.JPG
  demos/backup-la-reporting/images/KeyBackupJobsParameters.jpg
  demos/backup-la-reporting/images/LogAnalyticsScreen.JPG
  demos/backup-la-reporting/images/OverviewTile.JPG
  demos/backup-la-reporting/images/TimeFilter.jpg
  demos/backup-la-reporting/images/la-azurebackup-alertsazure.png
  demos/backup-la-reporting/images/la-azurebackup-backupjobsnonlog.png
  demos/backup-la-reporting/images/la-azurebackup-overview-dashboard.png
  demos/backup-la-reporting/images/la-azurebackup-overview.png
  demos/backup-la-reporting/images/tempImage.jpeg
  demos/backup-la-reporting/metadata.json
  demos/backup-la-reporting/nested/azure_alerts.json
  demos/backup-la-reporting/nested/backup_items.json
  demos/backup-la-reporting/nested/backup_jobs_log.json
  demos/backup-la-reporting/nested/backup_jobs_non_log.json
  demos/backup-la-reporting/nested/cloud_storage.json
  demos/backup-la-reporting/nested/on_prem_alerts.json
  demos/backup-la-reporting/nested/restore_jobs.json
  demos/backup-la-reporting/prereqs/.settings.json
  demos/backup-la-reporting/prereqs/prereq.azuredeploy.json
  demos/backup-la-reporting/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#9960 MOVE: 101-VM-Virus-Attack-Prevention to quickstarts\microsoft.compute
  101-VM-Virus-Attack-Prevention/metadata.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/README.md
  quickstarts/microsoft.compute/vm-virus-attack-prevention/azuredeploy.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/access-vm-0.png
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/disable-internet-explorer-enhanced-security-configuration.png
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/download-test-virus-file.png
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/image.png
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/install-endpoint-protection.png
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/log-analytics.png
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/log-search.png
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/resource-group.PNG
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/restricted-access-on-endpoint-protection.PNG
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/scep-history.PNG
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/search-eicar.png
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/virus-attack-on-virtual-machine.PNG
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/virus-attack-on-vm-1.png
  quickstarts/microsoft.compute/vm-virus-attack-prevention/images/vm-wo-endpoint-protection.PNG
  quickstarts/microsoft.compute/vm-virus-attack-prevention/metadata.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.compute/vm.windows.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.loganalytics/workspaces.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.network/nic-with-pip.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.network/nsg.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.network/publicipaddress.json
  quickstarts/microsoft.compute/vm-virus-attack-prevention/nested/microsoft.network/virtualnetworks.json
Labels: best practices violations

#9956 MOVE: 201-decrypt-vmss-windows to quickstarts\microsoft.compute
  201-decrypt-vmss-windows/README.md
  quickstarts/microsoft.compute/decrypt-vmss-windows/README.md
  quickstarts/microsoft.compute/decrypt-vmss-windows/azuredeploy.json
  quickstarts/microsoft.compute/decrypt-vmss-windows/azuredeploy.parameters.json
  quickstarts/microsoft.compute/decrypt-vmss-windows/metadata.json
  quickstarts/microsoft.compute/decrypt-vmss-windows/prereqs/.settings.json
  quickstarts/microsoft.compute/decrypt-vmss-windows/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.compute/decrypt-vmss-windows/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#9954 MOVE: 201-encrypt-running-vmss-linux to quickstarts\microsoft.compute
  201-encrypt-running-vmss-linux/README.md
  quickstarts/microsoft.compute/encrypt-running-vmss-linux/README.md
  quickstarts/microsoft.compute/encrypt-running-vmss-linux/azuredeploy.json
  quickstarts/microsoft.compute/encrypt-running-vmss-linux/azuredeploy.parameters.json
  quickstarts/microsoft.compute/encrypt-running-vmss-linux/metadata.json
  quickstarts/microsoft.compute/encrypt-running-vmss-linux/prereqs/.settings.json
  quickstarts/microsoft.compute/encrypt-running-vmss-linux/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.compute/encrypt-running-vmss-linux/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#9953 MOVE: 201-expressroute-circuit-public-private-peering to quickstarts\microsoft.network
  201-expressroute-circuit-public-private-peering/README.md
  201-expressroute-circuit-public-private-peering/metadata.json
  quickstarts/microsoft.network/expressroute-circuit-public-private-peering/README.md
  quickstarts/microsoft.network/expressroute-circuit-public-private-peering/azuredeploy.json
  quickstarts/microsoft.network/expressroute-circuit-public-private-peering/azuredeploy.parameters.json
  quickstarts/microsoft.network/expressroute-circuit-public-private-peering/metadata.json
Labels: best practices violations

#9951 MOVE: 201-hdinsight-datalake-store-azure-storage to quickstarts\microsoft.hdinsight
  201-hdinsight-datalake-store-azure-storage/metadata.json
  quickstarts/microsoft.hdinsight/hdinsight-datalake-store-azure-storage/README.md
  quickstarts/microsoft.hdinsight/hdinsight-datalake-store-azure-storage/azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-datalake-store-azure-storage/azuredeploy.parameters.json
  quickstarts/microsoft.hdinsight/hdinsight-datalake-store-azure-storage/metadata.json
Labels: best practices violations

#9941 MOVE: kafka-ubuntu-multidisks to application-workloads\kafka
  application-workloads/kafka/kafka-ubuntu-multidisks/README.md
  application-workloads/kafka/kafka-ubuntu-multidisks/azuredeploy.json
  application-workloads/kafka/kafka-ubuntu-multidisks/azuredeploy.parameters.json
  application-workloads/kafka/kafka-ubuntu-multidisks/datastore-16disk-resources.json
  application-workloads/kafka/kafka-ubuntu-multidisks/datastore-2disk-resources.json
  application-workloads/kafka/kafka-ubuntu-multidisks/datastore-8disk-resources.json
  application-workloads/kafka/kafka-ubuntu-multidisks/empty-resources.json
  application-workloads/kafka/kafka-ubuntu-multidisks/jumpbox-resources.json
  application-workloads/kafka/kafka-ubuntu-multidisks/kafka-cluster-install.sh
  application-workloads/kafka/kafka-ubuntu-multidisks/metadata.json
  application-workloads/kafka/kafka-ubuntu-multidisks/shared-resources.json
  application-workloads/kafka/kafka-ubuntu-multidisks/zookeeper-resources.json
Labels: best practices violations

#9938 MOVE: lap-neo4j-ubuntu to application-workloads\lap
  application-workloads/lap/lap-neo4j-ubuntu/README.md
  application-workloads/lap/lap-neo4j-ubuntu/azuredeploy.json
  application-workloads/lap/lap-neo4j-ubuntu/azuredeploy.parameters.json
  application-workloads/lap/lap-neo4j-ubuntu/metadata.json
  application-workloads/lap/lap-neo4j-ubuntu/nested/lanplap-resources.json
  application-workloads/lap/lap-neo4j-ubuntu/nested/lanpneo4j-resources.json
  application-workloads/lap/lap-neo4j-ubuntu/nested/shared-resources.json
  application-workloads/lap/lap-neo4j-ubuntu/scripts/install-lap.sh
  application-workloads/lap/lap-neo4j-ubuntu/scripts/install-neo4j.sh
Labels: best practices violations

#9916 MOVE: lansa-vmss-windows-autoscale-sql-database to application-workloads\lansa
  application-workloads/lansa/lansa-vmss-windows-autoscale-sql-database/README.md
  application-workloads/lansa/lansa-vmss-windows-autoscale-sql-database/azuredeploy.json
  application-workloads/lansa/lansa-vmss-windows-autoscale-sql-database/azuredeploy.parameters.json
  application-workloads/lansa/lansa-vmss-windows-autoscale-sql-database/metadata.json
Labels: best practices violations

#9894 MOVE: 101-front-door-geo-filtering to quickstarts\microsoft.network
  101-front-door-geo-filtering/README.md
  quickstarts/microsoft.network/front-door-geo-filtering/README.md
  quickstarts/microsoft.network/front-door-geo-filtering/azuredeploy.json
  quickstarts/microsoft.network/front-door-geo-filtering/azuredeploy.parameters.json
  quickstarts/microsoft.network/front-door-geo-filtering/metadata.json
Labels: best practices violations

#9890 MOVE: 201-vm-sql-full-autobackup to quickstarts\microsoft.compute
  quickstarts/microsoft.compute/vm-sql-full-autobackup/README.md
  quickstarts/microsoft.compute/vm-sql-full-autobackup/azuredeploy.json
  quickstarts/microsoft.compute/vm-sql-full-autobackup/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-sql-full-autobackup/metadata.json
  quickstarts/microsoft.compute/vm-sql-full-autobackup/nested/preparingSqlServerSa.json
  quickstarts/microsoft.compute/vm-sql-full-autobackup/scripts/PrepareSqlServer.ps1.zip
Labels: best practices violations

#9823 MOVE: 101-recovery-services-daily-backup-policy-create to quickstarts\microsoft.recoveryservices
  101-recovery-services-daily-backup-policy-create/README.md
  quickstarts/microsoft.recoveryservices/recovery-services-daily-backup-policy-create/README.md
  quickstarts/microsoft.recoveryservices/recovery-services-daily-backup-policy-create/azuredeploy.json
  quickstarts/microsoft.recoveryservices/recovery-services-daily-backup-policy-create/azuredeploy.parameters.json
  quickstarts/microsoft.recoveryservices/recovery-services-daily-backup-policy-create/metadata.json
Labels: best practices violations

#9813 MOVE: 101-ubuntu-mate-desktop-vscode to application-workloads\visualstudio
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/GettingStarted.md
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azdeploy.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azdeploy2.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azdeploy3.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azdeployportal.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azdeployportal2.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azdeployportal3.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azgroup.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azlogin.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azlogin2.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azportal.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azportaldepoy2.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azportaldepoy3.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azsetsub.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azssh.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/aztemplate.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/aztemplate2.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/aztemplate3.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/azubuntu.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/off1.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/Images/off2.png
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/README.md
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/azuredeploy.json
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/azuredeploy.parameters.json
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/infra.sh
  application-workloads/visualstudio/ubuntu-mate-desktop-vscode/metadata.json
Labels: best practices violations

#9809 MOVE: 101-vm-tags to quickstarts\microsoft.compute
  101-vm-tags/README.md
  quickstarts/microsoft.compute/vm-tags/README.md
  quickstarts/microsoft.compute/vm-tags/azuredeploy.json
  quickstarts/microsoft.compute/vm-tags/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vm-tags/metadata.json
Labels: best practices violations

#9697 MOVE: sqlvm-provisioning-csp to application-workloads\sql
  application-workloads/sql/sqlvm-provisioning-csp/Common.ps1
  application-workloads/sql/sqlvm-provisioning-csp/CreateSQLVMExample.ps1
  application-workloads/sql/sqlvm-provisioning-csp/New-SqlServerVirtualMachine.ps1
  application-workloads/sql/sqlvm-provisioning-csp/README.md
  application-workloads/sql/sqlvm-provisioning-csp/azuredeploy.json
  application-workloads/sql/sqlvm-provisioning-csp/azuredeploy.parameters.json
  application-workloads/sql/sqlvm-provisioning-csp/metadata.json
Labels: best practices violations

#9838 FIX-TEMPLATE: python-proxy-on-ubuntu (new)
  python-proxy-on-ubuntu/azuredeploy.json
  python-proxy-on-ubuntu/azuredeploy.parameters.json
  python-proxy-on-ubuntu/python-proxy-install-ubuntu.sh
Labels: best practices violations, readme violations

#9835 FIX-TEMPLATE: 301-servicebus-namespace-vnet
  301-servicebus-namespace-vnet/azuredeploy.json
  301-servicebus-namespace-vnet/azuredeploy.parameters.json
Labels: best practices violations, readme violations

#9923 FIX-TEMPLATE: anti-malware-extension-windows-vm
  anti-malware-extension-windows-vm/azuredeploy.json
Labels: best practices violations, readme violations

#10149 FIX-TEMPLATE: 201-cdn-customize
  201-aks-sql-server-always-on/azuredeploy.json
Labels: best practices violations, readme violations

#10147 FIX-TEMPLATE: 201-aci-linuxcontainer-healthprobe
  201-aci-linuxcontainer-healthprobe/azuredeploy.json
Labels: best practices violations, readme violations

#10137 FIX-TEMPLATE: 101-data-factory-salesforce-to-blob-copy
  101-data-factory-salesforce-to-blob-copy/azuredeploy.json
Labels: readme violations

#10105 FIX-TEMPLATE: arm-template-retrieve-azure-storage-access-keys
  arm-template-retrieve-azure-storage-access-keys/azuredeploy.parameters.json
Labels: best practices violations, readme violations

#10226 FIX-TEMPLATE: oms-servicebus-solution
  oms-servicebus-solution/README.md
  oms-servicebus-solution/azuredeploy.json
  oms-servicebus-solution/azuredeploy.parameters.json
  oms-servicebus-solution/metadata.json
  oms-servicebus-solution/nestedtemplates/addMultipleSubscriptions.json
Labels: best practices violations, readme violations

#10223 FIX-TEMPLATE: oms-azurensg-solution
  oms-azurensg-solution/README.md
  oms-azurensg-solution/azuredeploy.json
  oms-azurensg-solution/azuredeploy.parameters.json
  oms-azurensg-solution/metadata.json
Labels: best practices violations

#10179 FIX-TEMPLATE: oms-active-directory-security-audit-solution
  oms-active-directory-security-audit-solution/README.md
  oms-active-directory-security-audit-solution/azuredeploy.json
  oms-active-directory-security-audit-solution/azuredeploy.parameters.json
  oms-active-directory-security-audit-solution/metadata.json
Labels: best practices violations, readme violations

#10222 FIX-TEMPLATE: oms-automation-solution
  oms-automation-solution/README.md
  oms-automation-solution/azuredeploy.json
  oms-automation-solution/azuredeploy.parameters.json
  oms-automation-solution/metadata.json
Labels: best practices violations, readme violations

#10178 FIX-TEMPLATE: octopusdeploy3-single-vm-windows
  octopusdeploy3-single-vm-windows/README.md
  octopusdeploy3-single-vm-windows/azuredeploy.json
  octopusdeploy3-single-vm-windows/metadata.json
Labels: best practices violations

#10177 FIX-TEMPLATE: nylas-email-sync-engine
  nylas-email-sync-engine/README.md
  nylas-email-sync-engine/azuredeploy.json
  nylas-email-sync-engine/metadata.json
Labels: best practices violations

#10173 FIX-TEMPLATE: drone-ubuntu-vm
  drone-ubuntu-vm/azuredeploy.json
  drone-ubuntu-vm/install_drone.sh
Labels: best practices violations, readme violations
