Repository Azure/azure-quickstart-templates, pull requests merged in 2021-12, with the labels that each got.

#12053 Deploy an AKS cluster with NAT Gateway for outbound connections and an Application Gateway for inbound connections
  demos/aks-nat-agic/README.md
  demos/aks-nat-agic/azuredeploy.json
  demos/aks-nat-agic/azuredeploy.parameters.json
  demos/aks-nat-agic/images/architecture.png
  demos/aks-nat-agic/images/container-output.png
  demos/aks-nat-agic/images/mc_resourcegroup.png
  demos/aks-nat-agic/images/nat-gateway.png
  demos/aks-nat-agic/images/resourcegroup.png
  demos/aks-nat-agic/images/setup.png
  demos/aks-nat-agic/metadata.json
Labels: BPA

#12047 Adding new templates for Budget creation
  quickstarts/microsoft.consumption/create-budget-simple/README.md
  quickstarts/microsoft.consumption/create-budget-simple/azuredeploy.json
  quickstarts/microsoft.consumption/create-budget-simple/azuredeploy.parameters.json
  quickstarts/microsoft.consumption/create-budget-simple/metadata.json
Labels: manual validation required

#12063 Add a single filter template
  quickstarts/microsoft.consumption/create-budget-onefilter/README.md
  quickstarts/microsoft.consumption/create-budget-onefilter/azuredeploy.json
  quickstarts/microsoft.consumption/create-budget-onefilter/azuredeploy.parameters.json
  quickstarts/microsoft.consumption/create-budget-onefilter/metadata.json
Labels: manual validation required

#12062 Modify existing create-budget template to represent required fields
  quickstarts/microsoft.consumption/create-budget/README.md
  quickstarts/microsoft.consumption/create-budget/azuredeploy.json
  quickstarts/microsoft.consumption/create-budget/metadata.json
Labels: manual validation required

#12068 New template to add an external endpoint to an existing traffic manager profile
  quickstarts/microsoft.network/traffic-manager-add-external-endpoint/README.md
  quickstarts/microsoft.network/traffic-manager-add-external-endpoint/azuredeploy.json
  quickstarts/microsoft.network/traffic-manager-add-external-endpoint/azuredeploy.parameters.json
  quickstarts/microsoft.network/traffic-manager-add-external-endpoint/metadata.json
  quickstarts/microsoft.network/traffic-manager-add-external-endpoint/prereqs/.settings.json
  quickstarts/microsoft.network/traffic-manager-add-external-endpoint/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.network/traffic-manager-add-external-endpoint/prereqs/prereq.azuredeploy.parameters.json
Labels: BPA

#12083 Update azuredeploy.json
  quickstarts/microsoft.compute/vm-simple-windows/azuredeploy.json
  quickstarts/microsoft.compute/vm-simple-windows/createUiDefinition.json
  quickstarts/microsoft.compute/vm-simple-windows/main.bicep
  quickstarts/microsoft.compute/vm-simple-windows/metadata.json
Labels: bicep, PORTAL SAMPLE
