Repository Azure/azure-quickstart-templates, pull requests merged in 2022-08, with the labels that each got.

#12744 Fixed typo ('segments' instead of 'segements')
  quickstarts/microsoft.network/azure-dns-new-zone/main.bicep
Labels: metadata violations

#12693 update metadata for A4E
  quickstarts/microsoft.web/function-app-create-dedicated/metadata.json
Labels: best practices violations, BPA

#12677 Update create tresholdtype on create budget
  quickstarts/microsoft.consumption/create-budget/azuredeploy.json
  quickstarts/microsoft.consumption/create-budget/main.bicep
  quickstarts/microsoft.consumption/create-budget/metadata.json
Labels: manual validation required, remove azuredeploy.json, duplicate metadata

#12747 add level tag
  demos/ubuntu-desktop-gnome-rdp/metadata.json
Labels: best practices violations

#12748 updated metadata and Readme files for afs backup template with daily frequency
  quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share/README.md
  quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share/metadata.json
Labels: bicep warnings

#12751 added double quotes email Id parameter based on feedback - Alert Processing Rule template
  quickstarts/microsoft.recoveryservices/recovery-services-create-alert-processing-rule/azuredeploy.json
  quickstarts/microsoft.recoveryservices/recovery-services-create-alert-processing-rule/main.bicep
  quickstarts/microsoft.recoveryservices/recovery-services-create-alert-processing-rule/metadata.json
Labels: remove azuredeploy.json

#12690 multi-region-api updates
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/README.md
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/azuredeploy.parameters.json
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/azuredeploy.parameters.us.json
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-create-multi-region-account/metadata.json
Labels: best practices violations

#12681 Adding azure fileshare backup template with hourly backup policy
  quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly/README.md
  quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly/azuredeploy.parameters.json
  quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly/main.bicep
  quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly/metadata.json
  quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly/prereqs/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.recoveryservices/recovery-services-backup-file-share-hourly/prereqs/prereq.main.bicep
Labels: remove azuredeploy.json

#12705 mongo autoscale updates
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/README.md
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/azuredeploy.parameters.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/azuredeploy.parameters.us.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/metadata.json
Labels: decompile clean-up needed

#12760 web app updates
  quickstarts/microsoft.documentdb/cosmosdb-webapp/README.md
  quickstarts/microsoft.documentdb/cosmosdb-webapp/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-webapp/azuredeploy.parameters.json
  quickstarts/microsoft.documentdb/cosmosdb-webapp/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-webapp/metadata.json
Labels: BPA

#12702 mongo updates
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/README.md
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/azuredeploy.parameters.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/azuredeploy.parameters.us.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/metadata.json
Labels: decompile clean-up needed

#12773 Quickstart for Azure Machine Learning Data Asset creation
  quickstarts/microsoft.machinelearningservices/machine-learning-dataasset-create-from-file-uri/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-dataasset-create-from-file-uri/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataasset-create-from-file-uri/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-dataasset-create-from-file-uri/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataasset-create-from-file-uri/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataasset-create-from-file-uri/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataasset-create-from-file-uri/prereqs/prereq.azuredeploy.parameters.json
Labels: bicep warnings, remove azuredeploy.json

#12775 Update azuredeploy.json
  quickstarts/microsoft.signalrservice/signalr/azuredeploy.json
  quickstarts/microsoft.signalrservice/signalr/main.bicep
  quickstarts/microsoft.signalrservice/signalr/metadata.json
Labels: remove azuredeploy.json

#12766 Add AutoML classification job to quickstarts
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/data/training-mltable-folder/MLTable
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/data/training-mltable-folder/bank_marketing_train_data.csv
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/data/validation-mltable-folder/MLTable
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/data/validation-mltable-folder/bank_marketing_validation_data.csv
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-automl-classification-job/prereqs/prereq.azuredeploy.parameters.json
Labels: bicep warnings, remove azuredeploy.json

#12774 Quickstart Create Azure Machine Learning Data Version asset
  quickstarts/microsoft.machinelearningservices/machine-learning-dataversion-create-from-file-uri/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-dataversion-create-from-file-uri/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataversion-create-from-file-uri/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-dataversion-create-from-file-uri/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataversion-create-from-file-uri/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataversion-create-from-file-uri/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-dataversion-create-from-file-uri/prereqs/prereq.azuredeploy.parameters.json
Labels: bicep warnings, remove azuredeploy.json

#12743 Fix typo in README H1
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-privateendpoint/README.md
Labels: metadata violations, best practices violations

#12459 [service bus] update API versions
  quickstarts/microsoft.servicebus/servicebus-create-queue/azuredeploy.json
  quickstarts/microsoft.servicebus/servicebus-create-queue/main.bicep
  quickstarts/microsoft.servicebus/servicebus-create-queue/metadata.json
Labels: metadata violations, remove azuredeploy.json

#12794 OpenScholar Update
  application-workloads/openscholar/openscholar/README.md
  application-workloads/openscholar/openscholar/azuredeploy.json
  application-workloads/openscholar/openscholar/metadata.json
  application-workloads/openscholar/openscholar/scripts/openDrupal.sh
Labels: duplicate foldername

#12686 update metadata for edu
  quickstarts/microsoft.web/function-app-dedicated-github-deploy/metadata.json
Labels: best practices violations

#12799 update metadata for A4E
  quickstarts/microsoft.web/app-function/metadata.json
Labels: best practices violations, BPA

#12800 update metadata for A4E
  application-workloads/tomcat/openjdk-tomcat-ubuntu-vm/metadata.json
Labels: best practices violations

#12803 update metadata for A4E
  quickstarts/microsoft.web/webapp-linux-flask/metadata.json
Labels: metadata violations, best practices violations, BPA

#12804 update metadata for A4E
  quickstarts/microsoft.web/webapp-linux-django/metadata.json
Labels: best practices violations, BPA

#12805 update metadata for A4E
  quickstarts/microsoft.web/web-app-java-tomcat/metadata.json
Labels: metadata violations, best practices violations, BPA

#12793 Get started with Azure Data Factory
  quickstarts/microsoft.datafactory/data-factory-get-started/README.md
  quickstarts/microsoft.datafactory/data-factory-get-started/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
  quickstarts/microsoft.datafactory/data-factory-get-started/metadata.json
  quickstarts/microsoft.datafactory/data-factory-get-started/moviesDB2.csv
  quickstarts/microsoft.datafactory/data-factory-get-started/scripts/copy-data.ps1
Labels: best practices violations, bicep warnings

#12601 0708 networkwatcher
  quickstarts/microsoft.network/networkwatcher-flowLogs-create/azuredeploy.json
  quickstarts/microsoft.network/networkwatcher-flowLogs-create/main.bicep
  quickstarts/microsoft.network/networkwatcher-flowLogs-create/metadata.json
  quickstarts/microsoft.network/networkwatcher-flowLogs-create/nested_deployFlowLogs.bicep
  quickstarts/microsoft.network/networkwatcher-flowLogs-create/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.network/networkwatcher-flowLogs-create/prereqs/prereq.main.bicep
Labels: UPPERCASE

#12807 Corrected typo virtualVan into VirtualWan
  quickstarts/microsoft.network/fwm-docs-qs/main.bicep
Labels: metadata violations

#12808 Updating api version
  quickstarts/microsoft.azurepurview/azure-purview-deployment/azuredeploy.json
Labels: metadata violations

#12814 ad dsc script update
  application-workloads/active-directory/active-directory-new-domain/DSC/CreateADPDC.ps1
  application-workloads/active-directory/active-directory-new-domain/DSC/CreateADPDC.zip
  application-workloads/active-directory/active-directory-new-domain/azuredeploy.json
  application-workloads/active-directory/active-directory-new-domain/metadata.json
  application-workloads/active-directory/active-directory-new-domain/nestedtemplates/vnet-with-dns-server.json
  application-workloads/active-directory/active-directory-new-domain/nestedtemplates/vnet.json
Labels: duplicate foldername

#12815 Ad module
  modules/active-directory-new-domain/0.9/DSC/CreateADPDC.ps1
  modules/active-directory-new-domain/0.9/DSC/CreateADPDC.zip
  modules/active-directory-new-domain/0.9/metadata.json
Labels: duplicate foldername

#12819 Updates per closed PR# 12694
  quickstarts/microsoft.logic/logic-app-create/metadata.json
Labels: metadata violations
