Repository Azure/azure-quickstart-templates, pull requests merged in 2022-09, with the labels that each got.

#12824 removed github tag
  quickstarts/microsoft.logic/logic-app-create/metadata.json
Labels: metadata violations

#12825 Ensure 'CoreTechnology' is set to either 'EPC' or '5GC'
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/main.bicep
Labels: duplicate metadata

#12827 Ensure 'CoreTechnology' is set to either 'EPC' or '5GC'
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-site/main.bicep
Labels: duplicate metadata

#12823 remove github tag
  quickstarts/microsoft.web/function-app-dedicated-github-deploy/metadata.json
Labels: best practices violations

#12829 [Purview] - add Bicep
  quickstarts/microsoft.azurepurview/azure-purview-deployment/README.md
  quickstarts/microsoft.azurepurview/azure-purview-deployment/azuredeploy.json
  quickstarts/microsoft.azurepurview/azure-purview-deployment/main.bicep
  quickstarts/microsoft.azurepurview/azure-purview-deployment/metadata.json
Labels: bicep warnings

#12832 Quickstart demonstrating configuration of Azure Functions Premium plan with availability zones support
  quickstarts/microsoft.web/function-premium-availability-zone/README.md
  quickstarts/microsoft.web/function-premium-availability-zone/azuredeploy.json
  quickstarts/microsoft.web/function-premium-availability-zone/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-premium-availability-zone/azuredeploy.parameters.us.json
  quickstarts/microsoft.web/function-premium-availability-zone/main.bicep
  quickstarts/microsoft.web/function-premium-availability-zone/metadata.json
Labels: BPA, remove azuredeploy.json

#12841 eap7.4-rhel8.6-standalone-patch2.1
  application-workloads/jboss/jboss-eap-standalone-rhel/README.md
  application-workloads/jboss/jboss-eap-standalone-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-standalone-rhel/metadata.json
  application-workloads/jboss/jboss-eap-standalone-rhel/scripts/jbosseap-setup-redhat.sh
Labels: manual validation required, BPA

#12842 eap7.4-rhel8.6-multivm-patch2.1
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/README.md
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/metadata.json
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/scripts/jbosseap-setup-redhat.sh
Labels: manual validation required, BPA

#12818 Add Sweep job to quickstarts
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/data/iris.csv
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/modules/codeversion.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/prereqs/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-sweep-job/scripts/main.py
Labels: bicep warnings, BPA, remove azuredeploy.json

#12850 Delete azuredeploy.json
  quickstarts/microsoft.storage/storage-sftp/azuredeploy.json
  quickstarts/microsoft.storage/storage-sftp/metadata.json
Labels: bicep warnings, BPA

#12864 Update azuredeploy.parameters.json
  application-workloads/active-directory/active-directory-new-domain-ha-2-dc-zones/azuredeploy.parameters.json
Labels: metadata violations, BPA

#12863 Added the quickstart template for the sports analytics architecture on Azure
  demos/sports-analytics-architecture/README.md
  demos/sports-analytics-architecture/azuredeploy.parameters.json
  demos/sports-analytics-architecture/images/sports-analytics-azure-reference-architecture.png
  demos/sports-analytics-architecture/main.bicep
  demos/sports-analytics-architecture/metadata.json
  demos/sports-analytics-architecture/scripts/GetPrincipalObjectID.ps1
Labels: BPA

#12868 remove array() because range() returns an array already
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-new-storage/azuredeploy.json
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-new-storage/main.bicep
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-new-storage/metadata.json
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-new-storage/prereqs/prereq.azuredeploy.json
Labels: remove azuredeploy.json

#12872 Updated the sports analytics template
  demos/sports-analytics-architecture/README.md
  demos/sports-analytics-architecture/azuredeploy.json
  demos/sports-analytics-architecture/azuredeploy.parameters.json
  demos/sports-analytics-architecture/main.bicep
Labels: BPA

#12881 Adds quickstart template for Azure Data Factory copy data tool
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/README.md
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/azuredeploy.parameters.json
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/main.bicep
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/metadata.json
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/moviesDB2.csv
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/scripts/copy-data.ps1
Labels: BPA
