Repository Azure/azure-quickstart-templates, pull requests merged in 2022-12, with the labels that each got.

#12984 Add Bicep and update API versions
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/README.md
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/azuredeploy.parameters.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/main.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/metadata.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/nested_addAccessPolicy.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/prereqs/prereq.azuredeploy.json
Labels: remove azuredeploy.json

#13021 Update Client to use windows 11 22H2
  application-workloads/sccm/sccm-technicalpreview/azuredeploy.json
  application-workloads/sccm/sccm-technicalpreview/metadata.json
Labels: best practices violations

#13022 Update client to use windows 11 22h2
  application-workloads/sccm/sccm-currentbranch/azuredeploy.json
  application-workloads/sccm/sccm-currentbranch/metadata.json
Labels: best practices violations

#13020 updating with new site properties
  quickstarts/microsoft.web/webapp-privateendpoint-vnet-injection/azuredeploy.json
  quickstarts/microsoft.web/webapp-privateendpoint-vnet-injection/main.bicep
Labels: best practices violations, BPA, remove azuredeploy.json

#13024 Move to 2022-11-01 API for mobilenetwork-create-sim-policy
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-sim-policy/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-sim-policy/prereqs/prereq.azuredeploy.json
Labels: remove azuredeploy.json

#13025 Move to 2022-11-01 API for mobilenetwork-provision-proxy-sims
  quickstarts/microsoft.mobilenetwork/mobilenetwork-provision-proxy-sims/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-provision-proxy-sims/prereqs/prereq.azuredeploy.json
Labels: bicep warnings, BPA, remove azuredeploy.json

#13012 [AKS NAT gateway] - Add Bicep and update API versions.
  demos/aks-nat-agic/README.md
  demos/aks-nat-agic/azuredeploy.json
  demos/aks-nat-agic/main.bicep
  demos/aks-nat-agic/metadata.json
Labels: BPA

#13028 Move to new API with for update-packet-core-control-plane
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/azuredeploy.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/azuredeploy.parameters.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/createUiDefinition.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/prereqs/prereq.azuredeploy.json
Labels: BPA, remove azuredeploy.json

#13015 [Machine Learning workspace] - add Bicep and update API versions
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace/azuredeploy.parameters.us.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace/metadata.json
Labels: duplicate foldername

#12992 add Bicep and update API versions
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/nested_DeployPrivateEndpoints.bicep
Labels: BPA

#13030 1206 vms with selfhost integration runtime
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/README.md
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/azuredeploy.json
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/main.bicep
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/metadata.json
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/nested/IRInstall.bicep
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/nested/IRInstall.json
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/nested/IRtemplate.bicep
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/nested/IRtemplate.json
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/nested/VMtemplate.bicep
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/nested/VMtemplate.json
Labels: best practices violations, BPA

#13033 [Dokku] - update API versions and add Bicep
  application-workloads/dokku/dokku-vm/README.md
  application-workloads/dokku/dokku-vm/main.bicep
  application-workloads/dokku/dokku-vm/metadata.json
Labels: BPA

#13027 Move to 2022-11-01 API for mobilenetwork-create-new-site
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-site/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-site/prereqs/prereq.azuredeploy.json
Labels: merge-conflict

#12990 Add Bicep and update API versions
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet-v1-legacy-mode/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet-v1-legacy-mode/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet-v1-legacy-mode/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet-v1-legacy-mode/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet-v1-legacy-mode/nested_DeployPrivateEndpoints.bicep
Labels: BPA

#13035 [postgresql] - update API versions and add Bicep
  quickstarts/microsoft.web/webapp-linux-sonarqube-postgresql/README.md
  quickstarts/microsoft.web/webapp-linux-sonarqube-postgresql/azuredeploy.json
  quickstarts/microsoft.web/webapp-linux-sonarqube-postgresql/main.bicep
  quickstarts/microsoft.web/webapp-linux-sonarqube-postgresql/metadata.json
Labels: best practices violations, BPA

#12821 Fix GatewayInstall scripts fails with error aborted: Could not create SSL/TLS secure channel.
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/gatewayInstall.ps1
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, BPA

#13042 Removed MAA and ASC Endpoint for Linux TLVM
  quickstarts/microsoft.compute/vm-trustedlaunch-linux/azuredeploy.json
  quickstarts/microsoft.compute/vm-trustedlaunch-linux/createUiDefinition.json
  quickstarts/microsoft.compute/vm-trustedlaunch-linux/main.bicep
  quickstarts/microsoft.compute/vm-trustedlaunch-linux/metadata.json
Labels: BPA

#13031 fixing default params that people can work with it :)
  demos/xss-attack-prevention/artifacts/contosoclinic.bacpac
  demos/xss-attack-prevention/azuredeploy.json
Labels: best practices violations, BPA

#13050 Fix up site parent
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-site/main.bicep
Labels: best practices violations

#13034 [Traefik] - update API versions and add Bicep
  application-workloads/traefik/docker-portainer-traefik-windows-vm/README.md
  application-workloads/traefik/docker-portainer-traefik-windows-vm/azuredeploy.json
  application-workloads/traefik/docker-portainer-traefik-windows-vm/main.bicep
  application-workloads/traefik/docker-portainer-traefik-windows-vm/metadata.json
Labels: merge-conflict, BPA
