Repository Azure/azure-quickstart-templates, pull requests merged in 2022-10, with the labels that each got.

#12761 Update GDVM with Bicep Module
  application-workloads/azure-gamedev/gamedev-vm/azuredeploy.parameters.json
  application-workloads/azure-gamedev/gamedev-vm/createUiDefinition.json
  application-workloads/azure-gamedev/gamedev-vm/main.bicep
  application-workloads/azure-gamedev/gamedev-vm/nestedtemplates/gamedev-vm.bicep
  application-workloads/azure-gamedev/gamedev-vm/scripts/CreateDataDisk.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/MountFileShare.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/PostInstall.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/TeradiciRegCAS.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/ibSetup.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/p4DepotSync.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/Automatic-Shutdown.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/Clear-Proxy.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/CreateAutomaticShutdownScheduledTask.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/CreateClearProxyScheduledTask.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/CreateOneHourWarningScheduledTask.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/ForceCloseShutDown.reg
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/GPU-Update.ico
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/NetworkRestore.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/NetworkRestore.reg
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/OneHour.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/Parsec.png
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/ShowDialog.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/TeamMachineSetup.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/WarningMessage.ps1
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/gpt.ini
  application-workloads/azure-gamedev/gamedev-vm/scripts/parsec/psscripts.ini
Labels: metadata violations, best practices violations

#12871 Add CMK support to the Proxy SIMs ARM template
  quickstarts/microsoft.mobilenetwork/mobilenetwork-provision-proxy-sims/azuredeploy.parameters.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-provision-proxy-sims/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-provision-proxy-sims/metadata.json
Labels: bicep warnings, BPA

#12873 Add CMK support to the Full 5GC Deployment ARM template
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/metadata.json
Labels: bicep warnings, duplicate metadata

#12878 Updated AKV role authorization to include proper conditional
  demos/sports-analytics-architecture/README.md
  demos/sports-analytics-architecture/azuredeploy.json
  demos/sports-analytics-architecture/azuredeploy.parameters.json
  demos/sports-analytics-architecture/main.bicep
Labels: BPA

#12883 Restrict allowed length of VM name to 15
  application-workloads/active-directory/active-directory-new-domain/azuredeploy.json
Labels: duplicate foldername

#12885 Link + Alt text update
  demos/sports-analytics-architecture/README.md
Labels: BPA

#12891 Update VA ARM template to use the new API storageless
  quickstarts/microsoft.sql/sql-logical-server/azuredeploy.json
  quickstarts/microsoft.sql/sql-logical-server/metadata.json
Labels: metadata violations, best practices violations, BPA

#12720 Update AML end-to-end quickstart template
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/bastion.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/containerregistry.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/keyvault.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/machinelearning.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/machinelearningcompute.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/machinelearningnetworking.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/nsg.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/privateaks.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/storage.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/vnet.bicep
Labels: metadata violations, best practices violations, bicep warnings

#12900 Update metadata.json
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/metadata.json
Labels: BPA

#12899 Update main.bicep
  quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
Labels: BPA

#12902 Dapr Microservices Container App
  quickstarts/microsoft.app/container-app-dapr-blob/README.md
  quickstarts/microsoft.app/container-app-dapr-blob/azuredeploy.parameters.json
  quickstarts/microsoft.app/container-app-dapr-blob/main.bicep
  quickstarts/microsoft.app/container-app-dapr-blob/metadata.json
Labels: best practices violations

#12903 misc fixes
  quickstarts/microsoft.datafactory/data-factory-get-started/README.md
  quickstarts/microsoft.datafactory/data-factory-get-started/main.bicep
  quickstarts/microsoft.datafactory/data-factory-get-started/metadata.json
  quickstarts/microsoft.datafactory/data-factory-get-started/scripts/copy-data.ps1
Labels: BPA

#12905 remove roleAssignment dependency
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/README.md
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/main.bicep
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/metadata.json
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/moviesDB2.csv
  quickstarts/microsoft.datafactory/data-factory-copy-data-tool/scripts/copy-data.ps1
Labels: BPA

#12750 Container Apps with Azure Container Registry
  quickstarts/microsoft.app/container-app-acr/README.md
  quickstarts/microsoft.app/container-app-acr/azuredeploy.parameters.json
  quickstarts/microsoft.app/container-app-acr/containerRegistry.bicep
  quickstarts/microsoft.app/container-app-acr/main.bicep
  quickstarts/microsoft.app/container-app-acr/metadata.json
Labels: best practices violations

#12913 remove v1 option
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/README.md
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/azuredeploy.json
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/metadata.json
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/nested/IRtemplate.json
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/prereqs/prereq.azuredeploy.json
Labels: best practices violations, BPA

#12912 Remove UpdateSubnetPolicy task for PE workspace creation with existing subnet
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/azuredeploy.json
Labels: metadata violations, best practices violations, BPA

#12888 Add darktrace vsensor standalone template
  application-workloads/darktrace-vsensor-standalone/README.md
  application-workloads/darktrace-vsensor-standalone/azuredeploy.json
  application-workloads/darktrace-vsensor-standalone/images/admin-ssh-public-key.png
  application-workloads/darktrace-vsensor-standalone/images/architecture.png
  application-workloads/darktrace-vsensor-standalone/metadata.json
Labels: best practices violations

#12914 added sample for copying blob
  modules/microsoft.resources/deploymentScripts/copyBlob/0.9/README.md
  modules/microsoft.resources/deploymentScripts/copyBlob/0.9/azuredeploy.parameters.json
  modules/microsoft.resources/deploymentScripts/copyBlob/0.9/azuredeploy.parameters.us.json
  modules/microsoft.resources/deploymentScripts/copyBlob/0.9/main.bicep
  modules/microsoft.resources/deploymentScripts/copyBlob/0.9/metadata.json
  modules/microsoft.resources/deploymentScripts/copyBlob/0.9/prereqs/.settings.json
  modules/microsoft.resources/deploymentScripts/copyBlob/0.9/prereqs/prereq.azuredeploy.parameters.json
  modules/microsoft.resources/deploymentScripts/copyBlob/0.9/prereqs/prereq.main.bicep
  modules/microsoft.resources/deploymentScripts/copyBlob/0.9/scripts/copy-data.ps1
Labels: readme violations, UPPERCASE, decompile clean-up needed, BPA, duplicate foldername

#12920 Container App Dapr update
  quickstarts/microsoft.app/container-app-dapr-blob/README.md
  quickstarts/microsoft.app/container-app-dapr-blob/azuredeploy.json
  quickstarts/microsoft.app/container-app-dapr-blob/main.bicep
  quickstarts/microsoft.app/container-app-dapr-blob/metadata.json
Labels: best practices violations

#12923 Remove UpdateSubnetPolicy task for PE workspace creation with existing subnet
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet-v1-legacy-mode/azuredeploy.json
Labels: metadata violations, BPA

#12921 Update webapp-linux-sonarqube-postgresql/azuredeploy.json
  quickstarts/microsoft.web/webapp-linux-sonarqube-postgresql/azuredeploy.json
Labels: metadata violations, best practices violations, BPA

#12915 More secure SSH, update to latest images
  application-workloads/traefik/docker-portainer-traefik-windows-vm/azuredeploy.json
  application-workloads/traefik/docker-portainer-traefik-windows-vm/azuredeploy.parameters.json
  application-workloads/traefik/docker-portainer-traefik-windows-vm/configs/docker-compose.yml.template
  application-workloads/traefik/docker-portainer-traefik-windows-vm/configs/sshd_config_wopwd
  application-workloads/traefik/docker-portainer-traefik-windows-vm/createUiDefinition.json
  application-workloads/traefik/docker-portainer-traefik-windows-vm/initialize.ps1
  application-workloads/traefik/docker-portainer-traefik-windows-vm/metadata.json
  application-workloads/traefik/docker-portainer-traefik-windows-vm/setup.ps1
Labels: BPA

#12869 Added Template to create New Slice
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-slice/README.md
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-slice/azuredeploy.parameters.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-slice/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-slice/metadata.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-slice/prereqs/.settings.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-slice/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-slice/prereqs/prereq.azuredeploy.parameters.json
Labels: remove azuredeploy.json

#12929 Fix userplane metrics query to support Packet Core 4.17
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-dashboard/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-dashboard/metadata.json
Labels: best practices violations

#12925 Dapr Container App - Pub Sub w/ServiceBus
  quickstarts/microsoft.app/container-app-dapr-pubsub-servicebus/README.md
  quickstarts/microsoft.app/container-app-dapr-pubsub-servicebus/azuredeploy.parameters.json
  quickstarts/microsoft.app/container-app-dapr-pubsub-servicebus/main.bicep
  quickstarts/microsoft.app/container-app-dapr-pubsub-servicebus/metadata.json
Labels: best practices violations, BPA

#12931 Updating bicep file to GAed regions for the AHDS.
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/README.md
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
Labels: BPA

#12822 adding template for command job
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-or-update-job/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-or-update-job/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-or-update-job/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-or-update-job/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-or-update-job/prereqs/.settings.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-or-update-job/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-job-create-or-update-job/prereqs/prereq.azuredeploy.parameters.json
Labels: bicep warnings, BPA, remove azuredeploy.json

#12933 Resolving links
  quickstarts/microsoft.azurepurview/azure-purview-deployment/README.md
Labels: bicep warnings

#12910 Only support ASE install for mobilenetwork-create-full-5gc-deployment
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/README.md
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/azuredeploy.parameters.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/metadata.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/prereqs/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/prereqs/prereq.main.bicep
Labels: bicep warnings, duplicate metadata

#12941 Update sql-logical-server quickstart with new SQL advancedThreatProtectionSettings API
  quickstarts/microsoft.sql/sql-logical-server/README.md
  quickstarts/microsoft.sql/sql-logical-server/azuredeploy.json
  quickstarts/microsoft.sql/sql-logical-server/metadata.json
Labels: best practices violations, BPA

#12943 Update interface name helptext
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/main.bicep
Labels: best practices violations, bicep warnings, duplicate metadata

#12948 Disable allowBlobPublicAccess to storage account
  quickstarts/microsoft.web/function-app-storage-private-endpoints/main.bicep
  quickstarts/microsoft.web/function-app-storage-private-endpoints/metadata.json
Labels: BPA
