Repository Azure/azure-quickstart-templates, pull requests merged in 2022-05, with the labels that each got.

#12421 update keyvault exp property
  modules/Microsoft.KeyVault/vaults/keys/0.9/azuredeploy.json
Labels: UPPERCASE

#12436 add default location to dashboard
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-dashboard/azuredeploy.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-dashboard/azuredeploy.parameters.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-dashboard/main.bicep
Labels: best practices violations

#12451 Pipeline Test
  quickstarts/microsoft.eventgrid/event-grid/README.md
  quickstarts/microsoft.eventgrid/event-grid/main.bicep
  quickstarts/microsoft.eventgrid/event-grid/metadata.json
  quickstarts/microsoft.eventgrid/event-grid/prereqs/prereq.main.bicep
Labels: best practices violations, BPA

#12455 Take ownership of scenario
  subscription-deployments/blueprints-new-blueprint/metadata.json
Labels: manual validation required

#12457 Take ownership of scenario
  quickstarts/microsoft.authorization/azurepolicy-assign-builtinpolicy-resourcegroup/metadata.json
Labels: best practices violations

#12473 added sample
  101-blank-template/README.md
  101-blank-template/azuredeploy.parameters.json
  101-blank-template/main.bicep
  101-blank-template/metadata.json
Labels: ROOT

#12430 Update README.md
  application-workloads/datascience/vm-ubuntu-DSVM-GPU-or-CPU/README.md
Labels: UPPERCASE

#12453 [resource graph] - add the bicep file
  demos/resourcegraph-sharedquery-countos/README.md
  demos/resourcegraph-sharedquery-countos/azuredeploy.json
  demos/resourcegraph-sharedquery-countos/main.bicep
Labels: json with bicep

#12431 eap74-rhel-84-patch1.1
  application-workloads/jboss/jboss-eap-standalone-rhel/README.md
  application-workloads/jboss/jboss-eap-standalone-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-standalone-rhel/metadata.json
  application-workloads/jboss/jboss-eap-standalone-rhel/scripts/jbosseap-setup-redhat.sh
Labels: manual validation required

#12432 eap74-rhel84-multivm-patch1.1
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/README.md
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/metadata.json
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/scripts/jbosseap-setup-redhat.sh
Labels: manual validation required

#12433 eap74-rhel84-vmss-patch1.1
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/README.md
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/metadata.json
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/scripts/jbosseap-setup-redhat.sh
Labels: manual validation required

#12363 Workspace PNA flag update in arm template and bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/bastion.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/containerregistry.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/dsvmjumpbox.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/keyvault.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/machinelearning.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/machinelearningcompute.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/machinelearningnetworking.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/nsg.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/privateaks.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/storage.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-end-to-end-secure/modules/vnet.bicep
Labels: json with bicep

#12481 [Stream Analytics] udpate API version and add Bicep file
  quickstarts/microsoft.streamanalytics/streamanalytics-create/README.md
  quickstarts/microsoft.streamanalytics/streamanalytics-create/azuredeploy.json
  quickstarts/microsoft.streamanalytics/streamanalytics-create/main.bicep
  quickstarts/microsoft.streamanalytics/streamanalytics-create/metadata.json
Labels: json with bicep

#12463 [Signalr] - update api versions and create Bicep file
  quickstarts/microsoft.signalrservice/signalr/README.md
  quickstarts/microsoft.signalrservice/signalr/azuredeploy.json
  quickstarts/microsoft.signalrservice/signalr/main.bicep
  quickstarts/microsoft.signalrservice/signalr/metadata.json
Labels: json with bicep

#12492 [Synapse] update API versions ang create Bicep
  quickstarts/microsoft.sql/sql-data-warehouse-transparent-encryption-create/README.md
  quickstarts/microsoft.sql/sql-data-warehouse-transparent-encryption-create/azuredeploy.json
  quickstarts/microsoft.sql/sql-data-warehouse-transparent-encryption-create/main.bicep
  quickstarts/microsoft.sql/sql-data-warehouse-transparent-encryption-create/metadata.json
Labels: json with bicep

#12495 Update azuredeploy.json
  quickstarts/microsoft.compute/sig-image-version-create/azuredeploy.json
Labels: metadata violations, best practices violations

#12494 Update azuredeploy.json
  quickstarts/microsoft.compute/sig-image-definition-create/azuredeploy.json
Labels: metadata violations, best practices violations

#12500 rebrand sig
  modules/Microsoft.Compute/galleries/create/1.0/README.md
  modules/Microsoft.Compute/galleries/create/1.0/azuredeploy.json
  modules/Microsoft.Compute/galleries/create/1.0/metadata.json
Labels: best practices violations, readme violations, UPPERCASE

#12490 Create Azure NetApp Files resource for SAP HANA Cross Region Replication Storage
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/README.md
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/azuredeploy.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/azuredeploy.parameters.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/metadata.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/prereqs/.settings.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#12491 Update azuredeploy.json
  quickstarts/microsoft.devices/iothub-auto-route-messages/azuredeploy.json
  quickstarts/microsoft.devices/iothub-auto-route-messages/main.bicep
Labels: json with bicep

#12479 eap74-rhel84-vmss-patch2.1
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-clustered-vmss-rhel/metadata.json
Labels: manual validation required

#12507 add server version 4.2 to autoscale
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/README.md
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/azuredeploy.parameters.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/azuredeploy.parameters.us.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-mongodb-autoscale/metadata.json
Labels: decompile clean-up needed, bicep warnings, json with bicep

#12437 add server version 4.2
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/README.md
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/azuredeploy.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/azuredeploy.parameters.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/azuredeploy.parameters.us.json
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-mongodb/metadata.json
Labels: decompile clean-up needed, bicep warnings, json with bicep

#12493 [traffic manager] update API versions and create Bicep file
  quickstarts/microsoft.network/traffic-manager-external-endpoint/README.md
  quickstarts/microsoft.network/traffic-manager-external-endpoint/azuredeploy.json
  quickstarts/microsoft.network/traffic-manager-external-endpoint/main.bicep
  quickstarts/microsoft.network/traffic-manager-external-endpoint/metadata.json
Labels: json with bicep

#12509 Update metadata.json
  application-workloads/datascience/vm-ubuntu-DSVM-GPU-or-CPU/metadata.json
Labels: UPPERCASE

#12504 Creating new Bicep file and updating ARM JSON - Web Application Firewall
  demos/ag-docs-wafv2/README.md
  demos/ag-docs-wafv2/azuredeploy.json
  demos/ag-docs-wafv2/main.bicep
  demos/ag-docs-wafv2/metadata.json
Labels: json with bicep

#12510 Update main.bicep
  application-workloads/datascience/vm-ubuntu-DSVM-GPU-or-CPU/main.bicep
Labels: UPPERCASE

#12503 Updating API versions - Virtual Network Bicep file and ARM template
  quickstarts/microsoft.network/vnet-two-subnets/azuredeploy.json
  quickstarts/microsoft.network/vnet-two-subnets/main.bicep
  quickstarts/microsoft.network/vnet-two-subnets/metadata.json
Labels: json with bicep

#12511 Update metadata.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/metadata.json
Labels: best practices violations
