Repository Azure/azure-quickstart-templates, pull requests merged in 2022-11, with the labels that each got.

#12952 Creating quickstart template for APIM and Redis Cache
  quickstarts/microsoft.apimanagement/api-management-create-with-external-redis-cache/README.md
  quickstarts/microsoft.apimanagement/api-management-create-with-external-redis-cache/azuredeploy.parameters.json
  quickstarts/microsoft.apimanagement/api-management-create-with-external-redis-cache/main.bicep
  quickstarts/microsoft.apimanagement/api-management-create-with-external-redis-cache/metadata.json
Labels: BPA

#12947 Update XSS attack demo to remove SQL ATP old API since it is not used anyway
  demos/xss-attack-prevention/azuredeploy.json
  demos/xss-attack-prevention/metadata.json
  demos/xss-attack-prevention/nested/microsoft.sql/servers.securityalertpolicies.json
Labels: best practices violations, BPA

#12956 Enable Azure Gov for Game Dev VM image
  application-workloads/azure-gamedev/gamedev-vm/README.md
Labels: metadata violations, best practices violations, readme violations

#12960 Modify virtual network integration approach.
  quickstarts/microsoft.web/function-premium-vnet-integration/README.md
  quickstarts/microsoft.web/function-premium-vnet-integration/azuredeploy.json
  quickstarts/microsoft.web/function-premium-vnet-integration/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-premium-vnet-integration/azuredeploy.parameters.us.json
  quickstarts/microsoft.web/function-premium-vnet-integration/main.bicep
  quickstarts/microsoft.web/function-premium-vnet-integration/metadata.json
Labels: BPA

#12844 Update GameDev to use Bicep Module
  application-workloads/azure-gamedev/gamedev-vm/README.md
  application-workloads/azure-gamedev/gamedev-vm/main.bicep
  application-workloads/azure-gamedev/gamedev-vm/metadata.json
Labels: best practices violations, BPA

#12965 Adding serverless Cosmos DB Bicep sample
  quickstarts/microsoft.documentdb/cosmosdb-sql-serverless/README.md
  quickstarts/microsoft.documentdb/cosmosdb-sql-serverless/azuredeploy.parameters.json
  quickstarts/microsoft.documentdb/cosmosdb-sql-serverless/main.bicep
  quickstarts/microsoft.documentdb/cosmosdb-sql-serverless/metadata.json
Labels: BPA

#12963 Update quickstart - front-door-premium-storage-blobs-private-link - Add WAF
  quickstarts/microsoft.cdn/front-door-premium-storage-blobs-private-link/README.md
  quickstarts/microsoft.cdn/front-door-premium-storage-blobs-private-link/azuredeploy.json
  quickstarts/microsoft.cdn/front-door-premium-storage-blobs-private-link/images/diagram.png
  quickstarts/microsoft.cdn/front-door-premium-storage-blobs-private-link/metadata.json
  quickstarts/microsoft.cdn/front-door-premium-storage-blobs-private-link/modules/front-door.bicep
  quickstarts/microsoft.cdn/front-door-premium-storage-blobs-private-link/modules/storage.bicep
Labels: BPA

#12949 AzureDatabricks-workspace-with-managed-disk-customer-managed-keys
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/README.md
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/azuredeploy.parameters.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/metadata.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/prereqs/prereq.azuredeploy.parameters.json
Labels: readme violations, BPA

#12974 Explicitly disable storage public blob access on workspace creation template
  quickstarts/microsoft.machinelearningservices/machine-learning-private-ip/azuredeploy.json
Labels: metadata violations, best practices violations, BPA

#12973 Explicitly disable storage public blob access on workspace creation template
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet-v1-legacy-mode/azuredeploy.json
Labels: metadata violations, BPA

#12972 Explicitly disable storage public blob access on workspace creation template
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/azuredeploy.json
Labels: metadata violations, best practices violations, BPA

#12970 Explicitly disable storage public blob access on workspace creation template
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace/azuredeploy.json
Labels: metadata violations, best practices violations, BPA, duplicate foldername

#12969 updating api version
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/metadata.json
Labels: BPA

#12971 Explicitly disable storage public blob access on workspace creation template
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-cmk/azuredeploy.json
Labels: metadata violations, best practices violations, BPA

#12980 Update to make READMEs uniform across MedTech
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/README.md
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/metadata.json
Labels: BPA

#12991 1128 machine learning workspace cmk
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-cmk/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-cmk/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-cmk/main.bicep
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-cmk/metadata.json
Labels: best practices violations, BPA

#12975 Mapping Sweden Central to Norway East
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet-v1-legacy-mode/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet-v1-legacy-mode/metadata.json
Labels: BPA

#12993 Changed default values
  demos/aks-nat-agic/azuredeploy.json
  demos/aks-nat-agic/metadata.json
Labels: best practices violations, BPA

#12997 Add Bicep and update API versions
  quickstarts/microsoft.sql/sql-logical-server/README.md
  quickstarts/microsoft.sql/sql-logical-server/azuredeploy.json
  quickstarts/microsoft.sql/sql-logical-server/main.bicep
  quickstarts/microsoft.sql/sql-logical-server/metadata.json
Labels: BPA

#13008 Typo "resouce"→"resource"
  quickstarts/microsoft.appconfiguration/app-configuration-store-ff/README.md
Labels: best practices violations, BPA, duplicate metadata

#13005 Adding bicep pieces
  quickstarts/microsoft.web/webapp-basic-linux/README.md
  quickstarts/microsoft.web/webapp-basic-linux/main.bicep
  quickstarts/microsoft.web/webapp-basic-linux/metadata.json
Labels: BPA

#13004 Update APIs for Storage Blob Container
  quickstarts/microsoft.storage/storage-blob-container/main.bicep
  quickstarts/microsoft.storage/storage-blob-container/metadata.json
Labels: BPA

#13002 Update APIs
  quickstarts/microsoft.sql/sql-database/main.bicep
  quickstarts/microsoft.sql/sql-database/metadata.json
Labels: BPA

#13003 Update APIs Web App B
  quickstarts/microsoft.web/webapp-basic-windows/main.bicep
  quickstarts/microsoft.web/webapp-basic-windows/metadata.json
Labels: duplicate metadata

#13001 Update APIs for Storage
  quickstarts/microsoft.storage/storage-account-create/main.bicep
  quickstarts/microsoft.storage/storage-account-create/metadata.json
Labels: BPA
