Repository Azure/azure-quickstart-templates, pull requests merged in 2023-01, with the labels that each got.

#13048 Function app on Dedicated plan
  quickstarts/microsoft.web/function-app-dedicated-plan/README.md
  quickstarts/microsoft.web/function-app-dedicated-plan/azuredeploy.json
  quickstarts/microsoft.web/function-app-dedicated-plan/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-app-dedicated-plan/metadata.json
Labels: BPA

#13054 New template for Trusted Launch VMSS
  quickstarts/microsoft.compute/vmss-trustedlaunch-windows/README.md
  quickstarts/microsoft.compute/vmss-trustedlaunch-windows/azuredeploy.parameters.json
  quickstarts/microsoft.compute/vmss-trustedlaunch-windows/createUiDefinition.json
  quickstarts/microsoft.compute/vmss-trustedlaunch-windows/main.bicep
  quickstarts/microsoft.compute/vmss-trustedlaunch-windows/metadata.json
Labels: bicep warnings

#13056 App Service secure n-tier web app
  quickstarts/microsoft.web/webapp-secure-ntier/README.md
  quickstarts/microsoft.web/webapp-secure-ntier/azuredeploy.parameters.json
  quickstarts/microsoft.web/webapp-secure-ntier/main.bicep
  quickstarts/microsoft.web/webapp-secure-ntier/metadata.json
Labels: best practices violations, bicep warnings, BPA

#13079 [AD new domain] - update API versions and create Bicep
  application-workloads/active-directory/active-directory-new-domain/README.md
  application-workloads/active-directory/active-directory-new-domain/azuredeploy.json
  application-workloads/active-directory/active-directory-new-domain/main.bicep
  application-workloads/active-directory/active-directory-new-domain/metadata.json
  application-workloads/active-directory/active-directory-new-domain/nestedtemplates/vnet-with-dns-server.bicep
  application-workloads/active-directory/active-directory-new-domain/nestedtemplates/vnet.bicep
Labels: best practices violations, duplicate foldername

#13080 Correct comment referring to App GW instead of KV
  quickstarts/microsoft.resources/deployment-script-azcli-agw-certificates/main.bicep
Labels: best practices violations, bicep warnings, BPA

#13081 Create webapp-windows-privateendpoint-applicationgateway
  quickstarts/microsoft.web/webapp-windows-with-privateendpoint-applicationgateway/README.md
  quickstarts/microsoft.web/webapp-windows-with-privateendpoint-applicationgateway/azuredeploy.parameters.json
  quickstarts/microsoft.web/webapp-windows-with-privateendpoint-applicationgateway/main.bicep
  quickstarts/microsoft.web/webapp-windows-with-privateendpoint-applicationgateway/metadata.json
Labels: BPA

#13083 [iothub-with-consumergroup-create] - update api versions and create B…
  quickstarts/microsoft.devices/iothub-with-consumergroup-create/README.md
  quickstarts/microsoft.devices/iothub-with-consumergroup-create/azuredeploy.json
  quickstarts/microsoft.devices/iothub-with-consumergroup-create/main.bicep
  quickstarts/microsoft.devices/iothub-with-consumergroup-create/metadata.json
Labels: readme violations

#13091 [Azure Databricks] Updated template to support workspace names of 64 characters
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-privateendpoint/azuredeploy.json
Labels: best practices violations

#13092 [Azure Databricks] Updated Load Balancer template to support 64-character workspace names
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-load-balancer/azuredeploy.json
Labels: best practices violations

#13093 [Azure Databricks] Updated NAT gateway template to support 64-character workspace names
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-nat-gateway/azuredeploy.json
Labels: best practices violations

#13094 [Azure Databricks] Updated All-in-one Vnet Injection template to support 64-char workspace names
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection/azuredeploy.json
Labels: best practices violations, remove azuredeploy.json

#13096 [Azure Databricks] Updated CMK template to support 64-char workspace names
  quickstarts/microsoft.databricks/databricks-workspace-with-customer-managed-keys/azuredeploy.json
Labels: remove azuredeploy.json

#13097 [Azure Databricks] Updated Managed Disk CMK template to support 64-char workspace names
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/azuredeploy.json
Labels: remove azuredeploy.json

#13098 [Azure Databricks] Updated VNet Injection template to support 64-char workspace names
  quickstarts/microsoft.databricks/databricks-workspace-with-vnet-injection/azuredeploy.json
Labels: best practices violations

#13099 [Azure Databricks] Updated standard template to support 64-char workspace names
  quickstarts/microsoft.databricks/databricks-workspace/azuredeploy.json
Labels: remove azuredeploy.json

#13067 Add template: 3 VMS 1 Subnet
  demos/2fe-lb80-rdp-1be-nsg-rdp/azuredeploy.json
Labels: best practices violations, BPA

#13061 Add ARM templates for Mariner on AKS
  quickstarts/microsoft.kubernetes/aks-mariner/azuredeploy.json
  quickstarts/microsoft.kubernetes/aks-mariner/azuredeploy.parameters.json
  quickstarts/microsoft.kubernetes/aks-mariner/metadata.json
Labels: readme violations, BPA

#13058 App Service multi-region web app
  quickstarts/microsoft.web/webapp-multi-region-front-door/README.md
  quickstarts/microsoft.web/webapp-multi-region-front-door/azuredeploy.parameters.json
  quickstarts/microsoft.web/webapp-multi-region-front-door/main.bicep
  quickstarts/microsoft.web/webapp-multi-region-front-door/metadata.json
Labels: best practices violations, bicep warnings

#13102 add azuredeploy.json
  application-workloads/active-directory/active-directory-new-domain/azuredeploy.json
Labels: best practices violations, remove azuredeploy.json, duplicate foldername

#13106 [Azure Databricks] Updated Managed Disk CMK template to support 64 char workspace names
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/main.bicep
Labels: bicep warnings

#13104 [Azure Databricks] Updated all-in-one Vnet Injection template to support 64 character wo…
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection/main.bicep
Labels: best practices violations, bicep warnings

#13103 [Azure Databricks] Updated vanilla template to support 64 character workspaces
  quickstarts/microsoft.databricks/databricks-workspace/main.bicep
Labels: bicep warnings

#13089 [openScholar] - update API versions and add Bicep
  application-workloads/openscholar/openscholar/README.md
  application-workloads/openscholar/openscholar/azuredeploy.json
  application-workloads/openscholar/openscholar/main.bicep
  application-workloads/openscholar/openscholar/metadata.json
Labels: duplicate foldername

#13088 [webapp-linux-flask] - update api versions and add Bicep
  quickstarts/microsoft.web/webapp-linux-flask/README.md
  quickstarts/microsoft.web/webapp-linux-flask/azuredeploy.json
  quickstarts/microsoft.web/webapp-linux-flask/main.bicep
  quickstarts/microsoft.web/webapp-linux-flask/metadata.json
Labels: BPA

#13087 [webapp-linux-django] - update API versions and add Bicep
  quickstarts/microsoft.web/webapp-linux-django/README.md
  quickstarts/microsoft.web/webapp-linux-django/azuredeploy.json
  quickstarts/microsoft.web/webapp-linux-django/main.bicep
  quickstarts/microsoft.web/webapp-linux-django/metadata.json
Labels: BPA

#13086 [app-function] - update api versions and add Bicep
  quickstarts/microsoft.web/app-function/README.md
  quickstarts/microsoft.web/app-function/azuredeploy.json
  quickstarts/microsoft.web/app-function/main.bicep
  quickstarts/microsoft.web/app-function/metadata.json
Labels: BPA

#13084 [web-app-java-tomcat] - update api versions and add Bicep
  quickstarts/microsoft.web/web-app-java-tomcat/README.md
  quickstarts/microsoft.web/web-app-java-tomcat/azuredeploy.json
  quickstarts/microsoft.web/web-app-java-tomcat/main.bicep
  quickstarts/microsoft.web/web-app-java-tomcat/metadata.json
Labels: BPA

#13118 format the json files
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/azuredeploy.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/azuredeploy.parameters.json
Labels: best practices violations, BPA

#13113 [jboss eap clustered multivm rhel] - update API versions and add Bicep
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/README.md
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/azuredeploy.json
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/main.bicep
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/metadata.json
  application-workloads/jboss/jboss-eap-clustered-multivm-rhel/nested_guid.bicep
Labels: manual validation required, BPA

#13122 update sku
  application-workloads/active-directory/active-directory-new-domain/main.bicep
  application-workloads/active-directory/active-directory-new-domain/metadata.json
Labels: best practices violations, duplicate foldername

#13124 [load balancer gateway] - update api versions and add Bicep
  demos/load-balancer-gateway/README.md
  demos/load-balancer-gateway/azuredeploy.json
  demos/load-balancer-gateway/main.bicep
  demos/load-balancer-gateway/metadata.json
Labels: BPA

#13108 PacketCoreControlPlane Slice Dependency changes
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/azuredeploy.parameters.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, BPA, remove azuredeploy.json

#13111 Making changes to follow best practice
  quickstarts/microsoft.web/webapp-windows-with-privateendpoint-applicationgateway/README.md
  quickstarts/microsoft.web/webapp-windows-with-privateendpoint-applicationgateway/main.bicep
Labels: BPA

#13119 Add Bicep to Hub Spoke Bastion template
  quickstarts/microsoft.network/bastion-hub-spoke-vnet/README.md
  quickstarts/microsoft.network/bastion-hub-spoke-vnet/azuredeploy.json
  quickstarts/microsoft.network/bastion-hub-spoke-vnet/azuredeploy.parameters.json
  quickstarts/microsoft.network/bastion-hub-spoke-vnet/main.bicep
  quickstarts/microsoft.network/bastion-hub-spoke-vnet/metadata.json
Labels: BPA, remove azuredeploy.json

#13120 Add Bicep to Bastion NSG template
  quickstarts/microsoft.network/azure-bastion-nsg/README.md
  quickstarts/microsoft.network/azure-bastion-nsg/azuredeploy.json
  quickstarts/microsoft.network/azure-bastion-nsg/azuredeploy.parameters.json
  quickstarts/microsoft.network/azure-bastion-nsg/main.bicep
  quickstarts/microsoft.network/azure-bastion-nsg/metadata.json
Labels: remove azuredeploy.json

#13143 [Azure Databricks] Renamed DBFS CMK template folder
  quickstarts/microsoft.databricks/databricks-workspace-with-dbfs-root-customer-managed-keys/README.md
  quickstarts/microsoft.databricks/databricks-workspace-with-dbfs-root-customer-managed-keys/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace-with-dbfs-root-customer-managed-keys/azuredeploy.parameters.json
  quickstarts/microsoft.databricks/databricks-workspace-with-dbfs-root-customer-managed-keys/main.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-dbfs-root-customer-managed-keys/metadata.json
  quickstarts/microsoft.databricks/databricks-workspace-with-dbfs-root-customer-managed-keys/nested_addAccessPolicy.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-dbfs-root-customer-managed-keys/nested_configureCMKOnWorkspace.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-dbfs-root-customer-managed-keys/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace-with-dbfs-root-customer-managed-keys/prereqs/prereq.azuredeploy.parameters.json
Labels: readme violations, bicep warnings, remove azuredeploy.json

#13074 Function App with Private Endpoint Secured Azure Storage
  quickstarts/microsoft.web/function-app-storage-private-endpoints/README.md
  quickstarts/microsoft.web/function-app-storage-private-endpoints/azuredeploy.json
  quickstarts/microsoft.web/function-app-storage-private-endpoints/main.bicep
Labels: BPA

#13049 Function app and storage account with private endpoints
  quickstarts/microsoft.web/function-app-private-endpoints-storage-private-endpoints/README.md
  quickstarts/microsoft.web/function-app-private-endpoints-storage-private-endpoints/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-app-private-endpoints-storage-private-endpoints/images/function-app-private-endpoints-storage-private-endpoints.jpg
  quickstarts/microsoft.web/function-app-private-endpoints-storage-private-endpoints/main.bicep
  quickstarts/microsoft.web/function-app-private-endpoints-storage-private-endpoints/metadata.json
Labels: BPA

#13051 Function app with deployment slot
  quickstarts/microsoft.web/function-app-deployment-slot/README.md
  quickstarts/microsoft.web/function-app-deployment-slot/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-app-deployment-slot/main.bicep
  quickstarts/microsoft.web/function-app-deployment-slot/metadata.json
Labels: BPA

#13052 Function app on Windows Consumption plan
  quickstarts/microsoft.web/function-app-windows-consumption/README.md
  quickstarts/microsoft.web/function-app-windows-consumption/azuredeploy.json
  quickstarts/microsoft.web/function-app-windows-consumption/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-app-windows-consumption/metadata.json
Labels: BPA

#13071 Function app on Premium plan
  quickstarts/microsoft.web/function-app-premium-plan/README.md
  quickstarts/microsoft.web/function-app-premium-plan/azuredeploy.json
  quickstarts/microsoft.web/function-app-premium-plan/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-app-premium-plan/metadata.json
Labels: BPA

#13072 Function app on Linux Consumption plan
  quickstarts/microsoft.web/function-app-linux-consumption/README.md
  quickstarts/microsoft.web/function-app-linux-consumption/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-app-linux-consumption/main.bicep
  quickstarts/microsoft.web/function-app-linux-consumption/metadata.json
Labels: BPA

#13073 Function app on Linux Consumption plan with Remote Build
  quickstarts/microsoft.web/function-app-linux-consumption-remote-build/README.md
  quickstarts/microsoft.web/function-app-linux-consumption-remote-build/azuredeploy.json
  quickstarts/microsoft.web/function-app-linux-consumption-remote-build/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-app-linux-consumption-remote-build/metadata.json
Labels: BPA

#13144 Update main.bicep
  quickstarts/microsoft.storage/storage-account-create/main.bicep
Labels: BPA

#13152 Updates and edits
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/README.md
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/metadata.json
Labels: BPA

#13154 fixing broken links
  application-workloads/concourse/concourse-ci/README.md
Labels: best practices violations, BPA
