Repository Azure/azure-quickstart-templates, pull requests merged in 2023-09, with the labels that each got.

#13540 Add deployment script AzPwsh inputs/outputs sample
  quickstarts/microsoft.resources/deployment-script-azpwsh-inputs-outputs/README.md
  quickstarts/microsoft.resources/deployment-script-azpwsh-inputs-outputs/azuredeploy.parameters.json
  quickstarts/microsoft.resources/deployment-script-azpwsh-inputs-outputs/main.bicep
  quickstarts/microsoft.resources/deployment-script-azpwsh-inputs-outputs/metadata.json
  quickstarts/microsoft.resources/deployment-script-azpwsh-inputs-outputs/script.ps1
Labels: best practices violations

#13541 Add deployment script AzCli inputs/outputs sample
  quickstarts/microsoft.resources/deployment-script-azcli-inputs-outputs/README.md
  quickstarts/microsoft.resources/deployment-script-azcli-inputs-outputs/azuredeploy.parameters.json
  quickstarts/microsoft.resources/deployment-script-azcli-inputs-outputs/main.bicep
  quickstarts/microsoft.resources/deployment-script-azcli-inputs-outputs/metadata.json
  quickstarts/microsoft.resources/deployment-script-azcli-inputs-outputs/script.sh
Labels: best practices violations

#13546 Updating Datadog template
  quickstarts/microsoft.datadog/datadog/azuredeploy.json
Labels: manual validation required, best practices violations

#13509 Add quick start template for dev box and customized image with low feilds
  quickstarts/microsoft.devcenter/devbox-with-customized-image/README.md
  quickstarts/microsoft.devcenter/devbox-with-customized-image/abbreviations.json
  quickstarts/microsoft.devcenter/devbox-with-customized-image/assets/customized-command.png
  quickstarts/microsoft.devcenter/devbox-with-customized-image/assets/deployment-page.png
  quickstarts/microsoft.devcenter/devbox-with-customized-image/azuredeploy.parameters.json
  quickstarts/microsoft.devcenter/devbox-with-customized-image/customized-image/customized-image.bicep
  quickstarts/microsoft.devcenter/devbox-with-customized-image/customized-image/customized-image.json
  quickstarts/microsoft.devcenter/devbox-with-customized-image/main.bicep
  quickstarts/microsoft.devcenter/devbox-with-customized-image/metadata.json
  quickstarts/microsoft.devcenter/devbox-with-customized-image/modules/devcenter-settings.json
  quickstarts/microsoft.devcenter/devbox-with-customized-image/modules/devcenter.bicep
  quickstarts/microsoft.devcenter/devbox-with-customized-image/modules/gallery.bicep
  quickstarts/microsoft.devcenter/devbox-with-customized-image/modules/vnet.bicep
  quickstarts/microsoft.devcenter/devbox-with-customized-image/scripts/enable-devcenter.ps1
  quickstarts/microsoft.devcenter/devbox-with-customized-image/start.ps1
Labels: best practices violations, BPA

#13538 Update README.md for Azure API Management
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/README.md
Labels: BPA

#13542 fixed non-closed a href
  demos/application-gateway-logviewer-goaccess/README.md
Labels: best practices violations

#13555 Remove Gen1 pricing from the template
  quickstarts/microsoft.maps/maps-use-sas/azuredeploy.json
  quickstarts/microsoft.maps/maps-use-sas/metadata.json
Labels: best practices violations

#13564 Remove azure govt us deploy button
  quickstarts/microsoft.elastic/elastic-create/README.md
  quickstarts/microsoft.elastic/elastic-create/azuredeploy.json
  quickstarts/microsoft.elastic/elastic-create/azuredeploy.parameters.json
Labels: best practices violations, readme violations

#13565 Restoring deleted file
  quickstarts/microsoft.compute/2-vms-loadbalancer-lbrules/azuredeploy.json
Labels: best practices violations, BPA

#13563 fix sku failure due to the new change
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/README.md
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/azuredeploy.json
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/azuredeploy.parameters.json
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/metadata.json
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/modules/devcenter-settings.json
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/modules/devcenter.bicep
Labels: BPA

#13405 Azure Stack HCI VM at a Custom Path
  quickstarts/microsoft.azurestackhci/vm-windows-storage-container/README.md
  quickstarts/microsoft.azurestackhci/vm-windows-storage-container/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/vm-windows-storage-container/main.bicep
  quickstarts/microsoft.azurestackhci/vm-windows-storage-container/metadata.json
  quickstarts/microsoft.azurestackhci/vm-windows-storage-container/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/vm-windows-storage-container/prereq.main.bicep
Labels: manual validation required

#13557 hard code valid image URNs
  quickstarts/microsoft.azurestackhci/image-from-azure-marketplace/README.md
  quickstarts/microsoft.azurestackhci/image-from-azure-marketplace/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/image-from-azure-marketplace/main.bicep
Labels: manual validation required

#13558 Stack HCI Storage Container/Path
  quickstarts/microsoft.azurestackhci/storage-container/README.md
  quickstarts/microsoft.azurestackhci/storage-container/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/storage-container/main.bicep
  quickstarts/microsoft.azurestackhci/storage-container/metadata.json
Labels: manual validation required

#13577 Exposing npip parameter to cmk ms
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-services-customer-managed-keys/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-services-customer-managed-keys/azuredeploy.parameters.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-services-customer-managed-keys/main.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-services-customer-managed-keys/nested_addAccessPolicy.bicep
Labels: best practices violations, bicep warnings, remove azuredeploy.json

#13349 Azure Stack HCI Virtual Machine
  quickstarts/microsoft.azurestackhci/vm-simple-windows/README.md
  quickstarts/microsoft.azurestackhci/vm-simple-windows/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/vm-simple-windows/main.bicep
  quickstarts/microsoft.azurestackhci/vm-simple-windows/metadata.json
  quickstarts/microsoft.azurestackhci/vm-simple-windows/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/vm-simple-windows/prereq.main.bicep
Labels: manual validation required, duplicate foldername
