Repository Azure/azure-quickstart-templates, pull requests merged in 2023-06, with the labels that each got.

#13352 enable Trusted Launch
  quickstarts/microsoft.compute/vm-windows-ssh/main.bicep
Labels: best practices violations, BPA

#13357 Dev/ksadhana/quickstart temp/6.azurefirewall premium
  quickstarts/microsoft.network/azurefirewall-premium/main.bicep
Labels: best practices violations, readme violations, bicep warnings

#13358 Dev/ksadhana/quickstart temp/7.sql vm new storage
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-new-storage/main.bicep
Labels: best practices violations

#13360 Dev/ksadhana/quickstart temp/9.azurefirewall sandbox linux
  quickstarts/microsoft.network/azurefirewall-sandbox-linux/azuredeploy.json
Labels: best practices violations, BPA

#13361 Dev/ksadhana/quickstart temp/11.multi vm lb zones
  quickstarts/microsoft.compute/multi-vm-lb-zones/azuredeploy.json
Labels: best practices violations, bicep warnings, BPA

#13417 Add install odbc function for TP
  application-workloads/sccm/sccm-technicalpreview/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-technicalpreview/DSC/PSConfiguration.ps1
  application-workloads/sccm/sccm-technicalpreview/DSC/TemplateHelpDSC/TemplateHelpDSC.psd1
  application-workloads/sccm/sccm-technicalpreview/DSC/TemplateHelpDSC/TemplateHelpDSC.psm1
Labels: best practices violations

#13363 Dev/ksadhana/13.vm msi storage roleassignementissue
  quickstarts/microsoft.compute/vm-msi-storage/azuredeploy.json
Labels: best practices violations, BPA

#13368 enable trusted launch custom script extension : change type handler …
  quickstarts/microsoft.compute/vmss-azure-files-linux/azuredeploy.json
  quickstarts/microsoft.compute/vmss-azure-files-linux/azuredeploy.parameters.json
Labels: best practices violations

#13376 Enabling Trusted Launch
  quickstarts/microsoft.network/azure-firewall-dns-proxy/azuredeploy.json
Labels: best practices violations, BPA

#13377 Enable Trusted Launch
  quickstarts/microsoft.compute/vm-msi/azuredeploy.json
  quickstarts/microsoft.compute/vm-msi/nestedtemplates/createVM.json
Labels: best practices violations, BPA

#13388 Enabling Trusted Launch
  quickstarts/microsoft.compute/1-vm-loadbalancer-2-nics/azuredeploy.json
  quickstarts/microsoft.compute/1-vm-loadbalancer-2-nics/azuredeploy.parameters.json
Labels: best practices violations, BPA

#13411 enabling option to select security type as TL or standard
  quickstarts/microsoft.compute/vm-with-rdp-port/azuredeploy.json
Labels: best practices violations, BPA

#13413 enabling option to select security type as TL or standard
  quickstarts/microsoft.compute/vm-new-or-existing-conditions/azuredeploy.json
Labels: best practices violations, BPA

#13414 Typo "Azure CosmosDB"→"Azure Cosmos DB"
  quickstarts/microsoft.documentdb/cosmosdb-create-account/README.md
Labels: best practices violations, BPA

#13419 Enabling Trusted Launch
  quickstarts/microsoft.network/load-balancer-standard-create/azuredeploy.json
Labels: remove azuredeploy.json

#13420 enabling trusted launch
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/azuredeploy.json
Labels: best practices violations, BPA, remove azuredeploy.json

#13422 enabling option to select security type as Trusted launch or standard
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-new-storage/azuredeploy.json
Labels: best practices violations, remove azuredeploy.json

#13423 enabling option to option to select security type
  quickstarts/microsoft.compute/vm-windows-ssh/azuredeploy.json
Labels: best practices violations, BPA, remove azuredeploy.json

#13425 Enable trusted Launch
  quickstarts/microsoft.compute/vm-push-certificate-windows/azuredeploy.json
Labels: best practices violations

#13426 Enable option to select security Profile as std or TL
  quickstarts/microsoft.sqlvirtualmachine/sql-vm-new-storage/main.bicep
Labels: best practices violations

#13427 Enable option to select security type as std and TL
  quickstarts/microsoft.compute/vmss-with-public-ip-prefix/main.bicep
Labels: best practices violations, BPA

#13428 enable option to select security profile as std or TL
  quickstarts/microsoft.compute/vm-windows-ssh/main.bicep
Labels: best practices violations, BPA

#13431 Add new Dev Box service template with built-in image
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/README.md
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/abbreviations.json
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/azuredeploy.json
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/azuredeploy.parameters.json
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/main.bicep
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/metadata.json
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/modules/devcenter-settings.json
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/modules/devcenter.bicep
  quickstarts/microsoft.devcenter/devbox-with-builtin-image/modules/vnet.bicep
Labels: readme violations, remove azuredeploy.json

#13359 Dev/ksadhana/quickstart temp/8.aks application gateway ingress controller
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/azuredeploy.json
Labels: best practices violations, BPA

#13432 Fix: Broken Image link for api-management-logs-to-moesif-using-eventh…
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/README.md
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/images/azure-api-management-logging-architecture-diagram.png
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/metadata.json
Labels: BPA

#13434 #185404977 : Commented base element because it is not supported in gl…
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/README.md
Labels: BPA

#13442 Add appinsights swap for qatarcentral
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-vnet/azuredeploy.json
Labels: bicep warnings, BPA, remove azuredeploy.json

#13435 Azure Function with Event Hub and Storage using managed identity
  quickstarts/microsoft.web/function-app-event-hub-managed-identity/README.md
  quickstarts/microsoft.web/function-app-event-hub-managed-identity/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-app-event-hub-managed-identity/main.bicep
  quickstarts/microsoft.web/function-app-event-hub-managed-identity/metadata.json
Labels: BPA

#13438 Azure APIM Template: Mention how upgrade happens
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/README.md
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/apis/policies.bicep
Labels: BPA

#13443 Changed default values to match new diagrams and removed public IP address from virtual machine and simplified nat gateway setup
  quickstarts/microsoft.network/nat-gateway-1-vm/azuredeploy.json
Labels: best practices violations, BPA, remove azuredeploy.json
