Repository Azure/azure-quickstart-templates, pull requests merged in 2023-07, with the labels that each got.

#13199 [BULK] Replace incorrect "AlwaysOn" with "availability group"
  application-workloads/sql/aks-sql-server-always-on/metadata.json
Labels: best practices violations, BPA

#13447 Fix typo.
  quickstarts/microsoft.web/function-app-event-hub-managed-identity/README.md
Labels: BPA

#13449 [BULK] Replace incorrect "AlwaysOn" with "availability group"
  demos/asr-automation-recovery/README.md
  demos/asr-automation-recovery/scripts/ASR-SQL-FailoverAG.ps1
  demos/asr-automation-recovery/scripts/ASR-SQL-FailoverAGClassic.ps1
Labels: best practices violations, BPA

#13451 [BULK] Replace incorrect "AlwaysOn" with "availability group"
  application-workloads/sql/sqlvm-alwayson-cluster/README.md
  application-workloads/sql/sqlvm-alwayson-cluster/azuredeploy.json
  application-workloads/sql/sqlvm-alwayson-cluster/metadata.json
Labels: best practices violations, BPA

#13452 [BULK] Replace incorrect "AlwaysOn" with "availability group"
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/README.md
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/azuredeploy.json
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/metadata.json
Labels: best practices violations

#13456 Cost Management optimization-workbook template docs update
  quickstarts/microsoft.costmanagement/optimization-workbook/README.md
  quickstarts/microsoft.costmanagement/optimization-workbook/metadata.json
Labels: best practices violations

#13458 update for public IP AZ support
  quickstarts/microsoft.network/site-to-site-vpn-fqdn-bgp/azuredeploy.json
Labels: best practices violations, BPA

#13464 Jjoshi/update5 gc deployment
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/metadata.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/prereqs/prereq.azuredeploy.json
Labels: bicep warnings, remove azuredeploy.json

#13468 Updated CreateSimPolicy quickstarts with June API
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-sim-policy/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-sim-policy/metadata.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-sim-policy/prereqs/prereq.azuredeploy.json
Labels: remove azuredeploy.json

#13469 Updated Provision Proxy Sims quickstarts with June API
  quickstarts/microsoft.mobilenetwork/mobilenetwork-provision-proxy-sims/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-provision-proxy-sims/prereqs/prereq.azuredeploy.json
Labels: bicep warnings, BPA, remove azuredeploy.json

#13470 Updated UpdatePCCP with June API and new Core Network Technology
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/azuredeploy.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/createUiDefinition.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/metadata.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-update-packet-core-control-plane/prereqs/prereq.azuredeploy.json
Labels: best practices violations, BPA, remove azuredeploy.json

#13472 00712 vmss azure files linus
  quickstarts/microsoft.compute/vmss-azure-files-linux/README.md
  quickstarts/microsoft.compute/vmss-azure-files-linux/azuredeploy.json
  quickstarts/microsoft.compute/vmss-azure-files-linux/main.bicep
  quickstarts/microsoft.compute/vmss-azure-files-linux/metadata.json
Labels: BPA

#13473 vmss-windows-app-gateway
  quickstarts/microsoft.compute/vmss-windows-app-gateway/README.md
  quickstarts/microsoft.compute/vmss-windows-app-gateway/azuredeploy.json
  quickstarts/microsoft.compute/vmss-windows-app-gateway/main.bicep
  quickstarts/microsoft.compute/vmss-windows-app-gateway/metadata.json
Labels: BPA

#13474 Changed values to match diagram and simplified NAT gateway deployment
  quickstarts/microsoft.network/nat-gateway-1-vm/main.bicep
Labels: best practices violations, BPA

#13475 vm-msi-storage
  quickstarts/microsoft.compute/vm-msi-storage/README.md
  quickstarts/microsoft.compute/vm-msi-storage/azuredeploy.json
  quickstarts/microsoft.compute/vm-msi-storage/main.bicep
  quickstarts/microsoft.compute/vm-msi-storage/metadata.json
  quickstarts/microsoft.compute/vm-msi-storage/nested_assignRole.bicep
Labels: best practices violations, bicep warnings, BPA

#13404 Virtual Network Manager Creation Template - Bicep
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/README.md
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/azuredeploy.parameters.json
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/azuredeploy.parameters.us.json
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/main.bicep
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/metadata.json
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/modules/avnm.bicep
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/modules/avnmDeploymentScript.bicep
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/modules/dynMemberPolicy.bicep
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/modules/hub.bicep
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/modules/spoke.bicep
Labels: manual validation required, metadata violations, best practices violations, readme violations

#13465 Updated CreateNewSlice with June API
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-slice/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-slice/prereqs/prereq.azuredeploy.json
Labels: remove azuredeploy.json

#13467 Updated CreateNewSite quickstarts with June API
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-site/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-site/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-new-site/prereqs/prereq.main.bicep
Labels: remove azuredeploy.json

#13479 Typo about Data Warehouse
  application-workloads/sql/sqlvm-alwayson-cluster/azuredeploy.json
Labels: best practices violations, BPA

#13445 Adding quick start template for 'microsoft.datadog' create new datadog
  quickstarts/microsoft.datadog/datadog/README.md
  quickstarts/microsoft.datadog/datadog/azuredeploy.json
  quickstarts/microsoft.datadog/datadog/azuredeploy.parameters.json
  quickstarts/microsoft.datadog/datadog/createUiDefinition.json
  quickstarts/microsoft.datadog/datadog/metadata.json
Labels: manual validation required, best practices violations

#13444 Adding QuickStart json template to create a 'microsoft.elastic' resource.
  quickstarts/microsoft.elastic/elastic-create/README.md
  quickstarts/microsoft.elastic/elastic-create/azuredeploy.json
  quickstarts/microsoft.elastic/elastic-create/azuredeploy.parameters.json
  quickstarts/microsoft.elastic/elastic-create/createUiDefinition.json
  quickstarts/microsoft.elastic/elastic-create/metadata.json
Labels: best practices violations

#13471 vm-push-certificate-windows
  quickstarts/microsoft.compute/vm-push-certificate-windows/README.md
  quickstarts/microsoft.compute/vm-push-certificate-windows/azuredeploy.json
  quickstarts/microsoft.compute/vm-push-certificate-windows/main.bicep
  quickstarts/microsoft.compute/vm-push-certificate-windows/metadata.json
Labels: best practices violations

#13480 site-to-site-vpn-fqdn-bgp
  quickstarts/microsoft.network/site-to-site-vpn-fqdn-bgp/README.md
  quickstarts/microsoft.network/site-to-site-vpn-fqdn-bgp/azuredeploy.json
  quickstarts/microsoft.network/site-to-site-vpn-fqdn-bgp/main.bicep
  quickstarts/microsoft.network/site-to-site-vpn-fqdn-bgp/metadata.json
Labels: decompile clean-up needed, BPA

#13482 asr-automation-recovery
  demos/asr-automation-recovery/README.md
  demos/asr-automation-recovery/azuredeploy.json
  demos/asr-automation-recovery/main.bicep
  demos/asr-automation-recovery/metadata.json
Labels: bicep warnings, BPA

#13491 Updating naming convention for template for 'microsoft.elastic' to fix createUI
  quickstarts/microsoft.elastic/elastic-create/azuredeploy.json
  quickstarts/microsoft.elastic/elastic-create/azuredeploy.parameters.json
  quickstarts/microsoft.elastic/elastic-create/createUiDefinition.json
  quickstarts/microsoft.elastic/elastic-create/metadata.json
Labels: best practices violations

#13492 Making CreateUIDefinition functional
  quickstarts/microsoft.elastic/elastic-create/createUiDefinition.json
Labels: best practices violations

#13496 Updating the variable name to location
  quickstarts/microsoft.elastic/elastic-create/azuredeploy.json
  quickstarts/microsoft.elastic/elastic-create/azuredeploy.parameters.json
  quickstarts/microsoft.elastic/elastic-create/createUiDefinition.json
Labels: best practices violations

#13494 Changing the variable name to location
  quickstarts/microsoft.datadog/datadog/azuredeploy.json
  quickstarts/microsoft.datadog/datadog/azuredeploy.parameters.json
  quickstarts/microsoft.datadog/datadog/createUiDefinition.json
Labels: manual validation required, best practices violations
