Repository Azure/azure-quickstart-templates, pull requests merged in 2023-12, with the labels that each got.

#13648 Adding ARM template for ABC center alert
  quickstarts/microsoft.azurebusinesscontinuity/business-continuity-latest-recovery-point-age-alerts/README.md
  quickstarts/microsoft.azurebusinesscontinuity/business-continuity-latest-recovery-point-age-alerts/azuredeploy.json
  quickstarts/microsoft.azurebusinesscontinuity/business-continuity-latest-recovery-point-age-alerts/azuredeploy.parameters.json
  quickstarts/microsoft.azurebusinesscontinuity/business-continuity-latest-recovery-point-age-alerts/metadata.json
Labels: manual validation required

#13663 Fix typo
  demos/dsc-extension-iis-server-windows-vm/metadata.json
Labels: best practices violations

#13662 Fix typo
  demos/azure-resource-optimization-toolkit/scripts/AutoUpdateWorker.ps1
Labels: best practices violations, BPA

#13658 Fix typo
  application-workloads/mysql/mysql-ha-pxc-zones/azurepxc.sh
Labels: best practices violations, BPA

#13657 Fix typo
  application-workloads/mysql/mysql-ha-pxc/azurepxc.sh
Labels: best practices violations

#13654 Fix typo
  application-workloads/gluster/gluster-file-system/azuregfs.sh
Labels: best practices violations

#13665 Fix typo
  application-workloads/puppet/puppet-agent-linux/README.md
Labels: best practices violations, BPA

#13668 Fix typo
  demos/azure-resource-optimization-toolkit/README.md
Labels: best practices violations, BPA

#13667 Fix typo
  demos/aci-bc/README.md
Labels: best practices violations

#13669 Fix typo
  quickstarts/microsoft.compute/customscript-extension-public-storage-on-ubuntu/README.md
Labels: best practices violations

#13670 Fix typo
  quickstarts/microsoft.eventhub/event-hubs-create-event-hub-and-consumer-group/metadata.json
Labels: BPA

#13672 Fix typo
  quickstarts/microsoft.web/web-app-github-deploy/GettingStarted-WebGit.md
Labels: best practices violations, BPA

#13676 [APIM] Update quickstart/bicep - API version
  quickstarts/microsoft.apimanagement/azure-api-management-create/README.md
  quickstarts/microsoft.apimanagement/azure-api-management-create/azuredeploy.json
  quickstarts/microsoft.apimanagement/azure-api-management-create/main.bicep
  quickstarts/microsoft.apimanagement/azure-api-management-create/metadata.json
Labels: BPA
