Repository Azure/azure-quickstart-templates, pull requests merged in 2023-05, with the labels that each got.

#13332 VM Simple Linux - Enabled Auto Upgrade for Extension
  quickstarts/microsoft.compute/vm-simple-linux/azuredeploy.json
  quickstarts/microsoft.compute/vm-simple-linux/main.bicep
Labels: PORTAL SAMPLE, BPA

#13334 Update imagebuilder-windowsbaseline demo to work with recent version of bicep as some resources aren't available in the current release of az bicep
  demos/imagebuilder-windowsbaseline/README.md
  demos/imagebuilder-windowsbaseline/azuredeploy.json
  demos/imagebuilder-windowsbaseline/azuredeploy.parameters.json
  demos/imagebuilder-windowsbaseline/main.bicep
Labels: BPA

#13336 Updated metadata for Managed Services CMK template
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-services-customer-managed-keys/metadata.json
Labels: bicep warnings

#13342 Update GettingStarted.md
  quickstarts/microsoft.web/webapp-linux-django/GettingStarted.md
Labels: BPA

#13371 Yuanheng changeextracttp
  application-workloads/sccm/sccm-technicalpreview/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-technicalpreview/DSC/InstallAndUpdateSCCM.ps1
  application-workloads/sccm/sccm-technicalpreview/DSC/TemplateHelpDSC/TemplateHelpDSC.psm1
  application-workloads/sccm/sccm-technicalpreview/metadata.json
Labels: best practices violations

#13372 Change the extract method
  application-workloads/sccm/sccm-currentbranch/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-currentbranch/DSC/InstallAndUpdateSCCM.ps1
  application-workloads/sccm/sccm-currentbranch/DSC/InstallCSForHierarchy.ps1
  application-workloads/sccm/sccm-currentbranch/DSC/TemplateHelpDSC/TemplateHelpDSC.psm1
  application-workloads/sccm/sccm-currentbranch/metadata.json
Labels: best practices violations

#13381 Fix cm source path for CB
  application-workloads/sccm/sccm-currentbranch/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-currentbranch/DSC/InstallAndUpdateSCCM.ps1
  application-workloads/sccm/sccm-currentbranch/DSC/InstallCSForHierarchy.ps1
Labels: best practices violations

#13379 Add a role assignment for Cosmos DB Read
  quickstarts/microsoft.kusto/kusto-cosmos-db/main.bicep
Labels: BPA

#13397 New Cost Management finops-hub template
  quickstarts/microsoft.costmanagement/finops-hub/README.md
  quickstarts/microsoft.costmanagement/finops-hub/azuredeploy.parameters.json
  quickstarts/microsoft.costmanagement/finops-hub/createUiDefinition.json
  quickstarts/microsoft.costmanagement/finops-hub/main.bicep
  quickstarts/microsoft.costmanagement/finops-hub/metadata.json
  quickstarts/microsoft.costmanagement/finops-hub/modules/dataFactory.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/hub.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/keyVault.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Start-Triggers.ps1
  quickstarts/microsoft.costmanagement/finops-hub/modules/storage.bicep
Labels: BPA

#13396 New Cost Management optimization workbook
  quickstarts/microsoft.costmanagement/optimization-workbook/README.md
  quickstarts/microsoft.costmanagement/optimization-workbook/azuredeploy.parameters.json
  quickstarts/microsoft.costmanagement/optimization-workbook/createUiDefinition.json
  quickstarts/microsoft.costmanagement/optimization-workbook/main.bicep
  quickstarts/microsoft.costmanagement/optimization-workbook/metadata.json
  quickstarts/microsoft.costmanagement/optimization-workbook/workbook.json
Labels: best practices violations

#13393 changed name from Mariner to Azure Linux
  quickstarts/microsoft.kubernetes/aks-azure-linux/azuredeploy.json
  quickstarts/microsoft.kubernetes/aks-azure-linux/azuredeploy.parameters.json
  quickstarts/microsoft.kubernetes/aks-azure-linux/main.bicep
  quickstarts/microsoft.kubernetes/aks-azure-linux/metadata.json
Labels: best practices violations, readme violations, BPA, remove azuredeploy.json

#13369 Dev/ksadhana/quickstart temp/23vm new or existing conditions
  quickstarts/microsoft.compute/vm-new-or-existing-conditions/azuredeploy.json
Labels: best practices violations, BPA

#13401 change the extract method
  application-workloads/sccm/sccm-currentbranch/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-currentbranch/DSC/InstallAndUpdateSCCM.ps1
  application-workloads/sccm/sccm-currentbranch/DSC/InstallCSForHierarchy.ps1
  application-workloads/sccm/sccm-currentbranch/DSC/TemplateHelpDSC/TemplateHelpDSC.psm1
Labels: best practices violations

#13365 16: vm-with-rdp-port: enabling TL feature
  quickstarts/microsoft.compute/vm-with-rdp-port/azuredeploy.json
Labels: best practices violations, BPA

#13385 Enable Trusted Launch
  quickstarts/microsoft.compute/vms-with-selfhost-integration-runtime/azuredeploy.json
Labels: best practices violations, BPA, remove azuredeploy.json

#13387 Enabling Trusted Launch
  quickstarts/microsoft.compute/vmss-with-public-ip-prefix/azuredeploy.json
Labels: best practices violations, bicep warnings, BPA, remove azuredeploy.json

#13389 enabling trusted launch
  quickstarts/microsoft.compute/vm-windows-ssh/azuredeploy.json
Labels: best practices violations, BPA, remove azuredeploy.json
