Repository Azure/azure-quickstart-templates, pull requests merged in 2023-02, with the labels that each got.

#13133 CMK-MangedDisk_APIVersionUpdate_changes
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/README.md
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/azuredeploy.parameters.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/main.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/metadata.json
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/nested_addAccessPolicy.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-managed-disk-customer-managed-keys/prereqs/prereq.azuredeploy.json
Labels: bicep warnings

#13173 Fixing broken link
  application-workloads/nextflow/nextflow-genomics-cluster-ubuntu/README.md
Labels: best practices violations, BPA

#13163 DonotMerge-All-In-One-Template-Vnet-APIVersionChanges-Jan2023
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection/main.bicep
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection/metadata.json
Labels: bicep warnings

#13176 Update OS
  demos/nested-vms-in-virtual-network/azuredeploy.json
Labels: best practices violations, remove azuredeploy.json

#13159 Enabled TL as default for VM Simple Windows
  quickstarts/microsoft.compute/vm-simple-windows/azuredeploy.json
  quickstarts/microsoft.compute/vm-simple-windows/createUiDefinition.json
  quickstarts/microsoft.compute/vm-simple-windows/main.bicep
Labels: PORTAL SAMPLE, BPA

#13165 Added azfw client thru server template
  quickstarts/microsoft.network/azurefirewall-client-server-sandbox/README.md
  quickstarts/microsoft.network/azurefirewall-client-server-sandbox/azuredeploy.json
  quickstarts/microsoft.network/azurefirewall-client-server-sandbox/azuredeploy.parameters.json
  quickstarts/microsoft.network/azurefirewall-client-server-sandbox/metadata.json
Labels: best practices violations, BPA

#13175 Update GameDev VM README.md
  application-workloads/azure-gamedev/gamedev-vm/README.md
Labels: best practices violations, BPA

#13178 Remove extra comma in the ARM template causing fialure
  quickstarts/microsoft.kubernetes/aks-mariner/azuredeploy.json
Labels: readme violations, BPA

#13179 Updated Trusted Launch artifacts
  quickstarts/microsoft.compute/vm-simple-linux/azuredeploy.json
  quickstarts/microsoft.compute/vm-simple-linux/main.bicep
Labels: PORTAL SAMPLE, BPA

#13190 Updating Function App 'function-premium-vnet-integration' to V4
  quickstarts/microsoft.web/function-premium-vnet-integration/main.bicep
Labels: BPA

#13191 Updating Function App 'functions-managed-identity' to V4
  quickstarts/microsoft.web/functions-managed-identity/azuredeploy.json
Labels: best practices violations, BPA

#13187 Updating Function App 'function-app-create-dynamic' to use V4
  quickstarts/microsoft.web/function-app-create-dynamic/main.bicep
Labels: BPA

#13150 Kusto with Cosmos DB connection
  quickstarts/microsoft.kusto/kusto-cosmos-db/README.md
  quickstarts/microsoft.kusto/kusto-cosmos-db/azuredeploy.parameters.json
  quickstarts/microsoft.kusto/kusto-cosmos-db/deploy.sh
  quickstarts/microsoft.kusto/kusto-cosmos-db/main.bicep
  quickstarts/microsoft.kusto/kusto-cosmos-db/metadata.json
  quickstarts/microsoft.kusto/kusto-cosmos-db/script.kql
Labels: BPA

#13189 Updating Function App template 'function-http-trigger' to use V4
  quickstarts/microsoft.web/function-http-trigger/main.bicep
Labels: best practices violations, BPA

#13188 Updating Function App template 'function-app-create-dynamic-slot' to V4
  quickstarts/microsoft.web/function-app-create-dynamic-slot/azuredeploy.json
Labels: best practices violations, BPA

#13186 Updating Function App 'function-app-create-dedicated' to use V4
  quickstarts/microsoft.web/function-app-create-dedicated/main.bicep
Labels: BPA

#13185 Updating Function App template 'app-function' to use V4
  quickstarts/microsoft.web/app-function/main.bicep
Labels: BPA

#13121 [api-management-logs-to-moesif-using-eventhub-webapp] - update API ve…
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/README.md
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/azuredeploy.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/main.bicep
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/metadata.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/apis/policies.bicep
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/apis/policies.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/loggers.bicep
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.apimanagement/service/loggers.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.eventhub/namespaces.bicep
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.eventhub/namespaces.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.storage/storageaccounts.bicep
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.storage/storageaccounts.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/serverfarms.bicep
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/serverfarms.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/sites.bicep
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/sites.json
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/sites/extensions.bicep
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/nested/microsoft.web/sites/extensions.json
Labels: BPA

#13193 Added graph history related parameters
  quickstarts/microsoft.digitaltwins/digitaltwins-with-function-time-series-database-connection/main.bicep
  quickstarts/microsoft.digitaltwins/digitaltwins-with-function-time-series-database-connection/metadata.json
  quickstarts/microsoft.digitaltwins/digitaltwins-with-function-time-series-database-connection/modules/dataexplorercluster.bicep
  quickstarts/microsoft.digitaltwins/digitaltwins-with-function-time-series-database-connection/modules/digitaltwins.bicep
  quickstarts/microsoft.digitaltwins/digitaltwins-with-function-time-series-database-connection/modules/roleassignment.bicep
  quickstarts/microsoft.digitaltwins/digitaltwins-with-function-time-series-database-connection/modules/tsdbconnection.bicep
Labels: bicep warnings, BPA
