Repository Azure/azure-quickstart-templates, pull requests merged in 2023-08, with the labels that each got.

#13498 Update api-management-private-endpoint/README.md
  quickstarts/microsoft.apimanagement/api-management-private-endpoint/README.md
Labels: best practices violations, BPA

#13499 Update api-management-create-with-external-redis-cache/README.md
  quickstarts/microsoft.apimanagement/api-management-create-with-external-redis-cache/README.md
Labels: BPA

#13500 Update api-management-create-with-external-vnet-publicip/README.md
  quickstarts/microsoft.apimanagement/api-management-create-with-external-vnet-publicip/README.md
Labels: best practices violations, BPA

#13503 Update api-management-create-with-msi/README.md
  quickstarts/microsoft.apimanagement/api-management-create-with-msi/README.md
Labels: BPA

#13481 aks-sql-server-always-on
  application-workloads/sql/aks-sql-server-always-on/README.md
  application-workloads/sql/aks-sql-server-always-on/azuredeploy.json
  application-workloads/sql/aks-sql-server-always-on/azuredeploy.parameters.json
  application-workloads/sql/aks-sql-server-always-on/main.bicep
  application-workloads/sql/aks-sql-server-always-on/metadata.json
Labels: BPA

#13507 Fix images not rendering properly for as2-send-receive
  quickstarts/microsoft.logic/logic-app-as2-send-receive/README.md
Labels: best practices violations, BPA

#13508 Adding plan and term fields
  quickstarts/microsoft.datadog/datadog/azuredeploy.json
  quickstarts/microsoft.datadog/datadog/createUiDefinition.json
Labels: manual validation required, best practices violations

#13514 Adding QuickStart template for 'NewRelic.Observability'
  quickstarts/newrelic.observability/newrelic/README.md
  quickstarts/newrelic.observability/newrelic/azuredeploy.json
  quickstarts/newrelic.observability/newrelic/azuredeploy.parameters.json
  quickstarts/newrelic.observability/newrelic/createUiDefinition.json
  quickstarts/newrelic.observability/newrelic/metadata.json
Labels: manual validation required, best practices violations

#13515 Fixing UI Defination Output Error For 'NewRelic.Observability'
  quickstarts/newrelic.observability/newrelic/azuredeploy.json
  quickstarts/newrelic.observability/newrelic/createUiDefinition.json
Labels: manual validation required, best practices violations

#13516 Fixes for AVNM Bicep Template - References, Routing
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/README.md
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/azuredeploy.json
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/modules/avnm.bicep
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/modules/avnmDeploymentScript.bicep
Labels: manual validation required, metadata violations, best practices violations, readme violations

#13517 Trying to Get Resource Group as DropDown For 'NewRelic.Observability'
  quickstarts/newrelic.observability/newrelic/README.md
  quickstarts/newrelic.observability/newrelic/azuredeploy.json
  quickstarts/newrelic.observability/newrelic/azuredeploy.parameters.json
  quickstarts/newrelic.observability/newrelic/createUiDefinition.json
  quickstarts/newrelic.observability/newrelic/metadata.json
Labels: manual validation required, best practices violations

#13519 feat: added main.bicep template for create-rg
  subscription-deployments/create-rg/README.md
  subscription-deployments/create-rg/azuredeploy.json
  subscription-deployments/create-rg/main.bicep
Labels: manual validation required

#13520 feat: added main.bicep to microsoft.compute\vm-tags
  quickstarts/microsoft.compute/vm-tags/README.md
  quickstarts/microsoft.compute/vm-tags/azuredeploy.json
  quickstarts/microsoft.compute/vm-tags/main.bicep
  quickstarts/microsoft.compute/vm-tags/metadata.json
Labels: BPA

#13529 Update azuredeploy.json
  quickstarts/microsoft.compute/vm-customdata/azuredeploy.json
Labels: best practices violations, BPA

#13530 fixing deployment JSON
  quickstarts/newrelic.observability/newrelic/azuredeploy.json
Labels: manual validation required, best practices violations

#13525 Update azuredeploy.json
  quickstarts/microsoft.streamanalytics/streamanalytics-create/azuredeploy.json
Labels: remove azuredeploy.json

#13531 Igorpag vwan patch1
  quickstarts/microsoft.network/virtual-wan-routing-intent/README.md
  quickstarts/microsoft.network/virtual-wan-routing-intent/azuredeploy.parameters.json
  quickstarts/microsoft.network/virtual-wan-routing-intent/images/two-secured-hubs-diagram.png
  quickstarts/microsoft.network/virtual-wan-routing-intent/main.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/metadata.json
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/er.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/firewallpolicies.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/fwdiagnostics.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/ipgroups.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/loganalyticsws.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/routingintent.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/vnetconnections.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/vnets.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/vpns2s.bicep
Labels: BPA

#13537 update bicep and parameter file
  quickstarts/microsoft.streamanalytics/streamanalytics-create/azuredeploy.parameters.json
  quickstarts/microsoft.streamanalytics/streamanalytics-create/main.bicep
Labels: BPA
