Repository Azure/azure-quickstart-templates, pull requests merged in 2023-03, with the labels that each got.

#13218 (AzureCXP) fixes MicrosoftDocs/azure-docs#106119
  quickstarts/microsoft.logic/logic-app-create/README.md
Labels: metadata violations

#13217 (AzureCXP) fixes MicrosoftDocs/azure-docs#106119
  quickstarts/microsoft.logic/logic-app-create/main.bicep
Labels: metadata violations

#13220 update learning link
  quickstarts/microsoft.cognitiveservices/cognitive-services-universalkey/metadata.json
Labels: BPA

#13221 update learning link
  quickstarts/microsoft.cognitiveservices/cognitive-services-translate/metadata.json
Labels: best practices violations, BPA

#13222 update learn link
  quickstarts/microsoft.cognitiveservices/cognitive-services-Computer-vision-API/metadata.json
Labels: best practices violations, UPPERCASE, BPA

#13225 update learning links
  quickstarts/microsoft.web/function-app-create-dedicated/metadata.json
Labels: BPA

#13226 update learning link
  quickstarts/microsoft.logic/logic-app-create/metadata.json
Labels: metadata violations

#13227 update learning
  quickstarts/microsoft.devices/iothub-with-consumergroup-create/metadata.json
Labels: readme violations

#13228 update learning
  quickstarts/microsoft.storage/storage-file-share/metadata.json
Labels: BPA

#13230 update learning link
  demos/ubuntu-desktop-gnome-rdp/metadata.json
Labels: best practices violations

#13232 update learning
  quickstarts/microsoft.eventhub/event-hubs-create-event-hub-and-consumer-group/metadata.json
Labels: best practices violations, BPA

#13233 update learn link
  quickstarts/microsoft.web/web-app-java-tomcat/metadata.json
Labels: BPA

#13236 update learning
  quickstarts/microsoft.web/webapp-linux-flask/metadata.json
Labels: BPA

#13238 update learning
  quickstarts/microsoft.web/app-function/metadata.json
Labels: BPA

#13240 Updates and edits
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/README.md
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/main.bicep
  quickstarts/microsoft.healthcareapis/workspaces/iotconnectors/metadata.json
Labels: BPA

#13276 [logic-app-ftp-to-blob] - add Bicep
  quickstarts/microsoft.logic/logic-app-ftp-to-blob/README.md
  quickstarts/microsoft.logic/logic-app-ftp-to-blob/azuredeploy.json
  quickstarts/microsoft.logic/logic-app-ftp-to-blob/main.bicep
  quickstarts/microsoft.logic/logic-app-ftp-to-blob/metadata.json
Labels: bicep warnings

#13277 [ubuntu-desktop-gnome] - add bicep and update api versions
  demos/ubuntu-desktop-gnome/README.md
  demos/ubuntu-desktop-gnome/azuredeploy.json
  demos/ubuntu-desktop-gnome/main.bicep
  demos/ubuntu-desktop-gnome/metadata.json
Labels: BPA
