Repository Azure/azure-quickstart-templates, pull requests merged in 2024-08, with the labels that each got.

#14107 Add role assignment of Azure Stack HCI Connected InfraVMs
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#13290 VMSSDependsonLB
  demos/vmss-windows-webapp-dsc-autoscale/azuredeploy.json
Labels: best practices violations, remove azuredeploy.json

#14120 [front-door-api-management] Update README.md
  quickstarts/microsoft.network/front-door-api-management/README.md
Labels: best practices violations, BPA

#14123 Update remote access to resources from Internet to specific source IP address
  quickstarts/microsoft.network/azurefirewall-forced-tunneling/azuredeploy.json
Labels: best practices violations, BPA

#14119 Update Azure AI Studio Microsoft Entra ID template with keyless dependencies
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/README.md
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/main.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/main.json
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/metadata.json
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/modules/ai-hub.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/modules/dependent-resources.bicep
Labels: remove azuredeploy.json

#14116 Add Demo for Confidential OS Disk Encryption enabled VMSS deployment.
  demos/vmss-cvm-fde/README.md
  demos/vmss-cvm-fde/azuredeploy.json
  demos/vmss-cvm-fde/azuredeploy.parameters.json
  demos/vmss-cvm-fde/createUiDefinition.json
  demos/vmss-cvm-fde/metadata.json
Labels: readme violations

#14115 Front Door and Application Gateway - Fix Application Gateway required property
  quickstarts/microsoft.cdn/front-door-standard-premium-application-gateway-public/modules/application-gateway.bicep
Labels: best practices violations, BPA

#14106 edited readme.md
  quickstarts/microsoft.cdn/front-door-standard-premium-custom-domain/README.md
Labels: best practices violations
