Repository Azure/azure-quickstart-templates, pull requests merged in 2024-04, with the labels that each got.

#13932 AIStudio connections-based setup using EntraID auth
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/README.md
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/main.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/main.json
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/metadata.json
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/modules/ai-hub.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-entraid-passthrough/modules/dependent-resources.bicep
Labels: BPA, remove azuredeploy.json

#13936 [ag-docs-qs] - update api versions and add output
  demos/ag-docs-qs/README.md
  demos/ag-docs-qs/azuredeploy.json
  demos/ag-docs-qs/main.bicep
  demos/ag-docs-qs/metadata.json
Labels: BPA

#13942 [sql-data-warehouse-transparent-encryption-create] update api version…
  quickstarts/microsoft.sql/sql-data-warehouse-transparent-encryption-create/README.md
  quickstarts/microsoft.sql/sql-data-warehouse-transparent-encryption-create/azuredeploy.json
  quickstarts/microsoft.sql/sql-data-warehouse-transparent-encryption-create/main.bicep
  quickstarts/microsoft.sql/sql-data-warehouse-transparent-encryption-create/metadata.json
Labels: BPA

#13943 [streamanalytics-create] add outputs
  quickstarts/microsoft.streamanalytics/streamanalytics-create/azuredeploy.json
  quickstarts/microsoft.streamanalytics/streamanalytics-create/main.bicep
  quickstarts/microsoft.streamanalytics/streamanalytics-create/metadata.json
Labels: BPA

#13951 [hdinsight-kafka] update api versions and add outputs
  quickstarts/microsoft.hdinsight/hdinsight-kafka/README.md
  quickstarts/microsoft.hdinsight/hdinsight-kafka/azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-kafka/main.bicep
  quickstarts/microsoft.hdinsight/hdinsight-kafka/metadata.json
Labels: BPA

#13950 [iothub-auto-route-messages] - update api versions and add outputs
  quickstarts/microsoft.devices/iothub-auto-route-messages/README.md
  quickstarts/microsoft.devices/iothub-auto-route-messages/azuredeploy.json
  quickstarts/microsoft.devices/iothub-auto-route-messages/main.bicep
  quickstarts/microsoft.devices/iothub-auto-route-messages/metadata.json
Labels: BPA

#13916 Add a database watcher with new data store sample
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/README.md
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/azuredeploy.json
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/azuredeploy.parameters.json
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/metadata.json
Labels: best practices violations, BPA

#13926 Added Anbox Cloud quick-start template
  quickstarts/canonical/anbox/README.md
  quickstarts/canonical/anbox/azuredeploy.parameters.json
  quickstarts/canonical/anbox/main.bicep
  quickstarts/canonical/anbox/metadata.json
Labels: readme violations

#13956 Minor change to bicep file to get template file to regenerate
  quickstarts/microsoft.network/load-balancer-cross-region/main.bicep
Labels: best practices violations

#13955 [hdinsight-hive] update api versions and add outputs
  quickstarts/microsoft.hdinsight/hdinsight-interactive-hive/README.md
  quickstarts/microsoft.hdinsight/hdinsight-interactive-hive/azuredeploy.json
  quickstarts/microsoft.hdinsight/hdinsight-interactive-hive/main.bicep
  quickstarts/microsoft.hdinsight/hdinsight-interactive-hive/metadata.json
Labels: BPA

#13969 [create-budget-simple] - update api version and add outputs
  quickstarts/microsoft.consumption/create-budget-simple/README.md
  quickstarts/microsoft.consumption/create-budget-simple/azuredeploy.json
  quickstarts/microsoft.consumption/create-budget-simple/main.bicep
  quickstarts/microsoft.consumption/create-budget-simple/metadata.json
Labels: manual validation required, BPA

#13968 [data-factory-v2-blob-to-blob-copy] - update api versions and add out…
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-blob-copy/README.md
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-blob-copy/azuredeploy.json
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-blob-copy/main.bicep
  quickstarts/microsoft.datafactory/data-factory-v2-blob-to-blob-copy/metadata.json
Labels: BPA

#13967 [event-grid-subscription-and-storage] - update api versions and add o…
  quickstarts/microsoft.eventgrid/event-grid-subscription-and-storage/README.md
  quickstarts/microsoft.eventgrid/event-grid-subscription-and-storage/azuredeploy.json
  quickstarts/microsoft.eventgrid/event-grid-subscription-and-storage/main.bicep
  quickstarts/microsoft.eventgrid/event-grid-subscription-and-storage/metadata.json
  quickstarts/microsoft.eventgrid/event-grid-subscription-and-storage/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.eventgrid/event-grid-subscription-and-storage/prereqs/prereq.main.bicep
Labels: BPA

#13965 Use multiple targets and private endpoints
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/README.md
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/azuredeploy.json
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/azuredeploy.parameters.json
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/metadata.json
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/prereqs/.settings.json
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.databasewatcher/watcher-new-datastore/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, BPA

#13974 [arm-template-retrieve-azure-storage-access-keys] - add Bicep, update…
  demos/arm-template-retrieve-azure-storage-access-keys/README.md
  demos/arm-template-retrieve-azure-storage-access-keys/azuredeploy.json
  demos/arm-template-retrieve-azure-storage-access-keys/main.bicep
  demos/arm-template-retrieve-azure-storage-access-keys/metadata.json
Labels: BPA

#13975 [create cluster azurestackhci] - add Bicep
  quickstarts/microsoft.azurestackhci/create-cluster/README.md
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/create-cluster/main.bicep
  quickstarts/microsoft.azurestackhci/create-cluster/metadata.json
Labels: manual validation required, best practices violations, BPA

#13982 [database watcher] - fix elastic pool targets
  quickstarts/microsoft.databasewatcher/create-watcher/main.bicep
Labels: best practices violations, BPA

#13986 Remove example script with credentials
  application-workloads/sql/sqlvm-provisioning-csp/Common.ps1
  application-workloads/sql/sqlvm-provisioning-csp/CreateSQLVMExample.ps1
  application-workloads/sql/sqlvm-provisioning-csp/New-SqlServerVirtualMachine.ps1
  application-workloads/sql/sqlvm-provisioning-csp/README.md
Labels: best practices violations, BPA

#13990 Add 2 Node switched custom Storage IP example for Azure Stack HCI
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/README.md
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/metadata.json
Labels: manual validation required, best practices violations, readme violations, BPA

#13988 Add 3 Node switchless single link example for Azure Stack HCI deployment.
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/README.md
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/metadata.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#13919 Improve ARM template based deployment of Azure stack HCI cluster
  quickstarts/microsoft.azurestackhci/create-cluster/README.md
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.parameters.json
Labels: manual validation required, best practices violations, readme violations, BPA, remove azuredeploy.json
