Repository Azure/azure-quickstart-templates, pull requests merged in 2024-12, with the labels that each got.

#14227 Add bicep for Basic Agent Setup using api keys for auth on AI Service/AOAI connection
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-keys/README.md
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-keys/azuredeploy.parameters.json
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-keys/main.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-keys/metadata.json
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-keys/modules-basic/basic-ai-hub-keys.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-keys/modules-basic/basic-ai-project-keys.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-keys/modules-basic/basic-dependent-resources.bicep
Labels: BPA

#14235 Removed notice that Cloud Shell in a VNet functionality is in preview
  demos/cloud-shell-vnet/README.md
Labels: best practices violations, bicep warnings

#14238 Yuanhyan update tp
  application-workloads/sccm/sccm-technicalpreview/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-technicalpreview/DSC/InstallAndUpdateSCCM.ps1
  application-workloads/sccm/sccm-technicalpreview/DSC/PSConfiguration.ps1
  application-workloads/sccm/sccm-technicalpreview/DSC/TemplateHelpDSC/TemplateHelpDSC.psd1
  application-workloads/sccm/sccm-technicalpreview/DSC/TemplateHelpDSC/TemplateHelpDSC.psm1
  application-workloads/sccm/sccm-technicalpreview/azuredeploy.json
  application-workloads/sccm/sccm-technicalpreview/metadata.json
Labels: best practices violations

#14239 [devbox-ready-to-code-image] Address TODOs
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/azuredevops/build_images.ps1
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/main.bicep
Labels: BPA

#14240 Updating standard agent setup
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/README.md
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/azuredeploy.parameters.json
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/main.bicep
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/metadata.json
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/modules-standard/ai-search-role-assignments.bicep
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/modules-standard/ai-service-role-assignments.bicep
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/modules-standard/standard-ai-hub.bicep
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/modules-standard/standard-ai-project.bicep
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/modules-standard/standard-dependent-resources.bicep
Labels: best practices violations, BPA

#14241 Adding a new entra entitlement management service custom extensibility logic app sample
  demos/identitygovernance-entitlementmanagement-extensibility-servicenow-sample-logicapp/README.md
  demos/identitygovernance-entitlementmanagement-extensibility-servicenow-sample-logicapp/azuredeploy.json
  demos/identitygovernance-entitlementmanagement-extensibility-servicenow-sample-logicapp/azuredeploy.parameters.json
  demos/identitygovernance-entitlementmanagement-extensibility-servicenow-sample-logicapp/metadata.json
Labels: metadata violations, best practices violations, BPA

#14249 Support for BYO AI Services resource to basic setup
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/README.md
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/azuredeploy.parameters.json
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/main.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/modules-basic/ai-service-role-assignments.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/modules-basic/basic-ai-hub-identity.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/modules-basic/basic-ai-project-identity.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/modules-basic/basic-dependent-resources.bicep
Labels: best practices violations, BPA

#14250 Changing hub storage connection to use MI
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/README.md
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/modules-standard/standard-ai-hub.bicep
Labels: best practices violations, BPA

#14253 Adding minor updates to basic agent setup
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/azuredeploy.parameters.json
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/main.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/modules-basic/basic-ai-hub-identity.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/modules-basic/basic-dependent-resources.bicep
Labels: best practices violations, BPA

#14255 Removing bad parameter
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/main.bicep
Labels: best practices violations, BPA

#14258 Adding param to standard agent setup
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/README.md
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/azuredeploy.parameters.json
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/main.bicep
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/modules-standard/standard-ai-hub.bicep
Labels: best practices violations, BPA

#14260 Updating clarity with Standard Agent setup BYO Azure Open AI resource
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/README.md
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/main.bicep
  quickstarts/microsoft.azure-ai-agent-service/standard-agent/modules-standard/standard-ai-hub.bicep
Labels: best practices violations, BPA

#14252 [devbox-ready-to-code-image] Provide explicit default values for complex params; add blog post link
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/README.md
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/main.bicep
Labels: BPA

#14269 update API version to 2024-09-01-preview (upgrade cluster)
  quickstarts/microsoft.azurestackhci/upgrade-cluster/azuredeploy.json
Labels: manual validation required, best practices violations, BPA

#14268 update API version to 2024-09-01-preview (Cluster with pre-reqs)
  quickstarts/microsoft.azurestackhci/create-cluster-with-prereqs/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-with-prereqs/main.bicep
Labels: manual validation required, best practices violations, readme violations, bicep warnings, BPA, remove azuredeploy.json

#14264 Service Fabric - Update extension version to latest version 1.1
  quickstarts/microsoft.servicefabric/service-fabric-secure-cluster-5-node-1-nodetype/azuredeploy.json
Labels: BPA, remove azuredeploy.json

#14263 sf linux: update extension version with auto upgrade and use ubuntu 20.04
  quickstarts/microsoft.servicefabric/5-vm-ubuntu-1-nodetypes-secure/azuredeploy.json
Labels: best practices violations, BPA

#14262 Service Fabric - update extension version and use ubuntu 20.04 for linux
  quickstarts/microsoft.servicefabric/service-fabric-secure-nsg-cluster-65-node-3-nodetype/azuredeploy.json
Labels: best practices violations, BPA

#14242 Fix Typo
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/main.bicep
Labels: best practices violations, BPA

#14266 update API version to 2024-09-01-preview (3 node switchless single link)
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/azuredeploy.parameters.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14267 update API version to 2024-09-01-preview (3 node switchless duallink)
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-DualLink/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-DualLink/azuredeploy.parameters.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14265 update API version to 2024-09-01-preview (2node switched customstorageIP)
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/azuredeploy.parameters.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14261 Update API version to 2024-09-01-preview
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.parameters.json
Labels: manual validation required, best practices violations, readme violations, BPA
