Repository Azure/azure-quickstart-templates, pull requests merged in 2024-06, with the labels that each got.

#14054 Set EnableStorageAutoIP to true by default
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.parameters.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14056 Adding enableAutomaticUpgrade property for GuestAttestationExtension
  quickstarts/microsoft.compute/vm-trustedlaunch-windows/azuredeploy.json
  quickstarts/microsoft.compute/vm-trustedlaunch-windows/main.bicep
Labels: best practices violations, bicep warnings, remove azuredeploy.json

#14055 Adding enableaAutomaticUpgrade for GuestAttestationExtension
  quickstarts/microsoft.compute/vm-trustedlaunch-windows/azuredeploy.json
Labels: best practices violations, bicep warnings, remove azuredeploy.json

#14052 Update full 5g deployment creation with user consent
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/main.bicep
  quickstarts/microsoft.mobilenetwork/mobilenetwork-create-full-5gc-deployment/metadata.json
Labels: bicep warnings

#14071 updated API Version to GA API Version in 2 Node switched scenario
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/azuredeploy.parameters.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14072 updated API Version in 3 Node switchless dual link
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-DualLink/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-DualLink/azuredeploy.parameters.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14073 updated API Version in 3 Node switchless single link
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/azuredeploy.parameters.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14039 [AI Studio] private link deployment
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/README.md
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/main.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/main.json
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/metadata.json
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/ai-hub.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent-resources.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent/aiservices.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent/applicationinsights.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent/containerregistry.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent/keyvault.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent/storage.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/prereqs/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/prereqs/prereq.main.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/prereqs/prereq.main.json
Labels: BPA

#14069 Azure Stack HCI VMs - API Version Bump (Linux VM Simple)
  quickstarts/microsoft.azurestackhci/vm-simple-ashci-linux/main.bicep
  quickstarts/microsoft.azurestackhci/vm-simple-ashci-linux/metadata.json
Labels: manual validation required, best practices violations, bicep warnings

#14068 Azure Stack HCI VMs - API Version Bump (Windows VM Simple)
  quickstarts/microsoft.azurestackhci/vm-simple-ashci-windows/main.bicep
  quickstarts/microsoft.azurestackhci/vm-simple-ashci-windows/metadata.json
Labels: manual validation required, best practices violations

#14067 Azure Stack HCI VMs - API Version Bump (VM Extensions + Disks)
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/main.bicep
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/metadata.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14064 Fix AKS API Version to Available Non-preview version
  quickstarts/microsoft.kubernetes/aks-vmss-systemassigned-identity/main.bicep
Labels: BPA
