Repository Azure/azure-quickstart-templates, pull requests merged in 2024-10, with the labels that each got.

#14168 FinOps toolkit 0.6 - finops-hub update
  quickstarts/microsoft.costmanagement/finops-hub/README.md
  quickstarts/microsoft.costmanagement/finops-hub/main.bicep
  quickstarts/microsoft.costmanagement/finops-hub/metadata.json
  quickstarts/microsoft.costmanagement/finops-hub/modules/dataFactory.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/ftkver.txt
  quickstarts/microsoft.costmanagement/finops-hub/modules/hub.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Remove-OldResources.ps1
  quickstarts/microsoft.costmanagement/finops-hub/modules/storage.bicep
  quickstarts/microsoft.costmanagement/finops-hub/schemas/reservationdetails_2023-03-01.json
Labels: best practices violations, bicep warnings, BPA

#14171 Darktrace / CLOUD™ for Azure support: October 2024
  application-workloads/darktrace/darktrace-vsensor-autoscaling/README.md
  application-workloads/darktrace/darktrace-vsensor-autoscaling/azuredeploy.json
  application-workloads/darktrace/darktrace-vsensor-autoscaling/metadata.json
Labels: BPA

#14175 fix: update quickstart readme.
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/README.md
Labels: best practices violations, BPA

#14177 Deploy Secure Azure AI Studio with a managed virtual network
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/README.md
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/images/authentication-methods.png
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/images/hub-workspace.png
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/images/key-vault.png
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/images/managed-virtual-network.png
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/images/mfa.png
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/main.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/metadata.json
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/aiServices.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/applicationInsights.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/containerRegistry.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/functions.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/hub.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/keyVault.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/logAnalytics.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/privateEndpoints.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/project.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/storageAccount.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/virtualMachine.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/modules/virtualNetwork.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/params.bicepparam
Labels: best practices violations, BPA

#14184 Deprecate template
  quickstarts/microsoft.web/private-webapp-with-app-gateway-and-apim/README.md
  quickstarts/microsoft.web/private-webapp-with-app-gateway-and-apim/main.bicep
Labels: bicep warnings, BPA

#14188 add template support to upgrade an Azure Stack HCI cluster
  quickstarts/microsoft.azurestackhci/upgrade-cluster/README.md
  quickstarts/microsoft.azurestackhci/upgrade-cluster/azuredeploy.json
  quickstarts/microsoft.azurestackhci/upgrade-cluster/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/upgrade-cluster/metadata.json
Labels: manual validation required, best practices violations, BPA

#14186 update: AI Studio restricted template with systemDatastoresAuthMode, AAD authkey parameter, and added Search connection
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/README.md
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/main.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/main.json
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/metadata.json
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/ai-hub.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent-resources.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent/aisearch.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent/aiservices.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/prereqs/prereq.azuredeploy.json
Labels: best practices violations, BPA

#14178 Add gov cloud for service-side CMK
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-cmk-service-side-encryption/README.md
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-cmk-service-side-encryption/azuredeploy.parameters.us.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-cmk-service-side-encryption/metadata.json
  quickstarts/microsoft.machinelearningservices/machine-learning-workspace-cmk-service-side-encryption/prereqs/prereq.azuredeploy.parameters.us.json
Labels: bicep warnings, BPA

#14165 Service-side encryption preview for hub workspaces used in AI Studio
  quickstarts/microsoft.machinelearningservices/aistudio-cmk-service-side-encryption/README.md
  quickstarts/microsoft.machinelearningservices/aistudio-cmk-service-side-encryption/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/aistudio-cmk-service-side-encryption/main.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-cmk-service-side-encryption/metadata.json
  quickstarts/microsoft.machinelearningservices/aistudio-cmk-service-side-encryption/modules/ai-hub.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-cmk-service-side-encryption/modules/dependent-resources.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-cmk-service-side-encryption/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.machinelearningservices/aistudio-cmk-service-side-encryption/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations, bicep warnings, BPA, remove azuredeploy.json

#14180 Aks application gateway ingress controller
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/README.md
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/main.bicep
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/modules/computes/virtualmachine.bicep
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/modules/containerservices/containerregistry.bicep
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/modules/containerservices/kubernetes.bicep
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/modules/identity/identity.bicep
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/modules/monitoring/monitoring.bicep
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/modules/networks/applicationgateway.bicep
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/modules/networks/main.bicep
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/modules/roleassignment/roleassignment.bicep
  quickstarts/microsoft.network/aks-application-gateway-ingress-controller/modules/security/keyvault.bicep
Labels: BPA

#14190 HCI Cluster Bicep with Prereqs Improvements
  quickstarts/microsoft.azurestackhci/create-cluster-with-prereqs/main.bicep
  quickstarts/microsoft.azurestackhci/create-cluster-with-prereqs/modules/ashciPrereqs.bicep
Labels: manual validation required, best practices violations, readme violations, BPA

#14195 Added bicep code for creating Application Gateway for Url Path Based …
  quickstarts/microsoft.network/application-gateway-url-path-based-routing/README.md
  quickstarts/microsoft.network/application-gateway-url-path-based-routing/azuredeploy.json
  quickstarts/microsoft.network/application-gateway-url-path-based-routing/azuredeploy.parameters.json
  quickstarts/microsoft.network/application-gateway-url-path-based-routing/main.bicep
Labels: BPA, remove azuredeploy.json

#14193 Create Azure VM Replication and Disaster Recovery
  quickstarts/microsoft.recoveryservices/recovery-services-vm-replication-and-disaster-recovery/README.md
  quickstarts/microsoft.recoveryservices/recovery-services-vm-replication-and-disaster-recovery/azuredeploy.json
  quickstarts/microsoft.recoveryservices/recovery-services-vm-replication-and-disaster-recovery/azuredeploy.parameters.json
  quickstarts/microsoft.recoveryservices/recovery-services-vm-replication-and-disaster-recovery/main.bicep
  quickstarts/microsoft.recoveryservices/recovery-services-vm-replication-and-disaster-recovery/metadata.json
Labels: remove azuredeploy.json

#14173 fix issues in templates, add support for dynamic logical network, usi…
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/main.bicep
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/prereqs/image/gallery/parameters.json
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/prereqs/image/main.bicep
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/prereqs/image/marketplace/parameters.json
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/prereqs/logical-network/dynamic/parameters.json
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/prereqs/logical-network/main.bicep
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/prereqs/logical-network/static/parameters.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14200 [AI Studio] Enablement of additional storage reader role on aistudio-network-restricted
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/main.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/main.json
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/ai-hub.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/dependent/aisearch.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-network-restricted/modules/role-assignments.bicep
Labels: best practices violations, bicep warnings, BPA

#14189 Create AVD with FSLogix and AD DS Join
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/README.md
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/azuredeploy.json
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/azuredeploy.parameters.json
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/main.bicep
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/metadata.json
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/modules/recoveryservicevault/main.bicep
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/modules/sessionhost/main.bicep
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/modules/storage/main.bicep
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/modules/virtualdesktop/main.bicep
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/modules/virtualnetwork/hubnetwork.bicep
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/modules/virtualnetwork/main.bicep
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/scripts/postconfiguration.ps1
  quickstarts/microsoft.desktopvirtualization/azure-virtual-desktop-with-fslogix/scripts/preconfiguration.ps1
Labels: BPA, remove azuredeploy.json

#14201 updated decompression method for TP
  application-workloads/sccm/sccm-technicalpreview/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-technicalpreview/DSC/InstallAndUpdateSCCM.ps1
  application-workloads/sccm/sccm-technicalpreview/DSC/TemplateHelpDSC/TemplateHelpDSC.psm1
  application-workloads/sccm/sccm-technicalpreview/metadata.json
Labels: best practices violations

#14202 Update azuredeploy.json
  modules/active-directory-new-domain/0.9/azuredeploy.json
Labels: best practices violations, duplicate foldername
