Repository Azure/azure-quickstart-templates, pull requests merged in 2024-01, with the labels that each got.

#13687 Fixed template
  demos/private-aks-cluster-with-public-dns-zone/README.md
  demos/private-aks-cluster-with-public-dns-zone/azuredeploy.json
Labels: BPA

#13685 FinOps toolkit - optimization-workbook update
  quickstarts/microsoft.costmanagement/optimization-workbook/README.md
  quickstarts/microsoft.costmanagement/optimization-workbook/azuredeploy.json
  quickstarts/microsoft.costmanagement/optimization-workbook/metadata.json
  quickstarts/microsoft.costmanagement/optimization-workbook/version.txt
Labels: best practices violations, bicep warnings

#13679 Add ARM template for BrowserBox
  application-workloads/dosyago/browserbox/README.md
  application-workloads/dosyago/browserbox/azuredeploy.json
  application-workloads/dosyago/browserbox/azuredeploy.parameters.json
  application-workloads/dosyago/browserbox/createUiDefinition.json
  application-workloads/dosyago/browserbox/installBrowserBox_then_notify.sh
  application-workloads/dosyago/browserbox/metadata.json
Labels: BPA

#13455 Cost Management finops-hub template update
  quickstarts/microsoft.costmanagement/finops-hub/.buildignore
  quickstarts/microsoft.costmanagement/finops-hub/README.md
  quickstarts/microsoft.costmanagement/finops-hub/azuredeploy.json
  quickstarts/microsoft.costmanagement/finops-hub/createUiDefinition.json
  quickstarts/microsoft.costmanagement/finops-hub/main.bicep
  quickstarts/microsoft.costmanagement/finops-hub/metadata.json
  quickstarts/microsoft.costmanagement/finops-hub/modules/dataFactory.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/hub.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/keyVault.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Remove-ManagedIdentity.ps1
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Start-Triggers.ps1
  quickstarts/microsoft.costmanagement/finops-hub/modules/storage.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/version.txt
  quickstarts/microsoft.costmanagement/finops-hub/schemas/schema.settings.json
Labels: best practices violations, bicep warnings, BPA

#13682 add windows container qs
  quickstarts/microsoft.web/app-service-docs-windows-container/README.md
  quickstarts/microsoft.web/app-service-docs-windows-container/azuredeploy.json
  quickstarts/microsoft.web/app-service-docs-windows-container/azuredeploy.parameters.json
  quickstarts/microsoft.web/app-service-docs-windows-container/metadata.json
Labels: metadata violations, best practices violations, readme violations, BPA

#13693 Updated plan SKU and API version parameter
  quickstarts/microsoft.elastic/elastic-create/azuredeploy.parameters.json
  quickstarts/microsoft.elastic/elastic-create/main.bicep
Labels: best practices violations, readme violations

#13694 Updated labels and ARM deployment template
  quickstarts/microsoft.healthcareapis/fhir-import/azuredeploy.json
  quickstarts/microsoft.healthcareapis/fhir-import/azuredeploy.parameters.json
  quickstarts/microsoft.healthcareapis/fhir-import/main.bicep
Labels: remove azuredeploy.json

#13700 Update createUiDefinition.json
  quickstarts/microsoft.elastic/elastic-create/createUiDefinition.json
Labels: best practices violations, readme violations

#13699 FinOps toolkit -- Add missing azuredeploy.json for Cost optimization workbook
  quickstarts/microsoft.costmanagement/optimization-workbook/azuredeploy.json
Labels: best practices violations, bicep warnings, remove azuredeploy.json

#13677 Basic IaC template for Azure AI studio
  quickstarts/microsoft.machinelearningservices/aistudio-basics/README.md
  quickstarts/microsoft.machinelearningservices/aistudio-basics/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/aistudio-basics/main.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-basics/main.json
  quickstarts/microsoft.machinelearningservices/aistudio-basics/metadata.json
  quickstarts/microsoft.machinelearningservices/aistudio-basics/modules/ai-resource.bicep
  quickstarts/microsoft.machinelearningservices/aistudio-basics/modules/dependent-resources.bicep
Labels: BPA

#13723 FinOps toolkit 0.2 - FinOps hub update
  quickstarts/microsoft.costmanagement/finops-hub/.buildignore
  quickstarts/microsoft.costmanagement/finops-hub/README.md
  quickstarts/microsoft.costmanagement/finops-hub/metadata.json
  quickstarts/microsoft.costmanagement/finops-hub/modules/dataFactory.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Remove-ManagedIdentity.ps1
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Remove-OldResources.ps1
  quickstarts/microsoft.costmanagement/finops-hub/modules/storage.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/version.txt
  quickstarts/microsoft.costmanagement/finops-hub/schemas/schema.settings.json
Labels: best practices violations, bicep warnings, BPA

#13722 FinOps toolkit 0.2 - Optimization workbook update
  quickstarts/microsoft.costmanagement/optimization-workbook/README.md
  quickstarts/microsoft.costmanagement/optimization-workbook/metadata.json
  quickstarts/microsoft.costmanagement/optimization-workbook/version.txt
  quickstarts/microsoft.costmanagement/optimization-workbook/workbook.json
Labels: best practices violations, bicep warnings

#13736 fix vm-simple-windows conflict
  quickstarts/microsoft.azurestackhci/vm-simple-hci-windows/README.md
  quickstarts/microsoft.azurestackhci/vm-simple-hci-windows/azuredeploy.json
  quickstarts/microsoft.azurestackhci/vm-simple-hci-windows/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/vm-simple-hci-windows/main.bicep
  quickstarts/microsoft.azurestackhci/vm-simple-hci-windows/metadata.json
  quickstarts/microsoft.azurestackhci/vm-simple-hci-windows/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/vm-simple-hci-windows/prereq.main.bicep
Labels: manual validation required, readme violations, remove azuredeploy.json
