Repository Azure/azure-quickstart-templates, pull requests merged in 2024-02, with the labels that each got.

#13739 VMSS Flex quickstart - Updated to Gen2-Trusted launch
  quickstarts/microsoft.compute/vmss-flexible-orchestration-quickstart/azuredeploy.json
  quickstarts/microsoft.compute/vmss-flexible-orchestration-quickstart/main.bicep
  quickstarts/microsoft.compute/vmss-flexible-orchestration-quickstart/modules/compute/vmssflex.bicep
  quickstarts/microsoft.compute/vmss-flexible-orchestration-quickstart/modules/network/basenetwork.bicep
  quickstarts/microsoft.compute/vmss-flexible-orchestration-quickstart/modules/network/slb.bicep
Labels: BPA

#13728 Added workspace for App Insights instance
  quickstarts/microsoft.web/function-http-trigger/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-http-trigger/main.bicep
  quickstarts/microsoft.web/function-http-trigger/main.bicepparam
Labels: best practices violations, BPA

#13753 iis-2vm-sql-1vm - Add Bicep file
  demos/iis-2vm-sql-1vm/README.md
  demos/iis-2vm-sql-1vm/azuredeploy.json
  demos/iis-2vm-sql-1vm/main.bicep
  demos/iis-2vm-sql-1vm/metadata.json
Labels: best practices violations, BPA

#13755 Typo "a ORACLE storage"→"an ORACLE storage"
  quickstarts/microsoft.netapp/anf-oracle/anf-oracle-storage/README.md
Labels: best practices violations, bicep warnings

#13756 app-service-docs-windows-container - Add Bicep File
  quickstarts/microsoft.web/app-service-docs-windows-container/README.md
  quickstarts/microsoft.web/app-service-docs-windows-container/azuredeploy.json
  quickstarts/microsoft.web/app-service-docs-windows-container/main.bicep
  quickstarts/microsoft.web/app-service-docs-windows-container/metadata.json
Labels: best practices violations, readme violations, BPA

#13746 Added support for SNAT custom ranges
  quickstarts/microsoft.network/virtual-wan-routing-intent/azuredeploy.json
  quickstarts/microsoft.network/virtual-wan-routing-intent/azuredeploy.parameters.json
  quickstarts/microsoft.network/virtual-wan-routing-intent/main.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/metadata.json
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/PrivateTrafficRouteTable.bicep
  quickstarts/microsoft.network/virtual-wan-routing-intent/modules/firewallpolicies.bicep
Labels: BPA

#13759 app-service-docs-windows - Add Bicep file
  quickstarts/microsoft.web/app-service-docs-windows/README.md
  quickstarts/microsoft.web/app-service-docs-windows/azuredeploy.json
  quickstarts/microsoft.web/app-service-docs-windows/main.bicep
  quickstarts/microsoft.web/app-service-docs-windows/metadata.json
Labels: BPA

#13761 application-gateway-logviewer-goaccess - Add Bicep
  demos/application-gateway-logviewer-goaccess/README.md
  demos/application-gateway-logviewer-goaccess/azuredeploy.json
  demos/application-gateway-logviewer-goaccess/main.bicep
  demos/application-gateway-logviewer-goaccess/metadata.json
Labels: best practices violations

#13763 api-management-create-with-internal-vnet-application-gateway - Add Bicep
  quickstarts/microsoft.apimanagement/api-management-create-with-internal-vnet-application-gateway/README.md
  quickstarts/microsoft.apimanagement/api-management-create-with-internal-vnet-application-gateway/azuredeploy.json
  quickstarts/microsoft.apimanagement/api-management-create-with-internal-vnet-application-gateway/azuredeploy.parameters.json
  quickstarts/microsoft.apimanagement/api-management-create-with-internal-vnet-application-gateway/main.bicep
  quickstarts/microsoft.apimanagement/api-management-create-with-internal-vnet-application-gateway/metadata.json
  quickstarts/microsoft.apimanagement/api-management-create-with-internal-vnet-application-gateway/prereqs/prereq.azuredeploy.json
Labels: BPA, remove azuredeploy.json

#13770 [Create a new role def] Custom role with deterministic role ID update
  subscription-deployments/create-role-def/azuredeploy.json
  subscription-deployments/create-role-def/main.bicep
  subscription-deployments/create-role-def/metadata.json
Labels: manual validation required, BPA

#13760 databricks-workspace-with-customer-managed-keys-all-forms - Add Bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-customer-managed-keys-all-forms/README.md
  quickstarts/microsoft.databricks/databricks-workspace-with-customer-managed-keys-all-forms/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace-with-customer-managed-keys-all-forms/main.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-customer-managed-keys-all-forms/metadata.json
  quickstarts/microsoft.databricks/databricks-workspace-with-customer-managed-keys-all-forms/modules/DbfsCMKAccessPolicy.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-customer-managed-keys-all-forms/modules/DbfsCMKEnable.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-customer-managed-keys-all-forms/modules/ManagedDiskCMKAccessPolicy.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-customer-managed-keys-all-forms/modules/ManagedServicesCMKAccessPolicy.bicep
Labels: bicep warnings, BPA

#13772 Add Bicep - web app GitHub deploy
  quickstarts/microsoft.web/web-app-github-deploy/README.md
  quickstarts/microsoft.web/web-app-github-deploy/azuredeploy.json
  quickstarts/microsoft.web/web-app-github-deploy/main.bicep
  quickstarts/microsoft.web/web-app-github-deploy/metadata.json
Labels: BPA

#13780 Add Bicep - multi-vm-lb-zones
  quickstarts/microsoft.compute/multi-vm-lb-zones/README.md
  quickstarts/microsoft.compute/multi-vm-lb-zones/azuredeploy.json
  quickstarts/microsoft.compute/multi-vm-lb-zones/main.bicep
  quickstarts/microsoft.compute/multi-vm-lb-zones/metadata.json
Labels: best practices violations, BPA

#13776 Add Bicep - azure firewall dns proxy
  quickstarts/microsoft.network/azure-firewall-dns-proxy/README.md
  quickstarts/microsoft.network/azure-firewall-dns-proxy/azuredeploy.json
  quickstarts/microsoft.network/azure-firewall-dns-proxy/main.bicep
  quickstarts/microsoft.network/azure-firewall-dns-proxy/metadata.json
Labels: best practices violations, BPA

#13766 Add Bicep - sql-server-2014-alwayson-existing-vnet-and-ad
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/README.md
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/azuredeploy.json
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/main.bicep
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/metadata.json
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/modules/create-failover-cluster.ps1.zip
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/modules/deploy-sql-alwayson.bicep
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/modules/deploy-sql-cluster.bicep
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/modules/deploy-sql-witness.bicep
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/modules/prepare-sql-alwayson-server.ps1.zip
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/nested/deploy-sql-alwayson.json
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/nested/deploy-sql-cluster.json
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/nested/deploy-sql-witness.json
  application-workloads/sql/sql-server-2014-alwayson-existing-vnet-and-ad/prereqs/prereq.azuredeploy.json
Labels: best practices violations, BPA, remove azuredeploy.json

#13779 Add Bicep - azurefirewall-sandbox-linux
  quickstarts/microsoft.network/azurefirewall-sandbox-linux/README.md
  quickstarts/microsoft.network/azurefirewall-sandbox-linux/azuredeploy.json
  quickstarts/microsoft.network/azurefirewall-sandbox-linux/main.bicep
  quickstarts/microsoft.network/azurefirewall-sandbox-linux/metadata.json
Labels: best practices violations, BPA

#13783 Add Bicep - mysql-paas-replication
  application-workloads/mysql/mysql-paas-replication/README.md
  application-workloads/mysql/mysql-paas-replication/azuredeploy.json
  application-workloads/mysql/mysql-paas-replication/main.bicep
  application-workloads/mysql/mysql-paas-replication/metadata.json
  application-workloads/mysql/mysql-paas-replication/modules/mysql.bicep
  application-workloads/mysql/mysql-paas-replication/modules/mysqlReplica.bicep
  application-workloads/mysql/mysql-paas-replication/nested/mysql.json
  application-workloads/mysql/mysql-paas-replication/nested/mysqlReplica.json
Labels: BPA

#13785 Add Bicep - webapp-linux-sonarqube-azuresql
  quickstarts/microsoft.web/webapp-linux-sonarqube-azuresql/README.md
  quickstarts/microsoft.web/webapp-linux-sonarqube-azuresql/azuredeploy.json
  quickstarts/microsoft.web/webapp-linux-sonarqube-azuresql/main.bicep
  quickstarts/microsoft.web/webapp-linux-sonarqube-azuresql/metadata.json
Labels: best practices violations, BPA

#13790 Add Bicep - function-app-create-dynamic-slot
  quickstarts/microsoft.web/function-app-create-dynamic-slot/README.md
  quickstarts/microsoft.web/function-app-create-dynamic-slot/azuredeploy.json
  quickstarts/microsoft.web/function-app-create-dynamic-slot/main.bicep
  quickstarts/microsoft.web/function-app-create-dynamic-slot/metadata.json
Labels: BPA

#13792 Add Bicep - databricks-all-in-one-template-for-vnet-injection-with-load-balancer
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-load-balancer/README.md
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-load-balancer/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-load-balancer/main.bicep
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-load-balancer/metadata.json
Labels: bicep warnings

#13793 Add Bicep - databricks-workspace-with-custom-vnet-address
  quickstarts/microsoft.databricks/databricks-workspace-with-custom-vnet-address/README.md
  quickstarts/microsoft.databricks/databricks-workspace-with-custom-vnet-address/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-workspace-with-custom-vnet-address/main.bicep
  quickstarts/microsoft.databricks/databricks-workspace-with-custom-vnet-address/metadata.json
Labels: bicep warnings

#13794 Add Bicep - azurefirewall-client-server-sandbox
  quickstarts/microsoft.network/azurefirewall-client-server-sandbox/README.md
  quickstarts/microsoft.network/azurefirewall-client-server-sandbox/azuredeploy.json
  quickstarts/microsoft.network/azurefirewall-client-server-sandbox/main.bicep
  quickstarts/microsoft.network/azurefirewall-client-server-sandbox/metadata.json
Labels: BPA

#13795 Add Bicep - databricks-all-in-one-template-for-vnet-injection-with-nat-gateway
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-nat-gateway/README.md
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-nat-gateway/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-nat-gateway/main.bicep
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-nat-gateway/metadata.json
Labels: bicep warnings

#13788 Added Bicep file - puppet-agent-linux
  application-workloads/puppet/puppet-agent-linux/README.md
  application-workloads/puppet/puppet-agent-linux/azuredeploy.json
  application-workloads/puppet/puppet-agent-linux/main.bicep
  application-workloads/puppet/puppet-agent-linux/metadata.json
Labels: BPA

#13751 ANF application volume group extension for HANA
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-storage/README.md
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-storage/azuredeploy.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-storage/azuredeploy.parameters.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-storage/metadata.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-storage/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-storage/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#13791 Azure Stack HCI 23H2 Windows VM with Data Disks and Domain Join
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/README.md
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/main.bicep
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/metadata.json
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/prereq.azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/vm-windows-disks-and-adjoin/prereq.main.bicep
Labels: manual validation required, best practices violations, readme violations

#13806 ANF application volume group extension for HANA CRR
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/README.md
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/azuredeploy.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/azuredeploy.parameters.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/metadata.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/prereqs/prereq.azuredeploy.json
  quickstarts/microsoft.netapp/anf-sap-hana/anf-sap-hana-crr-storage/prereqs/prereq.azuredeploy.parameters.json
Labels: best practices violations

#13798 Fix naming for Application Insights
  quickstarts/microsoft.web/functions-managed-identity/README.md
  quickstarts/microsoft.web/functions-managed-identity/azuredeploy.json
Labels: best practices violations, BPA
