Repository Azure/azure-quickstart-templates, pull requests merged in 2025-03, with the labels that each got.

#14342 Devcenter/devbox quick start
  quickstarts/microsoft.devcenter/devbox-quick-start/README.md
  quickstarts/microsoft.devcenter/devbox-quick-start/azuredeploy.json
  quickstarts/microsoft.devcenter/devbox-quick-start/azuredeploy.parameters.json
  quickstarts/microsoft.devcenter/devbox-quick-start/main.bicep
  quickstarts/microsoft.devcenter/devbox-quick-start/metadata.json
Labels: remove azuredeploy.json

#14340 update SharePoint template
  application-workloads/sharepoint/sharepoint-adfs/CHANGELOG.md
  application-workloads/sharepoint/sharepoint-adfs/README.md
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureDCVM.ps1
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureDCVM.zip
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureSPSE.ps1
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureSPSE.zip
  application-workloads/sharepoint/sharepoint-adfs/main.bicep
  application-workloads/sharepoint/sharepoint-adfs/metadata.json
Labels: bicep warnings

#14334 Fix typo
  application-workloads/ethereum/go-ethereum-on-ubuntu/README.md
Labels: best practices violations

#14341 [devbox-ready-to-code-image] Support installing VSCode extensions during image creation
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/images/axios.bicep
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/modules/resource-aib.bicep
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/tools/artifacts/_common/windows-visual-studio-marketplace-utils.Tests.ps1
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/tools/artifacts/_common/windows-visual-studio-marketplace-utils.psm1
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/tools/artifacts/windows-install-visualstudiocode-extension/windows-install-visualstudiocode-extension.Tests.ps1
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/tools/artifacts/windows-install-visualstudiocode-extension/windows-install-visualstudiocode-extension.ps1
  quickstarts/microsoft.devcenter/devbox-ready-to-code-image/tools/run-image-build.ps1
Labels: BPA

#14325 Dropped API version from 2024-02-28-preview and replaced it with 2024-09-20
  quickstarts/microsoft.healthdataaiservices/deidentification-service-create/azuredeploy.json
  quickstarts/microsoft.healthdataaiservices/deidentification-service-create/main.bicep
  quickstarts/microsoft.healthdataaiservices/deidentification-service-create/metadata.json
Labels: readme violations, remove azuredeploy.json

#14345 network security perimeter | New Documents | Bicep and ARM quickstart samples
  quickstarts/microsoft.network/network-security-perimeter-create/README.md
  quickstarts/microsoft.network/network-security-perimeter-create/azuredeploy.parameters.json
  quickstarts/microsoft.network/network-security-perimeter-create/main.bicep
  quickstarts/microsoft.network/network-security-perimeter-create/metadata.json
Labels: best practices violations

#14339 [Functions] Address issues with the new Flex Consumption template
  quickstarts/microsoft.web/function-app-flex-managed-identities/azuredeploy.parameters.json
  quickstarts/microsoft.web/function-app-flex-managed-identities/main.bicep
  quickstarts/microsoft.web/function-app-flex-managed-identities/metadata.json
Labels: best practices violations, BPA

#14348 Fix typo
  quickstarts/microsoft.apimanagement/api-management-logs-to-moesif-using-eventhub-webapp/README.md
Labels: BPA

#14356 network security perimeter | Update names in bicep file to align with other QS articles
  quickstarts/microsoft.network/network-security-perimeter-create/azuredeploy.json
  quickstarts/microsoft.network/network-security-perimeter-create/main.bicep
Labels: best practices violations, remove azuredeploy.json

#14347 Fix typo
  application-workloads/rds/rds-deployment-ha-gateway/azuredeploy.json
Labels: best practices violations

#14361 [Functions] Flex quickstart add generated ARM template file
  quickstarts/microsoft.web/function-app-flex-managed-identities/azuredeploy.json
Labels: best practices violations, BPA, remove azuredeploy.json

#14362 FinOps toolkit 0.8 - finops-hub update
  quickstarts/microsoft.costmanagement/finops-hub/README.md
  quickstarts/microsoft.costmanagement/finops-hub/azuredeploy.json
  quickstarts/microsoft.costmanagement/finops-hub/dashboard.json
  quickstarts/microsoft.costmanagement/finops-hub/main.bicep
  quickstarts/microsoft.costmanagement/finops-hub/metadata.json
  quickstarts/microsoft.costmanagement/finops-hub/modules/azuretimezones.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/dataExplorer.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/dataFactory.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/ftkver.txt
  quickstarts/microsoft.costmanagement/finops-hub/modules/hub.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/keyVault.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Common.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/Copy-FileToAzureBlob.ps1
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/HubSetup.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/IngestionSetup.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/OpenDataFunctions.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/OpenDataFunctions_resource_type_1.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/OpenDataFunctions_resource_type_2.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/OpenDataFunctions_resource_type_3.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/OpenDataFunctions_resource_type_4.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/storage.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/vnet.bicep
Labels: best practices violations, BPA, remove azuredeploy.json

#14375 Studio to Foundry: aifoundry-networking-aoao
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/README.md
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/azuredeploy.json
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/azuredeploy.parameters.json
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/images/authentication-methods.png
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/images/hub-workspace.png
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/images/key-vault.png
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/images/managed-virtual-network.png
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/images/mfa.png
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/main.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/metadata.json
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/aiServices.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/applicationInsights.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/containerRegistry.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/functions.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/hub.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/keyVault.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/logAnalytics.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/privateEndpoints.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/project.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/storageAccount.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/virtualMachine.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/modules/virtualNetwork.bicep
  quickstarts/microsoft.machinelearningservices/aifoundry-networking-aoao/params.bicepparam
  quickstarts/microsoft.machinelearningservices/aistudio-networking-aoao/metadata.json
Labels: best practices violations, bicep warnings, BPA, remove azuredeploy.json

#14370 Updating Route Server Templates to use /26 Subnet
  quickstarts/microsoft.network/route-server/azuredeploy.json
  quickstarts/microsoft.network/route-server/main.bicep
Labels: best practices violations, remove azuredeploy.json

#14366 Role assignments names added with existing name guid
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14284 GitHub Enterprise Template - set storage account's minimum TLS version to TLSv1.2
  application-workloads/github-enterprise/github-enterprise/azuredeploy.json
Labels: metadata violations, best practices violations, BPA, duplicate foldername

#14388 update to bicep to match template
  quickstarts/microsoft.compute/vm-simple-linux/azureDeploy.json
  quickstarts/microsoft.compute/vm-simple-linux/main.bicep
Labels: PORTAL SAMPLE, BPA

#14377 Devcenter/Improve Dev Box Quick Start Experience
  quickstarts/microsoft.devcenter/devbox-quick-start/azuredeploy.json
  quickstarts/microsoft.devcenter/devbox-quick-start/azuredeploy.parameters.json
  quickstarts/microsoft.devcenter/devbox-quick-start/main.bicep
Labels: best practices violations, bicep warnings, remove azuredeploy.json

#14380 Updating sku for PIP on GHE deployment templates.
  application-workloads/github-enterprise/github-enterprise/azuredeploy.json
Labels: metadata violations, best practices violations, BPA, duplicate foldername
