Repository Azure/azure-quickstart-templates, pull requests merged in 2025-08, with the labels that each got.

#14562 Add allowSharedKeyAccess: false to StorageAccountConfigurations for Diagnostics Storage Account and remove unused param
  quickstarts/microsoft.azurestackhci/upgrade-cluster-for-usgov/azuredeploy.json
  quickstarts/microsoft.azurestackhci/upgrade-cluster-for-usgov/azuredeploy.parameters.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14561 Add allowSharedKeyAccess: false to StorageAccountConfigurations for Diagnostics Storage Account
  quickstarts/microsoft.azurestackhci/create-cluster-rac-enabled/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14563 Add allowSharedKeyAccess: false to StorageAccountConfigurations for Diagnostics Storage Account and remove unused param
  quickstarts/microsoft.azurestackhci/upgrade-cluster/azuredeploy.json
  quickstarts/microsoft.azurestackhci/upgrade-cluster/azuredeploy.parameters.json
Labels: manual validation required, best practices violations, BPA

#14566 Add allowSharedKeyAccess: false to StorageAccountConfigurations for Diagnostics Storage Account
  quickstarts/microsoft.azurestackhci/create-cluster-for-usgov/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14567 Add allowSharedKeyAccess: false to StorageAccountConfigurations for Diagnostics Storage Account
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14568 Add allowSharedKeyAccess: false to StorageAccountConfigurations for Diagnostics Storage Account
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-DualLink/azuredeploy.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14560 Add allowSharedKeyAccess: false to StorageAccountConfigurations for Diagnostics Storage Account
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14573 Foundry Hub template fix: remove apiProperties: statisticsEnabled
  quickstarts/microsoft.machinelearningservices/aifoundry-basics/modules/dependent-resources.bicep
Labels: BPA

#14575 Update entitlement management logic app template
  demos/identitygovernance-entitlementmanagement-extensibility-servicenow-sample-logicapp/azuredeploy.json
Labels: metadata violations, best practices violations, BPA

#14579 Updating Entitlement management templates with aud claim
  demos/identitygovernance-entitlementmanagement-extensibility-AccessPackageAssignment-sample-logicapp/azuredeploy.json
Labels: metadata violations, best practices violations, UPPERCASE, BPA
