Repository Azure/azure-quickstart-templates, pull requests merged in 2025-04, with the labels that each got.

#14389 update githubuser
  subscription-deployments/blueprints-new-blueprint/metadata.json
Labels: manual validation required

#14390 added enable automatic upgrade to GA extension in trusted launch linux quickstart
  quickstarts/microsoft.compute/vm-trustedlaunch-linux/main.bicep
Labels: best practices violations, BPA

#14320 remove depedency on ARB Service Pricipal
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.parameters.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14321 remove dependency on ARB SPN
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-2-node-switched-custom-storageip/azuredeploy.parameters.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14322 remove dependency on ARB SPN
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-DualLink/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-DualLink/azuredeploy.parameters.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14323 remove dependency on ARB SPN
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/azuredeploy.parameters.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14399 Node and cluster name validation added
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14416 Changes for RAC Cluster
  quickstarts/microsoft.azurestackhci/create-cluster-rac-enabled/README.md
  quickstarts/microsoft.azurestackhci/create-cluster-rac-enabled/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-rac-enabled/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/create-cluster-rac-enabled/metadata.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14392 Fix typo
  quickstarts/microsoft.compute/glassfish-on-suse/README.md
Labels: best practices violations

#14394 Fix typo
  quickstarts/microsoft.dataprotection/backup-create-mysqlflex-enable-protection/README.md
  quickstarts/microsoft.dataprotection/backup-create-mysqlflex-enable-protection/azuredeploy.json
  quickstarts/microsoft.dataprotection/backup-create-mysqlflex-enable-protection/main.bicep
  quickstarts/microsoft.dataprotection/backup-create-mysqlflex-enable-protection/metadata.json
Labels: metadata violations, best practices violations, remove azuredeploy.json

#14395 Fix typo
  quickstarts/microsoft.kusto/kusto-cosmos-db/README.md
Labels: bicep warnings, BPA

#14397 Fix typo
  quickstarts/microsoft.logic/logic-app-veter-pipeline/README.md
Labels: best practices violations, BPA

#14402 FinOps toolkit 0.9 - finops-hub update
  quickstarts/microsoft.costmanagement/finops-hub/azuredeploy.json
  quickstarts/microsoft.costmanagement/finops-hub/dashboard.json
  quickstarts/microsoft.costmanagement/finops-hub/docs/FTK Networking.vsdx
  quickstarts/microsoft.costmanagement/finops-hub/modules/dataExplorer.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/dataFactory.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/ftkver.txt
  quickstarts/microsoft.costmanagement/finops-hub/modules/hub.bicep
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/IngestionSetup.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/OpenDataFunctions_resource_type_1.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/OpenDataFunctions_resource_type_2.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/OpenDataFunctions_resource_type_3.kql
  quickstarts/microsoft.costmanagement/finops-hub/modules/scripts/OpenDataFunctions_resource_type_4.kql
  quickstarts/microsoft.costmanagement/finops-hub/schemas/reservationrecommendations_2023-05-01_mca.json
  quickstarts/microsoft.costmanagement/finops-hub/schemas/settings.json
Labels: best practices violations, BPA, remove azuredeploy.json

#14403 Darktrace vSensor: Collate templates
  application-workloads/darktrace/darktrace-vsensor-standalone/README.md
  application-workloads/darktrace/darktrace-vsensor-standalone/azuredeploy.json
  application-workloads/darktrace/darktrace-vsensor-standalone/azuredeploy.parameters.json
  application-workloads/darktrace/darktrace-vsensor-standalone/images/appendixa-completed-outputs.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/appendixa-completed-overview.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/appendixa-custom-deployment-validation.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/appendixa-input-params.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/architecture.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/build-your-own-template.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/click-save.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/create-a-resource.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/deploy-using-custom-templates.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/edit-template.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/load-the-template.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/select-the-template.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/template-deployment.png
  application-workloads/darktrace/darktrace-vsensor-standalone/images/template-form.png
  application-workloads/darktrace/darktrace-vsensor-standalone/main.bicep
  application-workloads/darktrace/darktrace-vsensor-standalone/metadata.json
Labels: best practices violations, readme violations, remove azuredeploy.json

#14404 Darktrace vSensor Updates: April 6.3.0 Update
  application-workloads/darktrace/darktrace-vsensor-autoscaling/azuredeploy.json
Labels: BPA

#14421 Fix typo
  application-workloads/jenkins/multiple-windows-vms-with-common-script/README.md
Labels: best practices violations, BPA

#14407 Remove load balancer properties
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-load-balancer/azuredeploy.json
  quickstarts/microsoft.databricks/databricks-all-in-one-template-for-vnet-injection-with-load-balancer/main.bicep
Labels: bicep warnings, remove azuredeploy.json

#14424 Implement Feedback on Quick Start Dev Box Template.
  quickstarts/microsoft.devcenter/devbox-quick-start/azuredeploy.json
  quickstarts/microsoft.devcenter/devbox-quick-start/azuredeploy.parameters.json
  quickstarts/microsoft.devcenter/devbox-quick-start/main.bicep
Labels: remove azuredeploy.json

#14425 Update template for SharePoint
  application-workloads/sharepoint/sharepoint-adfs/CHANGELOG.md
  application-workloads/sharepoint/sharepoint-adfs/README.md
  application-workloads/sharepoint/sharepoint-adfs/azuredeploy.json
  application-workloads/sharepoint/sharepoint-adfs/azuredeploy.parameters.json
  application-workloads/sharepoint/sharepoint-adfs/bastion.bicep
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureDCVM.ps1
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureDCVM.zip
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureFELegacy.ps1
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureFELegacy.zip
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureFESE.ps1
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureFESE.zip
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureSPLegacy.ps1
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureSPLegacy.zip
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureSPSE.ps1
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureSPSE.zip
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureSQLVM.ps1
  application-workloads/sharepoint/sharepoint-adfs/dsc/ConfigureSQLVM.zip
  application-workloads/sharepoint/sharepoint-adfs/firewall.bicep
  application-workloads/sharepoint/sharepoint-adfs/main.bicep
  application-workloads/sharepoint/sharepoint-adfs/metadata.json
  application-workloads/sharepoint/sharepoint-adfs/virtualMachine.bicep
  application-workloads/sharepoint/sharepoint-adfs/virtualNetwork.bicep
Labels: best practices violations, BPA

#14428 Add cloud deployment template for 2411.3 builds
  quickstarts/microsoft.azurestackhci/create-cluster-2411.3/README.md
  quickstarts/microsoft.azurestackhci/create-cluster-2411.3/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-2411.3/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/create-cluster-2411.3/metadata.json
Labels: manual validation required, best practices violations, readme violations, BPA
