Repository Azure/azure-quickstart-templates, pull requests merged in 2025-01, with the labels that each got.

#14277 update CB
  application-workloads/sccm/sccm-currentbranch/DSC/DCConfiguration.zip
  application-workloads/sccm/sccm-currentbranch/DSC/InstallCSForHierarchy.ps1
  application-workloads/sccm/sccm-currentbranch/DSC/PSConfiguration.ps1
  application-workloads/sccm/sccm-currentbranch/DSC/TemplateHelpDSC/TemplateHelpDSC.psd1
  application-workloads/sccm/sccm-currentbranch/DSC/TemplateHelpDSC/TemplateHelpDSC.psm1
  application-workloads/sccm/sccm-currentbranch/azuredeploy.json
  application-workloads/sccm/sccm-currentbranch/metadata.json
Labels: best practices violations

#14285 Azure AI Agents with Managed Network and UMI
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/README.md
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/azuredeploy.parameters.json
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/main.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/metadata.json
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/ai-search-role-assignments.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/ai-search-service.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/ai-service-role-assignments.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/cognitive-services-role-assignments.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/keyvault-role-assignments.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/network-secured-ai-hub.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/network-secured-ai-project.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/network-secured-dependent-resources.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/network-secured-identity.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/private-endpoint-and-dns.bicep
  quickstarts/microsoft.azure-ai-agent-service/network-secured-agent/modules-network-secured/storage-role-assignments.bicep
Labels: best practices violations, BPA

#14289 Azure Local 4 Nodes Switchless ARM Template
  quickstarts/microsoft.azurestackhci/create-cluster-4Nodes-Switchless-DualLink/README.md
  quickstarts/microsoft.azurestackhci/create-cluster-4Nodes-Switchless-DualLink/azuredeploy.json
  quickstarts/microsoft.azurestackhci/create-cluster-4Nodes-Switchless-DualLink/azuredeploy.parameters.json
  quickstarts/microsoft.azurestackhci/create-cluster-4Nodes-Switchless-DualLink/metadata.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14208 Support for Extension installation from Cloud
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14276 README / updated "Azure AI Studio" naming to "Azure AI Foundry"
  quickstarts/microsoft.machinelearningservices/aistudio-basics/README.md
Labels: BPA

#14290 Adding param basic-agent-identity template
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/README.md
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/azuredeploy.parameters.json
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/main.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/modules-basic/basic-ai-hub-identity.bicep
  quickstarts/microsoft.azure-ai-agent-service/basic-agent-identity/modules-basic/basic-ai-project-identity.bicep
Labels: best practices violations, BPA

#14294 Support for Extension installation from Cloud
  quickstarts/microsoft.azurestackhci/create-cluster-3Nodes-Switchless-SingleLink/azuredeploy.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14295 Support for Extension installation from Cloud
  quickstarts/microsoft.azurestackhci/create-cluster-4Nodes-Switchless-DualLink/azuredeploy.json
Labels: manual validation required, metadata violations, best practices violations, readme violations, UPPERCASE, BPA

#14299 AVM Module: fix policy output conditional logic
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/azuredeploy.json
  subscription-deployments/microsoft.network/virtual-network-manager-connectivity/main.bicep
Labels: manual validation required, metadata violations, best practices violations, readme violations

#14301 Add Fairfax deployment support for hci
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14305 Revert changes for Fairfax
  quickstarts/microsoft.azurestackhci/create-cluster/azuredeploy.json
Labels: manual validation required, best practices violations, readme violations, BPA

#14302 Darktrace Quickstart Updates - January 2025
  application-workloads/darktrace/darktrace-vsensor-autoscaling/azuredeploy.json
  application-workloads/darktrace/darktrace-vsensor-autoscaling/images/architecture-diagram.png
  application-workloads/darktrace/darktrace-vsensor-autoscaling/metadata.json
Labels: BPA
